using System.Net;
using Core.Application.Pipelines.Authorization;
using Core.CrossCuttingConcerns.Exceptions.Types;
using MediatR;
using Symplify.BackOffice.Application.Features.BulkEmails.Constants;
using Symplify.BackOffice.Application.Features.BulkEmails.Dtos;
using Symplify.BackOffice.Application.Features.BulkEmails.Rules;
using Symplify.BackOffice.Application.Features.BulkEmails.Services;
using Symplify.BackOffice.Application.Services.Mailing;
using Symplify.BackOffice.Application.Services.Repositories;
using Symplify.BackOffice.Domain.Communication;
using Symplify.BackOffice.Domain.Enums;

namespace Symplify.BackOffice.Application.Features.BulkEmails.Commands.Queue;

public sealed class QueueBulkEmailCommand : IRequest<QueueBulkEmailResponse>, ISecuredRequest
{
    public Guid CongressId { get; set; }

    public BulkEmailAudienceType AudienceType { get; set; }

    public string Culture { get; set; } = "tr-TR";

    public string Subject { get; set; } = string.Empty;

    public string Title { get; set; } = string.Empty;

    public string BodyText { get; set; } = string.Empty;

    public IReadOnlyCollection<string> ExcludedRecipientEmails { get; set; } = Array.Empty<string>();

    public IReadOnlyCollection<BulkEmailRecipientDto> AdditionalRecipients { get; set; } = Array.Empty<BulkEmailRecipientDto>();

    /// <summary>
    /// Absolute application base URL generated by the trusted WebUI controller.
    /// It is used only to create the anonymous open-tracking pixel URL.
    /// </summary>
    public string TrackingBaseUrl { get; set; } = string.Empty;

    public Guid? CurrentUserId { get; set; }

    public bool IsSuperAdmin { get; set; }

    public string[] Roles =>
    [
        BulkEmailsOperationClaims.Admin,
        BulkEmailsOperationClaims.Write,
        BulkEmailsOperationClaims.Add
    ];

    public sealed class Handler : IRequestHandler<QueueBulkEmailCommand, QueueBulkEmailResponse>
    {
        private readonly BulkEmailBusinessRules _rules;
        private readonly IBulkEmailRecipientResolver _recipientResolver;
        private readonly IBulkEmailComposer _composer;
        private readonly IMailOutboxMessageRepository _outboxRepository;
        private readonly IOrganizationMailConfigurationResolver _mailConfigurationResolver;

        public Handler(
            BulkEmailBusinessRules rules,
            IBulkEmailRecipientResolver recipientResolver,
            IBulkEmailComposer composer,
            IMailOutboxMessageRepository outboxRepository,
            IOrganizationMailConfigurationResolver mailConfigurationResolver)
        {
            _rules = rules;
            _recipientResolver = recipientResolver;
            _composer = composer;
            _outboxRepository = outboxRepository;
            _mailConfigurationResolver = mailConfigurationResolver;
        }

        public async Task<QueueBulkEmailResponse> Handle(
            QueueBulkEmailCommand request,
            CancellationToken cancellationToken)
        {
            EnsureRequiredContent(request);

            Symplify.BackOffice.Domain.Congress.Congress congress = await _rules.GetAuthorizedCongressAsync(
                request.CongressId,
                request.CurrentUserId,
                request.IsSuperAdmin,
                cancellationToken);

            BulkEmailRecipientResolutionResult resolution = await _recipientResolver.ResolveAdjustedAsync(
                request.CongressId,
                request.AudienceType,
                request.ExcludedRecipientEmails,
                request.AdditionalRecipients,
                cancellationToken);

            if (resolution.Recipients.Count == 0)
                throw new BusinessException(BulkEmailsMessages.RecipientNotFound);

            PreparedBulkEmailTemplate template = await _composer.PrepareAsync(
                request.CongressId,
                request.Culture,
                request.Subject,
                request.Title,
                request.BodyText,
                cancellationToken);

            ResolvedOrganizationMailConfiguration sender = await _mailConfigurationResolver.ResolveAsync(
                congress.OrganizationId,
                cancellationToken);

            Uri trackingBaseUri = NormalizeTrackingBaseUrl(request.TrackingBaseUrl);
            Guid batchId = Guid.NewGuid();
            DateTime createdAt = DateTime.UtcNow;
            string createdBy = request.CurrentUserId?.ToString() ?? "BulkEmail";

            List<MailOutboxMessage> messages = new(resolution.Recipients.Count);

            foreach (BulkEmailRecipientDto recipient in resolution.Recipients)
            {
                Guid trackingToken = Guid.NewGuid();
                string htmlBody = _composer.RenderHtmlBody(template, recipient.Name);
                htmlBody = AppendTrackingPixel(htmlBody, trackingBaseUri, trackingToken);

                messages.Add(new MailOutboxMessage
                {
                    Id = Guid.NewGuid(),
                    MailType = MailMessageType.BulkEmail,
                    ToEmail = recipient.Email,
                    ToName = Truncate(recipient.Name, 250),
                    Subject = TruncateRequired(_composer.RenderSubject(template, recipient.Name), 300),
                    HtmlBody = htmlBody,
                    Status = MailOutboxStatus.Pending,
                    BulkEmailBatchId = batchId,
                    OrganizationId = congress.OrganizationId,
                    CongressId = request.CongressId,
                    FromEmail = sender.FromEmail,
                    FromName = sender.FromName,
                    ReplyToEmail = sender.ReplyToEmail,
                    ReplyToName = sender.ReplyToName,
                    BulkEmailAudienceType = request.AudienceType,
                    BulkEmailCulture = NormalizeCulture(request.Culture),
                    TrackingToken = trackingToken,
                    CreatedDate = createdAt,
                    CreatedBy = createdBy
                });
            }

            await _outboxRepository.AddRangeAsync(messages, cancellationToken);

            return new QueueBulkEmailResponse
            {
                BatchId = batchId,
                QueuedCount = messages.Count,
                InvalidEmailCount = resolution.InvalidEmailCount,
                WarningLinks = template.WarningLinks
            };
        }

        private static void EnsureRequiredContent(QueueBulkEmailCommand request)
        {
            if (request.CongressId == Guid.Empty)
                throw new BusinessException(BulkEmailsMessages.CongressRequired);

            if (!Enum.IsDefined(request.AudienceType))
                throw new BusinessException(BulkEmailsMessages.AudienceRequired);

            if (string.IsNullOrWhiteSpace(request.Subject))
                throw new BusinessException(BulkEmailsMessages.SubjectRequired);

            if (request.Subject.Length > 200)
                throw new BusinessException(BulkEmailsMessages.SubjectTooLong);

            if (request.Subject.Contains('\r') || request.Subject.Contains('\n'))
                throw new BusinessException(BulkEmailsMessages.SubjectInvalid);

            if (string.IsNullOrWhiteSpace(request.Title))
                throw new BusinessException(BulkEmailsMessages.TitleRequired);

            if (request.Title.Length > 200)
                throw new BusinessException(BulkEmailsMessages.TitleTooLong);

            if (string.IsNullOrWhiteSpace(request.BodyText))
                throw new BusinessException(BulkEmailsMessages.BodyRequired);

            if (request.BodyText.Length > 20000)
                throw new BusinessException(BulkEmailsMessages.BodyTooLong);
        }

        private static Uri NormalizeTrackingBaseUrl(string value)
        {
            if (!Uri.TryCreate(value, UriKind.Absolute, out Uri? uri) ||
                !string.IsNullOrWhiteSpace(uri.UserInfo) ||
                (!string.Equals(uri.Scheme, Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase) &&
                 !string.Equals(uri.Scheme, Uri.UriSchemeHttp, StringComparison.OrdinalIgnoreCase)))
            {
                throw new BusinessException(BulkEmailsMessages.TrackingBaseUrlInvalid);
            }

            string normalized = uri.AbsoluteUri.TrimEnd('/') + "/";
            return new Uri(normalized, UriKind.Absolute);
        }

        private static string AppendTrackingPixel(string htmlBody, Uri trackingBaseUri, Guid trackingToken)
        {
            Uri trackingUri = new(trackingBaseUri, $"mail-tracking/open/{trackingToken:D}");
            string safeUrl = WebUtility.HtmlEncode(trackingUri.AbsoluteUri);
            string pixel = $"<img src=\"{safeUrl}\" width=\"1\" height=\"1\" alt=\"\" aria-hidden=\"true\" style=\"display:block;width:1px;height:1px;border:0;opacity:0;overflow:hidden;\" />";

            int bodyClosingIndex = htmlBody.LastIndexOf("</body>", StringComparison.OrdinalIgnoreCase);
            return bodyClosingIndex >= 0
                ? htmlBody.Insert(bodyClosingIndex, pixel)
                : htmlBody + pixel;
        }

        private static string NormalizeCulture(string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return "tr-TR";

            string normalized = value.Trim();
            return normalized.Length <= 15 ? normalized : normalized[..15];
        }

        private static string? Truncate(string? value, int maxLength)
        {
            if (string.IsNullOrWhiteSpace(value))
                return null;

            string normalized = value
                .Replace("\r", " ", StringComparison.Ordinal)
                .Replace("\n", " ", StringComparison.Ordinal)
                .Trim();

            return normalized.Length <= maxLength ? normalized : normalized[..maxLength];
        }

        private static string TruncateRequired(string value, int maxLength)
        {
            string normalized = (value ?? string.Empty)
                .Replace("\r", " ", StringComparison.Ordinal)
                .Replace("\n", " ", StringComparison.Ordinal)
                .Trim();

            return normalized.Length <= maxLength ? normalized : normalized[..maxLength];
        }
    }
}
