namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class AbstractBookResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("BackOffice.AbstractBook", "BackOffice.Sidebar.AbstractBook", "Özet Kitabı Oluştur", "Create Abstract Book"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PageTitle", "Özet Kitabı Oluştur", "Create Abstract Book"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PageDescription", "Kongre bildirilerini filtreleyin, kitap içeriğini yapılandırın ve profesyonel PDF veya Word çıktısı oluşturun.", "Filter congress submissions, configure book content, and generate a professional PDF or Word document."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.Badge", "Yayın Oluşturucu", "Publication Builder"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.Congress", "Kongre", "Congress"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.TotalSubmissions", "Toplam Bildiri", "Total Submissions"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.NoCongress", "Özet kitabı oluşturulabilecek aktif kongre bulunamadı.", "No active congress is available for abstract book generation."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.NoFilteredSubmissions", "Seçilen filtrelere uygun bildiri bulunamadı.", "No submissions match the selected filters."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.ContentLanguageRequired", "En az bir içerik dili seçilmelidir.", "At least one content language must be selected."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.ValidationTitle", "Kontrol Gerekli", "Review Required"),

        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.ContentSettings", "Kitap İçerik Ayarları", "Book Content Settings"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.ContentSettingsDescription", "Belgede bulunacak bölümleri, dilleri ve bildiri sıralamasını belirleyin.", "Choose the sections, languages, and submission ordering used in the document."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeCover", "Kapak Sayfası", "Cover Page"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeCoverHelp", "Kongre ve yayın bilgileriyle profesyonel kapak ekler.", "Adds a professional cover using congress and publication details."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludePublicationInfo", "Yayın Künyesi", "Publication Information"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludePublicationInfoHelp", "Editör, ISBN, yayınevi ve baskı bilgilerini gösterir.", "Shows editor, ISBN, publisher, and edition information."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeBoards", "Kongre Kurulları", "Congress Boards"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeBoardsHelp", "Aktif kongre kurullarını ve üyelerini ekler.", "Includes active congress boards and their members."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeTableOfContents", "İçindekiler", "Table of Contents"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeTableOfContentsHelp", "Bildiri başlıklarını sayfa numaralarıyla listeler.", "Lists submission titles with page numbers."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.StartEachSubmissionOnNewPage", "Her Bildiri Yeni Sayfadan Başlasın", "Start Each Submission on a New Page"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.StartEachSubmissionOnNewPageHelp", "Her bildiriyi bağımsız kitap bölümü olarak düzenler.", "Formats each submission as an independent book section."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeTurkishContent", "Türkçe İçerik", "Turkish Content"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeTurkishContentHelp", "Türkçe başlık, özet ve anahtar kelimeleri ekler.", "Includes Turkish title, abstract, and keywords."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeEnglishContent", "İngilizce İçerik", "English Content"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeEnglishContentHelp", "İngilizce başlık, abstract ve keywords alanlarını ekler.", "Includes English title, abstract, and keywords."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeOrcid", "ORCID Bilgileri", "ORCID Information"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeOrcidHelp", "Yazarların mevcut ORCID numaralarını gösterir.", "Displays available ORCID identifiers for authors."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeInstitutions", "Kurum Bilgileri", "Institution Information"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeInstitutionsHelp", "Kurumları tekilleştirerek dipnot düzeninde gösterir.", "Deduplicates institutions and displays them as affiliations."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeCorrespondingAuthor", "Sorumlu Yazar", "Corresponding Author"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.IncludeCorrespondingAuthorHelp", "Sorumlu yazarı ve mevcut e-posta bilgisini belirtir.", "Identifies the corresponding author and available email address."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.SortMode", "Bildiri Sıralaması", "Submission Ordering"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.SortSubmissionNumber", "Bildiri Numarasına Göre", "By Submission Number"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.SortTitle", "Başlığa Göre", "By Title"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.SortTopic", "Konuya Göre", "By Topic"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.SortSubmissionType", "Bildiri Türüne Göre", "By Submission Type"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.SortProgramOrder", "Etkinlik Programı Sırasına Göre", "By Event Programme Order"),

        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.CoverDesign", "Kapak Tasarımı", "Cover Design"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.CoverDesignDescription", "Kurumsal yayın kimliğine uygun kapak temasını ve temel bilgileri belirleyin.", "Choose a cover theme and publication details aligned with the corporate identity."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.ThemeCorporate", "Kurumsal", "Corporate"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.ThemeMinimal", "Minimal", "Minimal"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.ThemeEditorial", "Editoryal", "Editorial"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.BookTitle", "Kitap Başlığı", "Book Title"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.EnglishBookTitle", "İngilizce Kitap Başlığı", "English Book Title"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.Editor", "Editör", "Editor"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.Isbn", "ISBN", "ISBN"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PublicationYear", "Yayın Yılı", "Publication Year"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.City", "Şehir", "City"),

        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PublicationInfo", "Yayın Künyesi Bilgileri", "Publication Information"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PublicationInfoDescription", "Boş bırakılan alanlar PDF ve Word çıktısında gösterilmez.", "Empty fields are omitted from PDF and Word output."),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.EditPublicationInfo", "Künye Bilgilerini Düzenle", "Edit Publication Information"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PublishingDirector", "Yayın Yönetmeni", "Publishing Director"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.CoverDesigner", "Kapak Tasarımı", "Cover Design"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.InteriorDesigner", "İç Tasarım", "Interior Design"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.Publisher", "Yayınevi", "Publisher"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.EditionInformation", "Baskı Bilgisi", "Edition Information"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PublisherAddress", "Yayınevi Adresi", "Publisher Address"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PublisherEmail", "Yayınevi E-posta", "Publisher Email"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PublisherWebsite", "Yayınevi Web Sitesi", "Publisher Website"),

        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.SelectedSubmissionCount", "Kitaba Alınacak", "Included in Book"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.SubmissionUnit", "bildiri", "submissions"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PdfPreview", "PDF Önizle", "Preview PDF"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.PdfDownload", "PDF İndir", "Download PDF"),
        new("BackOffice.AbstractBook", "BackOffice.AbstractBook.WordDownload", "Word İndir", "Download Word")
    };
}
