namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class AcceptanceLetterResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        R("BackOffice.Submissions.AcceptanceLetter.DocumentTitle", "Resmi Kabul Mektubu", "Official Acceptance Letter"),
        R("BackOffice.Submissions.AcceptanceLetter.MainTitle", "KABUL MEKTUBU", "ACCEPTANCE LETTER"),
        R("BackOffice.Submissions.AcceptanceLetter.SubmissionCodeLabel", "Bildiri Kodu", "Submission Code"),
        R("BackOffice.Submissions.AcceptanceLetter.DateLabel", "Tarih", "Date"),
        R("BackOffice.Submissions.AcceptanceLetter.Salutation", "Sayın {AuthorFullName},", "Dear {AuthorFullName},"),
        R("BackOffice.Submissions.AcceptanceLetter.AcceptanceParagraph", "\"{SubmissionTitle}\" başlıklı {SubmissionTypeName} türündeki bildiriniz, {CongressTitle} kapsamında yapılan değerlendirme süreci sonucunda kabul edilmiştir.", "Your {SubmissionTypeName} titled \"{SubmissionTitle}\" has been accepted for presentation at {CongressTitle} after the review process."),
        R("BackOffice.Submissions.AcceptanceLetter.GuidelinesParagraph", "Sunum ve hazırlık süreciyle ilgili duyuruları kongrenin resmi kanallarından takip etmenizi rica ederiz.", "Please follow the official congress announcements for presentation and preparation guidelines."),
        R("BackOffice.Submissions.AcceptanceLetter.ThanksParagraph", "Kongremize göstermiş olduğunuz ilgi için teşekkür eder, çalışmalarınızda başarılar dileriz.", "Thank you for your interest in our congress. We wish you continued success in your academic work."),
        R("BackOffice.Submissions.AcceptanceLetter.SignerFallbackName", "Kongre Düzenleme Kurulu", "Congress Organizing Committee"),
        R("BackOffice.Submissions.AcceptanceLetter.SignerFallbackTitle", "Kongre Sekretaryası", "Congress Secretariat"),
        R("BackOffice.Submissions.AcceptanceLetter.GeneratedInfo", "Bu belge {SubmissionCode} numaralı bildiri için {GeneratedDate} tarihinde sistem tarafından oluşturulmuştur.", "This document was generated by the system for submission {SubmissionCode} on {GeneratedDate}.")
    };

    private static ResourceSeedDefinition R(string key, string tr, string en)
        => new("BackOffice", key, tr, en);
}
