namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class AuthResourceSeedDefinitions
{
    private static ResourceSeedDefinition R(string key, string tr, string en) => new("BackOffice.Auth", key, tr, en);

    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        R("BackOffice.Auth.Login.PageTitle", "Giriş - Symplify", "Login - Symplify"),
        R("BackOffice.Auth.Login.Title", "Hesabınıza Giriş Yapın", "Sign in to your account"),
        R("BackOffice.Auth.Login.Subtitle", "Devam etmek için e-posta adresiniz ve şifrenizle giriş yapın.", "Enter your email address and password to continue."),
        R("BackOffice.Auth.Login.OrganizationSubtitle", "{0} için giriş yapmaktasınız. Devam etmek için e-posta adresiniz ve şifrenizle giriş yapın.", "You are signing in for {0}. Enter your email address and password to continue."),
        R("BackOffice.Auth.Login.Button", "Giriş Yap", "Sign In"),
        R("BackOffice.Auth.Login.RememberMe", "Beni hatırla", "Remember me"),
        R("BackOffice.Auth.Login.ForgotPassword", "Şifremi unuttum", "Forgot password?"),
        R("BackOffice.Auth.Login.NoAccount", "Henüz hesabınız yok mu?", "Don’t have an account?"),
        R("BackOffice.Auth.Login.CreateAccount", "Hesap oluştur", "Create account"),

        R("BackOffice.Auth.Register.PageTitle", "Hesap Oluştur - Symplify", "Create Account - Symplify"),
        R("BackOffice.Auth.Register.Title", "Hesap Oluştur", "Create Account"),
        R("BackOffice.Auth.Register.Subtitle", "Bilgilerinizi girerek kayıt olun.", "Create your account by entering your information."),
        R("BackOffice.Auth.Register.OrganizationSubtitle", "{0} için hesap oluşturmaktasınız. Devam etmek için bilgilerinizi girin.", "You are creating an account for {0}. Enter your information to continue."),
        R("BackOffice.Auth.Register.Button", "Kayıt Ol", "Register"),
        R("BackOffice.Auth.Register.AlreadyHaveAccount", "Zaten hesabınız var mı?", "Already have an account?"),
        R("BackOffice.Auth.Register.SignIn", "Giriş Yap", "Sign In"),
        R("BackOffice.Auth.Register.TermsPrefix", "Kayıt olarak", "By creating an account, you agree to the"),
        R("BackOffice.Auth.Register.TermsLink", "Şartlar ve Koşullar", "Terms and Conditions"),
        R("BackOffice.Auth.Register.TermsMiddle", "ve", "and"),
        R("BackOffice.Auth.Register.PrivacyLink", "Gizlilik Politikası", "Privacy Policy"),
        R("BackOffice.Auth.Register.Success", "Kayıt işlemi tamamlandı. Hesabınızı aktifleştirmek için e-posta adresinize gönderilen doğrulama bağlantısını kullanın.", "Registration completed. Use the confirmation link sent to your email address to activate your account."),
        R("BackOffice.Auth.Register.PasswordHint", "Şifreniz en az 8 karakter, bir büyük harf, bir rakam ve bir özel karakter içermelidir.", "Your password must be at least 8 characters and contain an uppercase letter, a digit, and a special character."),

        R("BackOffice.Auth.ForgotPassword.PageTitle", "Şifremi Unuttum - Symplify", "Forgot Password - Symplify"),
        R("BackOffice.Auth.ForgotPassword.Title", "Şifremi Unuttum", "Forgot Password"),
        R("BackOffice.Auth.ForgotPassword.Subtitle", "Hesabınıza bağlı e-posta adresini girin. Uygunsa şifre sıfırlama bağlantısı gönderilecektir.", "Enter the email address associated with your account. If eligible, a reset link will be sent."),
        R("BackOffice.Auth.ForgotPassword.OrganizationSubtitle", "{0} için şifre sıfırlama işlemi yapmaktasınız. Devam etmek için e-posta adresinizi girin.", "You are resetting your password for {0}. Enter your email address to continue."),
        R("BackOffice.Auth.ForgotPassword.Button", "Devam Et", "Continue"),
        R("BackOffice.Auth.ForgotPassword.Success", "E-posta adresi sistemde kayıtlıysa şifre sıfırlama bağlantısı gönderildi.", "If the email address is registered, a password reset link has been sent."),
        R("BackOffice.Auth.ForgotPassword.BackToLogin", "Giriş ekranına dön", "Back to sign in"),

        R("BackOffice.Auth.ResetPassword.PageTitle", "Şifre Sıfırla - Symplify", "Reset Password - Symplify"),
        R("BackOffice.Auth.ResetPassword.Title", "Şifre Sıfırla", "Reset Password"),
        R("BackOffice.Auth.ResetPassword.Subtitle", "Yeni şifrenizi belirleyerek hesabınıza tekrar erişebilirsiniz.", "Set a new password to access your account again."),
        R("BackOffice.Auth.ResetPassword.OrganizationSubtitle", "{0} için şifrenizi yenilemektesiniz. Devam etmek için yeni şifrenizi belirleyin.", "You are updating your password for {0}. Set your new password to continue."),
        R("BackOffice.Auth.ResetPassword.Button", "Şifreyi Güncelle", "Update Password"),
        R("BackOffice.Auth.ResetPassword.Success", "Şifreniz güncellendi. Yeni şifrenizle giriş yapabilirsiniz.", "Your password has been updated. You can sign in with your new password."),

        R("BackOffice.Auth.ConfirmEmail.PageTitle", "E-posta Doğrulama - Symplify", "Email Confirmation - Symplify"),
        R("BackOffice.Auth.ConfirmEmail.SuccessTitle", "E-posta doğrulandı", "Email confirmed"),
        R("BackOffice.Auth.ConfirmEmail.SuccessMessage", "Hesabınız aktifleştirildi. Artık giriş yapabilirsiniz.", "Your account has been activated. You can now sign in."),
        R("BackOffice.Auth.ConfirmEmail.FailedTitle", "Doğrulama tamamlanamadı", "Confirmation could not be completed"),
        R("BackOffice.Auth.ConfirmEmail.FailedMessage", "Doğrulama bağlantısı geçersiz, süresi dolmuş veya daha önce kullanılmış olabilir.", "The confirmation link may be invalid, expired, or already used."),

        R("BackOffice.Auth.Field.Name", "Adınız", "First name"),
        R("BackOffice.Auth.Field.Surname", "Soyadınız", "Last name"),
        R("BackOffice.Auth.Field.Institution", "Kurum", "Institution"),
        R("BackOffice.Auth.Field.Title", "Ünvan", "Title"),
        R("BackOffice.Auth.Field.Congress", "Kongre", "Congress"),
        R("BackOffice.Auth.Field.Country", "Ülke", "Country"),
        R("BackOffice.Auth.Field.State", "Eyalet/İl", "State/Province"),
        R("BackOffice.Auth.Field.Phone", "Telefon numaranız", "Phone number"),
        R("BackOffice.Auth.Field.Email", "E-posta adresiniz", "Email address"),
        R("BackOffice.Auth.Field.Password", "Şifreniz", "Password"),
        R("BackOffice.Auth.Field.ConfirmPassword", "Şifre (Tekrar)", "Confirm password"),
        R("BackOffice.Auth.Field.SelectTitle", "Ünvan Seçin", "Select title"),
        R("BackOffice.Auth.Field.SelectCongress", "Kongre seçin", "Select congress"),
        R("BackOffice.Auth.Field.SelectCountry", "Ülke", "Country"),
        R("BackOffice.Auth.Field.SelectState", "Eyalet/İl", "State/Province"),

        R("BackOffice.Auth.Validation.InvalidCredentials", "E-posta adresi veya şifre hatalı.", "Email address or password is incorrect."),
        R("BackOffice.Auth.Validation.AccountLocked", "Hesabınız geçici olarak kilitlenmiştir. Lütfen daha sonra tekrar deneyin.", "Your account is temporarily locked. Please try again later."),
        R("BackOffice.Auth.Validation.AccountBlacklisted", "Hesabınız için işlem kısıtlaması bulunmaktadır. Sistem yöneticisi ile iletişime geçin.", "Your account is restricted. Please contact the system administrator."),
        R("BackOffice.Auth.Validation.EmailNotConfirmed", "Giriş yapmadan önce e-posta adresinizi doğrulamanız gerekir.", "You must confirm your email address before signing in."),
        R("BackOffice.Auth.Validation.EmailAlreadyRegistered", "Bu e-posta adresiyle kayıtlı bir hesap bulunmaktadır.", "An account with this email address already exists."),
        R("BackOffice.Auth.Validation.RegisterFailed", "Kayıt işlemi tamamlanamadı. Bilgileri kontrol ederek tekrar deneyin.", "Registration could not be completed. Check the information and try again."),
        R("BackOffice.Auth.Validation.ResetPasswordFailed", "Şifre sıfırlama işlemi tamamlanamadı. Bağlantı geçersiz veya süresi dolmuş olabilir.", "Password reset could not be completed. The link may be invalid or expired."),
        R("BackOffice.Auth.Validation.ConfirmEmailFailed", "E-posta doğrulama işlemi tamamlanamadı.", "Email confirmation could not be completed."),
        R("BackOffice.Auth.Validation.AuthorRoleMissing", "Yazar rolü sistemde tanımlı değil. Sistem yöneticisi ile iletişime geçin.", "Author role is not configured. Please contact the system administrator."),
        R("BackOffice.Auth.Validation.CongressRequired", "Kongre seçimi zorunludur.", "Congress selection is required."),
        R("BackOffice.Auth.Validation.CongressNotFound", "Seçilen kongre bulunamadı veya artık kullanılamıyor.", "The selected congress was not found or is no longer available."),
        R("BackOffice.Auth.Validation.OrganizationRequired", "Organizasyon bağlamı zorunludur. Lütfen portaldaki giriş veya kayıt bağlantısını kullanın.", "Organization context is required. Please use the sign-in or registration link from the portal."),
        R("BackOffice.Auth.Validation.OrganizationNotFound", "Organizasyon bulunamadı veya artık kullanılamıyor.", "The organization was not found or is no longer available."),
        R("BackOffice.Auth.Validation.OrganizationMembershipRequired", "Bu organizasyon için kullanıcı üyeliğiniz bulunamadı.", "You do not have an active membership for this organization."),
        R("BackOffice.Auth.Validation.TermsRequired", "Devam etmek için şartları ve gizlilik politikasını kabul etmelisiniz.", "You must accept the terms and privacy policy to continue."),
        R("BackOffice.Auth.Validation.NameRequired", "Ad alanı zorunludur.", "First name is required."),
        R("BackOffice.Auth.Validation.SurnameRequired", "Soyad alanı zorunludur.", "Last name is required."),
        R("BackOffice.Auth.Validation.InstitutionRequired", "Kurum alanı zorunludur.", "Institution is required."),
        R("BackOffice.Auth.Validation.TitleRequired", "Ünvan seçimi zorunludur.", "Title selection is required."),
        R("BackOffice.Auth.Validation.CountryRequired", "Ülke seçimi zorunludur.", "Country selection is required."),
        R("BackOffice.Auth.Validation.PhoneRequired", "Telefon numarası zorunludur.", "Phone number is required."),
        R("BackOffice.Auth.Validation.PhoneInvalid", "Telefon numarasını ülke kodu ile birlikte geçerli formatta giriniz.", "Enter a valid phone number including the country code."),
        R("BackOffice.Auth.Validation.EmailRequired", "E-posta adresi zorunludur.", "Email address is required."),
        R("BackOffice.Auth.Validation.EmailInvalid", "Geçerli bir e-posta adresi giriniz.", "Enter a valid email address."),
        R("BackOffice.Auth.Validation.PasswordRequired", "Şifre alanı zorunludur.", "Password is required."),
        R("BackOffice.Auth.Validation.PasswordPolicy", "Şifre en az 8 karakter olmalı; büyük harf, rakam ve özel karakter içermelidir.", "Password must be at least 8 characters and contain an uppercase letter, a digit, and a special character."),
        R("BackOffice.Auth.Validation.ConfirmPasswordRequired", "Şifre tekrarı zorunludur.", "Password confirmation is required."),
        R("BackOffice.Auth.Validation.PasswordsDoNotMatch", "Şifreler eşleşmiyor.", "Passwords do not match."),
        R("BackOffice.Auth.Validation.TokenRequired", "Şifre sıfırlama bağlantısı geçersiz.", "Password reset token is invalid."),

        R("BackOffice.Auth.Identity.PasswordTooShort", "Şifre belirlenen minimum uzunlukta değil.", "Password is shorter than the required minimum length."),
        R("BackOffice.Auth.Identity.PasswordRequiresNonAlphanumeric", "Şifre en az bir özel karakter içermelidir.", "Password must contain at least one special character."),
        R("BackOffice.Auth.Identity.PasswordRequiresDigit", "Şifre en az bir rakam içermelidir.", "Password must contain at least one digit."),
        R("BackOffice.Auth.Identity.PasswordRequiresUpper", "Şifre en az bir büyük harf içermelidir.", "Password must contain at least one uppercase letter."),
        R("BackOffice.Auth.Identity.DuplicateEmail", "Bu e-posta adresiyle kayıtlı bir hesap bulunmaktadır.", "An account with this email address already exists."),
        R("BackOffice.Auth.Identity.InvalidToken", "Bağlantı geçersiz veya süresi dolmuş olabilir.", "The link may be invalid or expired."),

        R("BackOffice.Auth.AccessDenied.Title", "Yetkisiz erişim", "Access denied"),
        R("BackOffice.Auth.AccessDenied.Message", "Bu işlemi yapmak için gerekli yetkiye sahip değilsiniz.", "You do not have the required permission to perform this operation."),
        R("BackOffice.Auth.AccessDenied.BackToLogin", "Giriş sayfasına dön", "Back to sign in"),
        R("BackOffice.Auth.AuthenticationRequired.Message", "Devam etmek için giriş yapmalısınız.", "You must sign in to continue."),

        R("BackOffice.Auth.EmailConfirmation.Subject", "Symplify e-posta doğrulama", "Symplify email confirmation"),
        R("BackOffice.Auth.EmailConfirmation.BodyHtml", "<p>Merhaba {0},</p><p>Symplify hesabınızı aktifleştirmek için aşağıdaki bağlantıya tıklayın:</p><p><a href=\"{1}\">E-posta adresimi doğrula</a></p><p>Bu işlemi siz yapmadıysanız bu e-postayı dikkate almayın.</p>", "<p>Hello {0},</p><p>Click the link below to activate your Symplify account:</p><p><a href=\"{1}\">Confirm my email address</a></p><p>If you did not request this, you can ignore this email.</p>"),
        R("BackOffice.Auth.ResetPassword.EmailSubject", "Symplify şifre sıfırlama", "Symplify password reset"),
        R("BackOffice.Auth.ResetPassword.EmailBodyHtml", "<p>Merhaba {0},</p><p>Şifrenizi yenilemek için aşağıdaki bağlantıya tıklayın:</p><p><a href=\"{1}\">Şifremi sıfırla</a></p><p>Bu işlemi siz yapmadıysanız bu e-postayı dikkate almayın.</p>", "<p>Hello {0},</p><p>Click the link below to reset your password:</p><p><a href=\"{1}\">Reset my password</a></p><p>If you did not request this, you can ignore this email.</p>")
    };
}
