namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class BackOfficeWorkflowResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("BackOffice.Sidebar", "BackOffice.Sidebar.Workflow", "Workflow", "Workflow"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.TransactionStatusPhases", "Status Fazları", "Status Phases"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.TransactionStatuses", "Transaction Durumları", "Transaction Statuses"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.TransactionStatusTransitions", "Durum Geçişleri", "Status Transitions"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.WorkflowTemplates", "Workflow Şablonları", "Workflow Templates"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.WorkflowTemplateTransitions", "Şablon Geçişleri", "Template Transitions"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.CongressWorkflows", "Kongre Workflowları", "Congress Workflows"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.PageTitle", "Status Fazları", "Status Phases"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.PageDescription", "Workflow durumlarını gruplayan fazları yönetin.", "Manage phases that group workflow statuses."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.ManagementTitle", "Status Fazları yönetimi", "Status Phases management"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.ListTitle", "Status Fazları Listesi", "Status Phases List"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.CreateButton", "Yeni Faz", "New Phase"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.CreateModalTitle", "Status Fazı Oluştur", "Create Status Phase"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.UpdateModalTitle", "Status Fazı Düzenle", "Edit Status Phase"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Fields.Code", "Sistem Anahtarı", "System Key"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Fields.Name", "Faz Adı", "Phase Name"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Fields.Order", "Sıra", "Order"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Fields.IsActive", "Aktif", "Active"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Placeholders.Code", "faz sistem anahtarını giriniz", "Enter phase system key"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Placeholders.Name", "faz adını giriniz", "Enter phase name"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Placeholders.Description", "faz açıklaması giriniz", "Enter phase description"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.EntityNotFound", "Status fazı bulunamadı.", "Status phase was not found."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.TranslationNotFound", "Status faz çevirisi bulunamadı.", "Status phase translation was not found."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.DefaultTranslationRequired", "Varsayılan dilde faz adı zorunludur.", "Phase name is required in the default language."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.DefaultTranslationCannotBeDeleted", "Varsayılan dil çevirisi silinemez.", "The default language translation cannot be deleted."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.AtLeastOneTranslationRequired", "En az bir dil için faz adı girilmelidir.", "A phase name must be entered for at least one language."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.LanguageRequired", "Dil bilgisi zorunludur.", "Language is required."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.CodeRequired", "Sistem anahtarı zorunludur.", "System key is required."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.CodeMaxLength", "Sistem anahtarı en fazla 100 karakter olabilir.", "System key can be at most 100 characters."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.CodeAlreadyExists", "Bu sistem anahtarıyla aynı status fazı zaten kayıtlı.", "A status phase with the same system key already exists."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.OrderCannotBeNegative", "Sıra değeri negatif olamaz.", "Order value cannot be negative."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.NameRequired", "Faz adı zorunludur.", "Phase name is required."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.NameMaxLength", "Faz adı en fazla 250 karakter olabilir.", "Phase name can be at most 250 characters."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.DescriptionMaxLength", "Açıklama en fazla 1000 karakter olabilir.", "Description can be at most 1000 characters."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.DuplicateTranslationNameInRequest", "Aynı dil için aynı faz adı birden fazla kez girilemez.", "The same phase name cannot be entered more than once for the same language."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.NameAlreadyExists", "Bu dil için aynı faz adı zaten kayıtlı.", "A phase with the same name already exists for this language."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.EntityUsedByTransactionStatus", "Bu faza bağlı transaction durumları bulunduğu için silinemez.", "This phase cannot be deleted because transaction statuses are linked to it."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Validation.ReorderEntityNotFound", "Sıralanacak status fazı bulunamadı.", "Status phase to reorder was not found."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Messages.Created", "Status fazı başarıyla oluşturuldu.", "Status phase was created successfully."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Messages.Updated", "Status fazı başarıyla güncellendi.", "Status phase was updated successfully."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Messages.Deleted", "Status fazı başarıyla silindi.", "Status phase was deleted successfully."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Messages.DeleteConfirm", "Bu status fazını silmek istediğinize emin misiniz?", "Are you sure you want to delete this status phase?"),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Messages.InvalidRecord", "Geçersiz status fazı bilgisi.", "Invalid status phase information."),
        new("BackOffice.TransactionStatusPhases", "BackOffice.TransactionStatusPhases.Messages.Reordered", "Status faz sıralaması başarıyla güncellendi.", "Status phase order was updated successfully."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.PageTitle", "Transaction Durumları", "Transaction Statuses"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.PageDescription", "Submission workflow durumlarını yönetin.", "Manage submission workflow statuses."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.ManagementTitle", "Transaction Durumları yönetimi", "Transaction Statuses management"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.ListTitle", "Transaction Durumları Listesi", "Transaction Statuses List"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.CreateButton", "Yeni Durum", "New Status"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.CreateModalTitle", "Transaction Durumu Oluştur", "Create Transaction Status"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.UpdateModalTitle", "Transaction Durumu Düzenle", "Edit Transaction Status"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Fields.Phase", "Faz", "Phase"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Fields.Code", "Sistem Anahtarı", "System Key"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Fields.Name", "Durum Adı", "Status Name"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Fields.Order", "Sıra", "Order"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Fields.IsEditable", "Düzenlenebilir", "Editable"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Fields.IsFinal", "Final Durum", "Final Status"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Fields.IsActive", "Aktif", "Active"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Placeholders.Phase", "faz seçiniz", "Select phase"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Placeholders.Code", "durum sistem anahtarını giriniz", "Enter status system key"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Placeholders.Name", "durum adını giriniz", "Enter status name"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Placeholders.Description", "durum açıklaması giriniz", "Enter status description"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.EntityNotFound", "Transaction durumu bulunamadı.", "Transaction status was not found."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.TranslationNotFound", "Transaction durum çevirisi bulunamadı.", "Transaction status translation was not found."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.DefaultTranslationRequired", "Varsayılan dilde durum adı zorunludur.", "Status name is required in the default language."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.DefaultTranslationCannotBeDeleted", "Varsayılan dil çevirisi silinemez.", "The default language translation cannot be deleted."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.AtLeastOneTranslationRequired", "En az bir dil için durum adı girilmelidir.", "A status name must be entered for at least one language."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.LanguageRequired", "Dil bilgisi zorunludur.", "Language is required."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.PhaseRequired", "Faz seçimi zorunludur.", "Phase selection is required."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.PhaseNotFound", "Seçilen faz bulunamadı.", "Selected phase was not found."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.PhasePassive", "Pasif faz altında durum oluşturulamaz.", "A status cannot be created under an inactive phase."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.CodeRequired", "Sistem anahtarı zorunludur.", "System key is required."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.CodeMaxLength", "Sistem anahtarı en fazla 100 karakter olabilir.", "System key can be at most 100 characters."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.CodeAlreadyExists", "Bu sistem anahtarıyla aynı transaction durumu zaten kayıtlı.", "A transaction status with the same system key already exists."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.OrderCannotBeNegative", "Sıra değeri negatif olamaz.", "Order value cannot be negative."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.NameRequired", "Durum adı zorunludur.", "Status name is required."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.NameMaxLength", "Durum adı en fazla 250 karakter olabilir.", "Status name can be at most 250 characters."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.DescriptionMaxLength", "Açıklama en fazla 1000 karakter olabilir.", "Description can be at most 1000 characters."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.DuplicateTranslationNameInRequest", "Aynı dil için aynı durum adı birden fazla kez girilemez.", "The same status name cannot be entered more than once for the same language."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.EntityUsedByTransition", "Bu durum bir geçişte kullanıldığı için silinemez.", "This status cannot be deleted because it is used by a transition."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.EntityUsedBySubmission", "Bu durum submission kayıtlarında kullanıldığı için silinemez.", "This status cannot be deleted because it is used by submissions."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.EntityUsedBySubmissionHistory", "Bu durum submission geçmişinde kullanıldığı için silinemez.", "This status cannot be deleted because it is used by submission history."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.FinalStatusCannotHaveOutgoingTransition", "Final durumdan aktif geçiş çıkamaz.", "A final status cannot have an active outgoing transition."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.ReorderEntityNotFound", "Sıralanacak transaction durumu bulunamadı.", "Transaction status to reorder was not found."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Validation.ReorderDifferentPhaseNotAllowed", "Transaction durumları sadece aynı faz içinde sıralanabilir.", "Transaction statuses can only be reordered within the same phase."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Messages.Created", "Transaction durumu başarıyla oluşturuldu.", "Transaction status was created successfully."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Messages.Updated", "Transaction durumu başarıyla güncellendi.", "Transaction status was updated successfully."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Messages.Deleted", "Transaction durumu başarıyla silindi.", "Transaction status was deleted successfully."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Messages.DeleteConfirm", "Bu transaction durumunu silmek istediğinize emin misiniz?", "Are you sure you want to delete this transaction status?"),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Messages.InvalidRecord", "Geçersiz transaction durum bilgisi.", "Invalid transaction status information."),
        new("BackOffice.TransactionStatuses", "BackOffice.TransactionStatuses.Messages.Reordered", "Transaction durum sıralaması başarıyla güncellendi.", "Transaction status order was updated successfully."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.PageTitle", "Durum Geçişleri", "Status Transitions"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.PageDescription", "Workflow durumları arasındaki global geçiş kataloğunu yönetin.", "Manage the global transition catalog between workflow statuses."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.ManagementTitle", "Durum Geçişleri yönetimi", "Status Transitions management"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.ListTitle", "Durum Geçişleri Listesi", "Status Transitions List"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.CreateButton", "Yeni Geçiş", "New Transition"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.CreateModalTitle", "Durum Geçişi Oluştur", "Create Status Transition"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.UpdateModalTitle", "Durum Geçişi Düzenle", "Edit Status Transition"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Fields.FromStatus", "Kaynak Durum", "From Status"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Fields.ToStatus", "Hedef Durum", "To Status"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Fields.Name", "Geçiş Adı", "Transition Name"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Fields.IsActive", "Aktif", "Active"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Placeholders.FromStatus", "kaynak durum seçiniz", "Select from status"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Placeholders.ToStatus", "hedef durum seçiniz", "Select to status"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Placeholders.Name", "geçiş adını giriniz", "Enter transition name"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Placeholders.Description", "geçiş açıklaması giriniz", "Enter transition description"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.EntityNotFound", "Durum geçişi bulunamadı.", "Status transition was not found."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.TranslationNotFound", "Durum geçiş çevirisi bulunamadı.", "Status transition translation was not found."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.DefaultTranslationRequired", "Varsayılan dilde geçiş adı zorunludur.", "Transition name is required in the default language."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.DefaultTranslationCannotBeDeleted", "Varsayılan dil çevirisi silinemez.", "The default language translation cannot be deleted."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.AtLeastOneTranslationRequired", "En az bir dil için geçiş adı girilmelidir.", "A transition name must be entered for at least one language."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.LanguageRequired", "Dil bilgisi zorunludur.", "Language is required."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.FromStatusRequired", "Kaynak durum seçimi zorunludur.", "From status selection is required."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.ToStatusRequired", "Hedef durum seçimi zorunludur.", "To status selection is required."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.FromStatusNotFound", "Kaynak durum bulunamadı.", "From status was not found."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.ToStatusNotFound", "Hedef durum bulunamadı.", "To status was not found."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.FromStatusPassive", "Pasif kaynak durumdan geçiş oluşturulamaz.", "A transition cannot start from an inactive status."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.ToStatusPassive", "Pasif hedef duruma geçiş oluşturulamaz.", "A transition cannot target an inactive status."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.FromStatusCannotBeFinal", "Final durumdan geçiş oluşturulamaz.", "A transition cannot start from a final status."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.FromAndToStatusCannotBeSame", "Kaynak ve hedef durum aynı olamaz.", "From status and to status cannot be the same."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.TransitionAlreadyExists", "Bu kaynak ve hedef durum arasında geçiş zaten kayıtlı.", "A transition between this from status and to status already exists."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.NameRequired", "Geçiş adı zorunludur.", "Transition name is required."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.NameMaxLength", "Geçiş adı en fazla 250 karakter olabilir.", "Transition name can be at most 250 characters."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.DescriptionMaxLength", "Açıklama en fazla 1000 karakter olabilir.", "Description can be at most 1000 characters."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Validation.DuplicateTranslationNameInRequest", "Aynı dil için aynı geçiş adı birden fazla kez girilemez.", "The same transition name cannot be entered more than once for the same language."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Messages.Created", "Durum geçişi başarıyla oluşturuldu.", "Status transition was created successfully."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Messages.Updated", "Durum geçişi başarıyla güncellendi.", "Status transition was updated successfully."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Messages.Deleted", "Durum geçişi başarıyla silindi.", "Status transition was deleted successfully."),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Messages.DeleteConfirm", "Bu durum geçişini silmek istediğinize emin misiniz?", "Are you sure you want to delete this status transition?"),
        new("BackOffice.TransactionStatusTransitions", "BackOffice.TransactionStatusTransitions.Messages.InvalidRecord", "Geçersiz durum geçiş bilgisi.", "Invalid status transition information."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.PageTitle", "Workflow Şablonları", "Workflow Templates"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.PageDescription", "Kongrelerde tekrar kullanılacak workflow şablonlarını yönetin.", "Manage reusable workflow templates for congresses."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.ManagementTitle", "Workflow Şablonları yönetimi", "Workflow Templates management"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.ListTitle", "Workflow Şablonları Listesi", "Workflow Templates List"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.CreateButton", "Yeni Şablon", "New Template"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.CreateModalTitle", "Workflow Şablonu Oluştur", "Create Workflow Template"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.UpdateModalTitle", "Workflow Şablonu Düzenle", "Edit Workflow Template"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Fields.Code", "Sistem Anahtarı", "System Key"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Fields.Name", "Şablon Adı", "Template Name"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Fields.InitialTransactionStatus", "Başlangıç Durumu", "Initial Status"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Fields.IsDefault", "Varsayılan", "Default"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Fields.IsActive", "Aktif", "Active"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Placeholders.Code", "şablon sistem anahtarını giriniz", "Enter template system key"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Placeholders.Name", "şablon adını giriniz", "Enter template name"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Placeholders.Description", "şablon açıklaması giriniz", "Enter template description"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Placeholders.InitialTransactionStatus", "başlangıç durumu seçiniz", "Select initial status"),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.EntityNotFound", "Workflow şablonu bulunamadı.", "Workflow template was not found."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.TranslationNotFound", "Workflow şablon çevirisi bulunamadı.", "Workflow template translation was not found."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.DefaultTranslationRequired", "Varsayılan dilde şablon adı zorunludur.", "Template name is required in the default language."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.CodeRequired", "Sistem anahtarı zorunludur.", "System key is required."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.CodeMaxLength", "Sistem anahtarı en fazla 100 karakter olabilir.", "System key can be at most 100 characters."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.CodeAlreadyExists", "Bu sistem anahtarıyla aynı workflow şablonu zaten kayıtlı.", "A workflow template with the same system key already exists."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.NameRequired", "Şablon adı zorunludur.", "Template name is required."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.NameMaxLength", "Şablon adı en fazla 250 karakter olabilir.", "Template name can be at most 250 characters."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.DescriptionMaxLength", "Açıklama en fazla 1000 karakter olabilir.", "Description can be at most 1000 characters."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.DuplicateTranslationNameInRequest", "Aynı dil için aynı şablon adı birden fazla kez girilemez.", "The same template name cannot be entered more than once for the same language."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.NameAlreadyExists", "Bu dil için aynı şablon adı zaten kayıtlı.", "A template with the same name already exists for this language."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.InitialStatusNotFound", "Başlangıç durumu bulunamadı.", "Initial status was not found."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.InitialStatusInactive", "Pasif bir durum başlangıç durumu olarak seçilemez.", "An inactive status cannot be selected as the initial status."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.InitialStatusIsFinal", "Final bir durum başlangıç durumu olarak seçilemez.", "A final status cannot be selected as the initial status."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Validation.EntityUsedByCongressWorkflow", "Bu şablon kongre workflow tanımında kullanıldığı için silinemez.", "This template cannot be deleted because it is used by a congress workflow."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Messages.Created", "Workflow şablonu başarıyla oluşturuldu.", "Workflow template was created successfully."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Messages.Updated", "Workflow şablonu başarıyla güncellendi.", "Workflow template was updated successfully."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Messages.Deleted", "Workflow şablonu başarıyla silindi.", "Workflow template was deleted successfully."),
        new("BackOffice.WorkflowTemplates", "BackOffice.WorkflowTemplates.Messages.TranslationDeleted", "Workflow şablon çevirisi başarıyla silindi.", "Workflow template translation was deleted successfully."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.PageTitle", "Workflow Şablon Geçişleri", "Workflow Template Transitions"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.PageDescription", "Workflow şablonlarının kullanacağı geçişleri yönetin.", "Manage transitions used by workflow templates."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.ManagementTitle", "Workflow Şablon Geçişleri yönetimi", "Workflow Template Transitions management"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.ListTitle", "Workflow Şablon Geçişleri Listesi", "Workflow Template Transitions List"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.CreateButton", "Yeni Şablon Geçişi", "New Template Transition"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.CreateModalTitle", "Şablon Geçişi Ekle", "Add Template Transition"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.UpdateModalTitle", "Şablon Geçişi Düzenle", "Edit Template Transition"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Fields.WorkflowTemplate", "Workflow Şablonu", "Workflow Template"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Fields.Transition", "Geçiş", "Transition"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Fields.Order", "Sıra", "Order"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Fields.IsActive", "Aktif", "Active"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Placeholders.WorkflowTemplate", "workflow şablonu seçiniz", "Select workflow template"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Placeholders.Transition", "geçiş seçiniz", "Select transition"),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Validation.EntityNotFound", "Workflow şablon geçişi bulunamadı.", "Workflow template transition was not found."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Validation.TemplateNotFound", "Workflow şablonu bulunamadı.", "Workflow template was not found."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Validation.TransitionNotFound", "Durum geçişi bulunamadı.", "Status transition was not found."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Validation.TransitionInactive", "Pasif bir geçiş workflow şablonuna eklenemez.", "An inactive transition cannot be added to a workflow template."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Validation.TransitionAlreadyExists", "Bu geçiş bu workflow şablonunda zaten kayıtlı.", "This transition already exists in this workflow template."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Validation.EntityUsedByCongressWorkflow", "Bu şablon geçişi kongre workflow tanımında kullanıldığı için silinemez.", "This template transition cannot be deleted because it is used by a congress workflow."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Validation.ReorderInvalid", "Workflow şablon geçiş sıralama isteği geçersiz.", "Workflow template transition reorder request is invalid."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Messages.Created", "Workflow şablon geçişi başarıyla eklendi.", "Workflow template transition was added successfully."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Messages.Updated", "Workflow şablon geçişi başarıyla güncellendi.", "Workflow template transition was updated successfully."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Messages.Deleted", "Workflow şablon geçişi başarıyla silindi.", "Workflow template transition was deleted successfully."),
        new("BackOffice.WorkflowTemplateTransitions", "BackOffice.WorkflowTemplateTransitions.Messages.Reordered", "Workflow şablon geçiş sıralaması başarıyla güncellendi.", "Workflow template transition order was updated successfully."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.PageTitle", "Kongre Workflow", "Congress Workflow"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.PageDescription", "Kongreye atanmış workflow geçişlerini yönetin.", "Manage workflow transitions assigned to a congress."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.ManagementTitle", "Kongre workflow yönetimi", "Congress workflow management"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.ManagementDescription", "Workflow şablonunu kongreye uygulayabilir, geçişleri düzenleyebilir veya sıralayabilirsiniz.", "You can apply a workflow template to the congress, edit transitions, or reorder them."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.ListTitle", "Kongre Workflow Geçişleri", "Congress Workflow Transitions"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.ListDescription", "Bu kongrede kullanılacak aktif/pasif workflow geçişlerini görüntüleyin.", "View active/passive workflow transitions used in this congress."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.ApplyTemplateButton", "Şablonu Uygula", "Apply Template"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.AddTransitionButton", "Geçiş Ekle", "Add Transition"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Fields.Congress", "Kongre", "Congress"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Fields.WorkflowTemplate", "Workflow Şablonu", "Workflow Template"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Fields.InitialTransactionStatus", "Başlangıç Durumu", "Initial Status"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Fields.Transition", "Geçiş", "Transition"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Fields.Order", "Sıra", "Order"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Fields.IsActive", "Aktif", "Active"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Placeholders.WorkflowTemplate", "workflow şablonu seçiniz", "Select workflow template"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Placeholders.InitialTransactionStatus", "başlangıç durumu seçiniz", "Select initial status"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Placeholders.Transition", "geçiş seçiniz", "Select transition"),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Validation.CongressNotFound", "Kongre bulunamadı.", "Congress was not found."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Validation.TemplateNotFound", "Workflow şablonu bulunamadı.", "Workflow template was not found."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Validation.TemplateHasNoTransitions", "Seçilen workflow şablonunda geçiş bulunmuyor.", "The selected workflow template has no transitions."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Validation.InitialStatusRequired", "Başlangıç durumu zorunludur.", "Initial status is required."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Validation.TransitionNotFound", "Kongre workflow geçişi bulunamadı.", "Congress workflow transition was not found."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Validation.TransitionAlreadyExists", "Bu geçiş bu kongre workflow’unda zaten kayıtlı.", "This transition already exists in this congress workflow."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Validation.EntityNotFound", "Kongre workflow kaydı bulunamadı.", "Congress workflow record was not found."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Validation.ReorderInvalid", "Kongre workflow geçiş sıralama isteği geçersiz.", "Congress workflow transition reorder request is invalid."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Messages.TemplateApplied", "Workflow şablonu kongreye başarıyla uygulandı.", "Workflow template was applied to the congress successfully."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Messages.TransitionAdded", "Kongre workflow geçişi başarıyla eklendi.", "Congress workflow transition was added successfully."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Messages.TransitionUpdated", "Kongre workflow geçişi başarıyla güncellendi.", "Congress workflow transition was updated successfully."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Messages.TransitionDeleted", "Kongre workflow geçişi başarıyla silindi.", "Congress workflow transition was deleted successfully."),
        new("BackOffice.CongressWorkflows", "BackOffice.CongressWorkflows.Messages.Reordered", "Kongre workflow geçiş sıralaması başarıyla güncellendi.", "Congress workflow transition order was updated successfully."),
    };
}
