namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class BackOfficeLookupResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("BackOffice.Topics", "BackOffice.Topics.PageTitle", "Konular", "Topics"),
        new("BackOffice.Topics", "BackOffice.Topics.PageDescription", "Kongrelerde kullanılacak konu başlıklarını yönetin.", "Manage topic headings used in congresses."),
        new("BackOffice.Topics", "BackOffice.Topics.ManagementTitle", "Konular yönetimi", "Topic management"),
        new("BackOffice.Topics", "BackOffice.Topics.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.Topics", "BackOffice.Topics.ListTitle", "Konular Listesi", "Topics List"),
        new("BackOffice.Topics", "BackOffice.Topics.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.Topics", "BackOffice.Topics.CreateButton", "Yeni Konu", "New Topic"),
        new("BackOffice.Topics", "BackOffice.Topics.CreateModalTitle", "Konu Oluştur", "Create Topic"),
        new("BackOffice.Topics", "BackOffice.Topics.UpdateModalTitle", "Konu Düzenle", "Edit Topic"),
        new("BackOffice.Topics", "BackOffice.Topics.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.Topics", "BackOffice.Topics.Fields.Name", "Konu Adı", "Topic Name"),
        new("BackOffice.Topics", "BackOffice.Topics.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.Topics", "BackOffice.Topics.Placeholders.Name", "konu adını giriniz", "Enter topic name"),
        new("BackOffice.Topics", "BackOffice.Topics.Placeholders.Description", "Açıklama giriniz", "Enter description"),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.EntityNotFound", "Konu bulunamadı.", "Topic was not found."),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.TranslationNotFound", "Konu çevirisi bulunamadı.", "Topic translation was not found."),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.DefaultTranslationRequired", "Varsayılan dilde konu adı zorunludur.", "Topic name is required in the default language."),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.DefaultTranslationCannotBeDeleted", "Varsayılan dil çevirisi silinemez.", "The default language translation cannot be deleted."),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.AtLeastOneTranslationRequired", "En az bir dil için konu adı girilmelidir.", "A topic name must be entered for at least one language."),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.LanguageRequired", "Dil bilgisi zorunludur.", "Language is required."),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.NameRequired", "Konu adı zorunludur.", "Topic name is required."),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.NameMaxLength", "Konu adı en fazla 250 karakter olabilir.", "Topic name can be at most 250 characters."),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.DescriptionMaxLength", "Açıklama en fazla 1000 karakter olabilir.", "Description can be at most 1000 characters."),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.NameAlreadyExists", "Bu dil için aynı konu adı zaten kayıtlı.", "A topic with the same name already exists for this language."),
        new("BackOffice.Topics.Validation", "BackOffice.Topics.Validation.DuplicateTranslationNameInRequest", "Aynı dil için aynı konu adı birden fazla kez girilemez.", "The same topic name cannot be entered more than once for the same language."),
        new("BackOffice.Topics.Messages", "BackOffice.Topics.Messages.Created", "Konu başarıyla oluşturuldu.", "Topic was created successfully."),
        new("BackOffice.Topics.Messages", "BackOffice.Topics.Messages.Updated", "Konu başarıyla güncellendi.", "Topic was updated successfully."),
        new("BackOffice.Topics.Messages", "BackOffice.Topics.Messages.Deleted", "Konu başarıyla silindi.", "Topic was deleted successfully."),
        new("BackOffice.Topics.Messages", "BackOffice.Topics.Messages.DeleteConfirm", "Bu kaydı silmek istediğinize emin misiniz?", "Are you sure you want to delete this record?"),
        new("BackOffice.Topics.Messages", "BackOffice.Topics.Messages.InvalidRecord", "Geçersiz konu bilgisi.", "Invalid topic information."),
        new("BackOffice.Titles", "BackOffice.Titles.PageTitle", "Ünvanlar", "Titles"),
        new("BackOffice.Titles", "BackOffice.Titles.PageDescription", "Kullanıcı profillerinde kullanılacak ünvanları yönetin.", "Manage titles used in user profiles."),
        new("BackOffice.Titles", "BackOffice.Titles.ManagementTitle", "Ünvanlar yönetimi", "Title management"),
        new("BackOffice.Titles", "BackOffice.Titles.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.Titles", "BackOffice.Titles.ListTitle", "Ünvanlar Listesi", "Titles List"),
        new("BackOffice.Titles", "BackOffice.Titles.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.Titles", "BackOffice.Titles.CreateButton", "Yeni Ünvan", "New Title"),
        new("BackOffice.Titles", "BackOffice.Titles.CreateModalTitle", "Ünvan Oluştur", "Create Title"),
        new("BackOffice.Titles", "BackOffice.Titles.UpdateModalTitle", "Ünvan Düzenle", "Edit Title"),
        new("BackOffice.Titles", "BackOffice.Titles.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.Titles", "BackOffice.Titles.Fields.Name", "Ünvan Adı", "Title Name"),
        new("BackOffice.Titles", "BackOffice.Titles.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.Titles", "BackOffice.Titles.Placeholders.Name", "ünvan adını giriniz", "Enter title name"),
        new("BackOffice.Titles", "BackOffice.Titles.Placeholders.Description", "Açıklama giriniz", "Enter description"),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.EntityNotFound", "Ünvan bulunamadı.", "Title was not found."),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.TranslationNotFound", "Ünvan çevirisi bulunamadı.", "Title translation was not found."),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.DefaultTranslationRequired", "Varsayılan dilde ünvan adı zorunludur.", "Title name is required in the default language."),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.DefaultTranslationCannotBeDeleted", "Varsayılan dil çevirisi silinemez.", "The default language translation cannot be deleted."),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.AtLeastOneTranslationRequired", "En az bir dil için ünvan adı girilmelidir.", "A title name must be entered for at least one language."),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.LanguageRequired", "Dil bilgisi zorunludur.", "Language is required."),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.NameRequired", "Ünvan adı zorunludur.", "Title name is required."),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.NameMaxLength", "Ünvan adı en fazla 250 karakter olabilir.", "Title name can be at most 250 characters."),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.DescriptionMaxLength", "Açıklama en fazla 1000 karakter olabilir.", "Description can be at most 1000 characters."),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.NameAlreadyExists", "Bu dil için aynı ünvan adı zaten kayıtlı.", "A title with the same name already exists for this language."),
        new("BackOffice.Titles.Validation", "BackOffice.Titles.Validation.DuplicateTranslationNameInRequest", "Aynı dil için aynı ünvan adı birden fazla kez girilemez.", "The same title name cannot be entered more than once for the same language."),
        new("BackOffice.Titles.Messages", "BackOffice.Titles.Messages.Created", "Ünvan başarıyla oluşturuldu.", "Title was created successfully."),
        new("BackOffice.Titles.Messages", "BackOffice.Titles.Messages.Updated", "Ünvan başarıyla güncellendi.", "Title was updated successfully."),
        new("BackOffice.Titles.Messages", "BackOffice.Titles.Messages.Deleted", "Ünvan başarıyla silindi.", "Title was deleted successfully."),
        new("BackOffice.Titles.Messages", "BackOffice.Titles.Messages.DeleteConfirm", "Bu kaydı silmek istediğinize emin misiniz?", "Are you sure you want to delete this record?"),
        new("BackOffice.Titles.Messages", "BackOffice.Titles.Messages.InvalidRecord", "Geçersiz ünvan bilgisi.", "Invalid title information."),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.PageTitle", "Doküman Tipleri", "Document Types"),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.PageDescription", "Kongre dokümanları için doküman tiplerini yönetin.", "Manage document types used for congress documents."),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.ManagementTitle", "Doküman Tipleri yönetimi", "Document Type management"),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.ListTitle", "Doküman Tipleri Listesi", "Document Types List"),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.CreateButton", "Yeni Doküman Tipi", "New Document Type"),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.CreateModalTitle", "Doküman Tipi Oluştur", "Create Document Type"),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.UpdateModalTitle", "Doküman Tipi Düzenle", "Edit Document Type"),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.Fields.Name", "Doküman Tipi Adı", "Document Type Name"),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.Placeholders.Name", "doküman tipi adını giriniz", "Enter document type name"),
        new("BackOffice.DocumentTypes", "BackOffice.DocumentTypes.Placeholders.Description", "Açıklama giriniz", "Enter description"),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.EntityNotFound", "Doküman Tipi bulunamadı.", "Document Type was not found."),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.TranslationNotFound", "Doküman Tipi çevirisi bulunamadı.", "Document Type translation was not found."),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.DefaultTranslationRequired", "Varsayılan dilde doküman tipi adı zorunludur.", "Document Type name is required in the default language."),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.DefaultTranslationCannotBeDeleted", "Varsayılan dil çevirisi silinemez.", "The default language translation cannot be deleted."),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.AtLeastOneTranslationRequired", "En az bir dil için doküman tipi adı girilmelidir.", "A document type name must be entered for at least one language."),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.LanguageRequired", "Dil bilgisi zorunludur.", "Language is required."),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.NameRequired", "Doküman Tipi adı zorunludur.", "Document Type name is required."),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.NameMaxLength", "Doküman Tipi adı en fazla 250 karakter olabilir.", "Document Type name can be at most 250 characters."),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.DescriptionMaxLength", "Açıklama en fazla 1000 karakter olabilir.", "Description can be at most 1000 characters."),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.NameAlreadyExists", "Bu dil için aynı doküman tipi adı zaten kayıtlı.", "A document type with the same name already exists for this language."),
        new("BackOffice.DocumentTypes.Validation", "BackOffice.DocumentTypes.Validation.DuplicateTranslationNameInRequest", "Aynı dil için aynı doküman tipi adı birden fazla kez girilemez.", "The same document type name cannot be entered more than once for the same language."),
        new("BackOffice.DocumentTypes.Messages", "BackOffice.DocumentTypes.Messages.Created", "Doküman Tipi başarıyla oluşturuldu.", "Document Type was created successfully."),
        new("BackOffice.DocumentTypes.Messages", "BackOffice.DocumentTypes.Messages.Updated", "Doküman Tipi başarıyla güncellendi.", "Document Type was updated successfully."),
        new("BackOffice.DocumentTypes.Messages", "BackOffice.DocumentTypes.Messages.Deleted", "Doküman Tipi başarıyla silindi.", "Document Type was deleted successfully."),
        new("BackOffice.DocumentTypes.Messages", "BackOffice.DocumentTypes.Messages.DeleteConfirm", "Bu kaydı silmek istediğinize emin misiniz?", "Are you sure you want to delete this record?"),
        new("BackOffice.DocumentTypes.Messages", "BackOffice.DocumentTypes.Messages.InvalidRecord", "Geçersiz doküman tipi bilgisi.", "Invalid document type information."),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.PageTitle", "Bildiri Tipleri", "Submission Types"),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.PageDescription", "Başvuru ve bildiri süreçlerinde kullanılacak bildiri tiplerini yönetin.", "Manage submission types used in submission workflows."),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.ManagementTitle", "Bildiri Tipleri yönetimi", "Submission Type management"),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.ListTitle", "Bildiri Tipleri Listesi", "Submission Types List"),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.CreateButton", "Yeni Bildiri Tipi", "New Submission Type"),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.CreateModalTitle", "Bildiri Tipi Oluştur", "Create Submission Type"),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.UpdateModalTitle", "Bildiri Tipi Düzenle", "Edit Submission Type"),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.Fields.Name", "Bildiri Tipi Adı", "Submission Type Name"),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.Placeholders.Name", "bildiri tipi adını giriniz", "Enter submission type name"),
        new("BackOffice.SubmissionTypes", "BackOffice.SubmissionTypes.Placeholders.Description", "Açıklama giriniz", "Enter description"),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.EntityNotFound", "Bildiri Tipi bulunamadı.", "Submission Type was not found."),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.TranslationNotFound", "Bildiri Tipi çevirisi bulunamadı.", "Submission Type translation was not found."),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.DefaultTranslationRequired", "Varsayılan dilde bildiri tipi adı zorunludur.", "Submission Type name is required in the default language."),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.DefaultTranslationCannotBeDeleted", "Varsayılan dil çevirisi silinemez.", "The default language translation cannot be deleted."),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.AtLeastOneTranslationRequired", "En az bir dil için bildiri tipi adı girilmelidir.", "A submission type name must be entered for at least one language."),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.LanguageRequired", "Dil bilgisi zorunludur.", "Language is required."),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.NameRequired", "Bildiri Tipi adı zorunludur.", "Submission Type name is required."),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.NameMaxLength", "Bildiri Tipi adı en fazla 250 karakter olabilir.", "Submission Type name can be at most 250 characters."),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.DescriptionMaxLength", "Açıklama en fazla 1000 karakter olabilir.", "Description can be at most 1000 characters."),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.NameAlreadyExists", "Bu dil için aynı bildiri tipi adı zaten kayıtlı.", "A submission type with the same name already exists for this language."),
        new("BackOffice.SubmissionTypes.Validation", "BackOffice.SubmissionTypes.Validation.DuplicateTranslationNameInRequest", "Aynı dil için aynı bildiri tipi adı birden fazla kez girilemez.", "The same submission type name cannot be entered more than once for the same language."),
        new("BackOffice.SubmissionTypes.Messages", "BackOffice.SubmissionTypes.Messages.Created", "Bildiri Tipi başarıyla oluşturuldu.", "Submission Type was created successfully."),
        new("BackOffice.SubmissionTypes.Messages", "BackOffice.SubmissionTypes.Messages.Updated", "Bildiri Tipi başarıyla güncellendi.", "Submission Type was updated successfully."),
        new("BackOffice.SubmissionTypes.Messages", "BackOffice.SubmissionTypes.Messages.Deleted", "Bildiri Tipi başarıyla silindi.", "Submission Type was deleted successfully."),
        new("BackOffice.SubmissionTypes.Messages", "BackOffice.SubmissionTypes.Messages.DeleteConfirm", "Bu kaydı silmek istediğinize emin misiniz?", "Are you sure you want to delete this record?"),
        new("BackOffice.SubmissionTypes.Messages", "BackOffice.SubmissionTypes.Messages.InvalidRecord", "Geçersiz bildiri tipi bilgisi.", "Invalid submission type information."),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.PageTitle", "Etkinlik Salonları", "Event Rooms"),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.PageDescription", "Kongre programında kullanılacak salonları yönetin.", "Manage rooms used in congress schedules."),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.ManagementTitle", "Etkinlik Salonları yönetimi", "Event Room management"),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.ListTitle", "Etkinlik Salonları Listesi", "Event Rooms List"),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.CreateButton", "Yeni Etkinlik Salonu", "New Event Room"),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.CreateModalTitle", "Etkinlik Salonu Oluştur", "Create Event Room"),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.UpdateModalTitle", "Etkinlik Salonu Düzenle", "Edit Event Room"),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.Fields.Name", "Etkinlik Salonu Adı", "Event Room Name"),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.Placeholders.Name", "etkinlik salonu adını giriniz", "Enter event room name"),
        new("BackOffice.EventRooms", "BackOffice.EventRooms.Placeholders.Description", "Açıklama giriniz", "Enter description"),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.EntityNotFound", "Etkinlik Salonu bulunamadı.", "Event Room was not found."),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.TranslationNotFound", "Etkinlik Salonu çevirisi bulunamadı.", "Event Room translation was not found."),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.DefaultTranslationRequired", "Varsayılan dilde etkinlik salonu adı zorunludur.", "Event Room name is required in the default language."),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.DefaultTranslationCannotBeDeleted", "Varsayılan dil çevirisi silinemez.", "The default language translation cannot be deleted."),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.AtLeastOneTranslationRequired", "En az bir dil için etkinlik salonu adı girilmelidir.", "A event room name must be entered for at least one language."),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.LanguageRequired", "Dil bilgisi zorunludur.", "Language is required."),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.NameRequired", "Etkinlik Salonu adı zorunludur.", "Event Room name is required."),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.NameMaxLength", "Etkinlik Salonu adı en fazla 250 karakter olabilir.", "Event Room name can be at most 250 characters."),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.DescriptionMaxLength", "Açıklama en fazla 1000 karakter olabilir.", "Description can be at most 1000 characters."),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.NameAlreadyExists", "Bu dil için aynı etkinlik salonu adı zaten kayıtlı.", "A event room with the same name already exists for this language."),
        new("BackOffice.EventRooms.Validation", "BackOffice.EventRooms.Validation.DuplicateTranslationNameInRequest", "Aynı dil için aynı etkinlik salonu adı birden fazla kez girilemez.", "The same event room name cannot be entered more than once for the same language."),
        new("BackOffice.EventRooms.Messages", "BackOffice.EventRooms.Messages.Created", "Etkinlik Salonu başarıyla oluşturuldu.", "Event Room was created successfully."),
        new("BackOffice.EventRooms.Messages", "BackOffice.EventRooms.Messages.Updated", "Etkinlik Salonu başarıyla güncellendi.", "Event Room was updated successfully."),
        new("BackOffice.EventRooms.Messages", "BackOffice.EventRooms.Messages.Deleted", "Etkinlik Salonu başarıyla silindi.", "Event Room was deleted successfully."),
        new("BackOffice.EventRooms.Messages", "BackOffice.EventRooms.Messages.DeleteConfirm", "Bu kaydı silmek istediğinize emin misiniz?", "Are you sure you want to delete this record?"),
        new("BackOffice.EventRooms.Messages", "BackOffice.EventRooms.Messages.InvalidRecord", "Geçersiz etkinlik salonu bilgisi.", "Invalid event room information."),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.PageTitle", "Değerlendirme Kriterleri", "Evaluation Criteria"),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.PageDescription", "Hakem değerlendirme süreçlerinde kullanılacak kriterleri yönetin.", "Manage criteria used in reviewer evaluation workflows."),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.ManagementTitle", "Değerlendirme Kriterleri yönetimi", "Evaluation Criterion management"),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.ManagementDescription", "Kayıtları listeleyebilir, yeni kayıt oluşturabilir veya mevcut kayıtları düzenleyebilirsiniz. Çeviri alanları dil sekmeleriyle yönetilir.", "You can list records, create new records, or update existing records. Translation fields are managed through language tabs."),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.ListTitle", "Değerlendirme Kriterleri Listesi", "Evaluation Criteria List"),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.ListDescription", "Aktif/pasif kayıtları görüntüleyin ve düzenleyin.", "View and edit active/passive records."),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.CreateButton", "Yeni Değerlendirme Kriteri", "New Evaluation Criterion"),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.CreateModalTitle", "Değerlendirme Kriteri Oluştur", "Create Evaluation Criterion"),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.UpdateModalTitle", "Değerlendirme Kriteri Düzenle", "Edit Evaluation Criterion"),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.TranslationModalDescription", "Çeviri bilgilerini dil sekmelerinden yönetebilirsiniz.", "You can manage translation information through language tabs."),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.Fields.Name", "Değerlendirme Kriteri Adı", "Evaluation Criterion Name"),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.Placeholders.Name", "değerlendirme kriteri adını giriniz", "Enter evaluation criterion name"),
        new("BackOffice.EvaluationCriteria", "BackOffice.EvaluationCriteria.Placeholders.Description", "Açıklama giriniz", "Enter description"),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.EntityNotFound", "Değerlendirme Kriteri bulunamadı.", "Evaluation Criterion was not found."),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.TranslationNotFound", "Değerlendirme Kriteri çevirisi bulunamadı.", "Evaluation Criterion translation was not found."),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.DefaultTranslationRequired", "Varsayılan dilde değerlendirme kriteri adı zorunludur.", "Evaluation Criterion name is required in the default language."),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.DefaultTranslationCannotBeDeleted", "Varsayılan dil çevirisi silinemez.", "The default language translation cannot be deleted."),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.AtLeastOneTranslationRequired", "En az bir dil için değerlendirme kriteri adı girilmelidir.", "A evaluation criterion name must be entered for at least one language."),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.LanguageRequired", "Dil bilgisi zorunludur.", "Language is required."),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.NameRequired", "Değerlendirme Kriteri adı zorunludur.", "Evaluation Criterion name is required."),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.NameMaxLength", "Değerlendirme Kriteri adı en fazla 250 karakter olabilir.", "Evaluation Criterion name can be at most 250 characters."),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.DescriptionMaxLength", "Açıklama en fazla 1000 karakter olabilir.", "Description can be at most 1000 characters."),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.NameAlreadyExists", "Bu dil için aynı değerlendirme kriteri adı zaten kayıtlı.", "A evaluation criterion with the same name already exists for this language."),
        new("BackOffice.EvaluationCriteria.Validation", "BackOffice.EvaluationCriteria.Validation.DuplicateTranslationNameInRequest", "Aynı dil için aynı değerlendirme kriteri adı birden fazla kez girilemez.", "The same evaluation criterion name cannot be entered more than once for the same language."),
        new("BackOffice.EvaluationCriteria.Messages", "BackOffice.EvaluationCriteria.Messages.Created", "Değerlendirme Kriteri başarıyla oluşturuldu.", "Evaluation Criterion was created successfully."),
        new("BackOffice.EvaluationCriteria.Messages", "BackOffice.EvaluationCriteria.Messages.Updated", "Değerlendirme Kriteri başarıyla güncellendi.", "Evaluation Criterion was updated successfully."),
        new("BackOffice.EvaluationCriteria.Messages", "BackOffice.EvaluationCriteria.Messages.Deleted", "Değerlendirme Kriteri başarıyla silindi.", "Evaluation Criterion was deleted successfully."),
        new("BackOffice.EvaluationCriteria.Messages", "BackOffice.EvaluationCriteria.Messages.DeleteConfirm", "Bu kaydı silmek istediğinize emin misiniz?", "Are you sure you want to delete this record?"),
        new("BackOffice.EvaluationCriteria.Messages", "BackOffice.EvaluationCriteria.Messages.InvalidRecord", "Geçersiz değerlendirme kriteri bilgisi.", "Invalid evaluation criterion information.")
    };
}
