namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class BulkEmailResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        R("BackOffice.Sidebar", "BackOffice.Sidebar.BulkEmails", "Toplu E-Posta", "Bulk Email"),
        R("BackOffice.Sidebar", "BackOffice.Sidebar.BulkEmails.Send", "E-Posta Gönder", "Send Email"),
        R("BackOffice.Sidebar", "BackOffice.Sidebar.BulkEmails.History", "Gönderim Geçmişi", "Sending History"),

        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.PageTitle", "Toplu E-Posta Gönder", "Send Bulk Email"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.PageDescription", "Seçili kongredeki hedef gruba mevcut kurumsal e-posta şablonuyla duyuru gönderin.", "Send an announcement to the selected congress audience using the existing corporate email template."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Section.Recipients", "Alıcı Seçimi", "Recipient Selection"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Section.Content", "E-Posta İçeriği", "Email Content"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Fields.Congress", "Kongre", "Congress"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Fields.Audience", "Kime Gönderilsin?", "Recipients"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Fields.Subject", "E-Posta Konusu", "Email Subject"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Fields.Title", "Mail Başlığı", "Email Title"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Fields.Body", "Mail İçeriği", "Email Content"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Placeholders.SelectCongress", "Kongre seçiniz", "Select a congress"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Placeholders.Subject", "Örn: Kongre ödeme süreci hakkında bilgilendirme", "Example: Information about the congress payment process"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Placeholders.Title", "Örn: Ödeme Hatırlatması", "Example: Payment Reminder"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Placeholders.Body", "Göndermek istediğiniz metni yazınız...", "Enter the message you want to send..."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Audience.AllRegistered", "Tüm Kayıt Olanlara", "All Registered Users"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Audience.AcceptedCorrespondingAuthors", "Sadece Kabul Alanlara", "Accepted Corresponding Authors"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Audience.AcceptedAllAuthors", "Kabul Alan Tüm Yazarlara", "All Authors of Accepted Submissions"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Audience.PaymentPending", "Ücret Ödemeyenlere", "Users with Pending Payment"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Audience.PaymentCompleted", "Ücret Ödeyenlere", "Users with Completed Payment"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.RecipientSummary", "Alıcı Özeti", "Recipient Summary"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.UniqueRecipients", "benzersiz alıcı", "unique recipients"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.BodyHelp", "HTML kodları çalıştırılmaz. HTTP/HTTPS bağlantıları doğrulanır; tehlikeli protokoller ve yerel ağ adresleri engellenir.", "HTML is not executed. HTTP/HTTPS links are validated; dangerous protocols and local network addresses are blocked."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Buttons.PreviewRecipients", "Alıcıları Ön İzle", "Preview Recipients"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Buttons.ManageRecipients", "Alıcıları Yönet", "Manage Recipients"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Buttons.PreviewContent", "Maili Ön İzle", "Preview Email"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Buttons.Queue", "Gönderimi Kuyruğa Al", "Queue Emails"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Confirm.Title", "Gönderimi Onayla", "Confirm Sending"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Confirm.Text", "{0} benzersiz alıcı için e-posta kuyruğu oluşturulacak. Devam etmek istiyor musunuz?", "An email queue will be created for {0} unique recipients. Do you want to continue?"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Confirm.Button", "Kuyruğa Al", "Queue"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Loading", "İşlem yapılıyor...", "Processing..."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.ErrorTitle", "Hata", "Error"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.GenericError", "İşlem sırasında bir hata oluştu.", "An error occurred while processing the request."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.SelectCongress", "Lütfen bir kongre seçiniz.", "Please select a congress."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.InvalidSummary", "({0} geçersiz adres atlandı)", "({0} invalid addresses skipped)"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.RecipientModalSummary", "{0} benzersiz alıcı, {1} geçersiz adres", "{0} unique recipients, {1} invalid addresses"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.RecipientNotFound", "Alıcı bulunamadı.", "No recipients found."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.UnsafeLinks", "Güvenli olmayan bağlantılar bulundu.", "Unsafe links were detected."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.HttpWarning", "HTTP kullanan bağlantılar bulundu. Mümkünse HTTPS kullanınız.", "Links using HTTP were detected. Use HTTPS whenever possible."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.NoDeliverableRecipient", "Seçilen grupta gönderilebilir alıcı bulunamadı.", "No deliverable recipients were found in the selected group."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.LoadingRecipients", "Alıcılar yükleniyor...", "Loading recipients..."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.RecipientModalSummaryV2", "{0} seçili alıcı · {1} filtre sonucu · {2} geçersiz adres", "{0} selected recipients · {1} filtered results · {2} invalid addresses"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.ManualEmailInvalid", "Geçerli bir e-posta adresi giriniz.", "Enter a valid email address."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.RecipientPageSummary", "Sayfa {0} / {1} · {2} kayıt", "Page {0} / {1} · {2} records"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Client.FilterChangeReset", "Alıcı grubu değiştiği için manuel alıcı seçimleri sıfırlandı.", "Manual recipient changes were reset because the audience filter changed."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.TitleV2", "Alıcı Listesini Yönet", "Manage Recipient List"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Help", "Filtre sonucundaki tüm alıcılar sayfalanarak listelenir. İsterseniz kişileri listeden çıkarabilir veya manuel alıcı ekleyebilirsiniz.", "All recipients matching the filter are listed with pagination. You can remove recipients or add recipients manually."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Title", "Alıcı Ön İzlemesi", "Recipient Preview"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Name", "Ad Soyad", "Full Name"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Email", "E-Posta", "Email"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.NamePlaceholder", "Ad Soyad", "Full name"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Add", "Alıcı Ekle", "Add Recipient"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Search", "Ara", "Search"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.SearchPlaceholder", "Ad soyad veya e-posta...", "Full name or email..."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.PageSize", "Sayfa Boyutu", "Page Size"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Source", "Kaynak", "Source"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Source.Filter", "Filtre", "Filter"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Source.Manual", "Manuel", "Manual"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Action", "İşlem", "Action"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Remove", "Listeden Çıkar", "Remove"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Reset", "Seçimi Sıfırla", "Reset Selection"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.ResetConfirmTitle", "Alıcı listesini sıfırla", "Reset recipient list"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.ResetConfirmText", "Manuel eklenen ve çıkarılan alıcılar silinecek. Devam etmek istiyor musunuz?", "Manually added and removed recipients will be cleared. Do you want to continue?"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Recipients.Pagination", "Sayfalama", "Pagination"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Content.Title", "Mail Ön İzlemesi", "Email Preview"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Modal.Content.FrameTitle", "E-posta ön izlemesi", "Email preview"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Success.Queued", "{0} e-posta gönderim kuyruğuna alındı.", "{0} emails were added to the sending queue."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Warning.InvalidEmails", "{0} geçersiz e-posta adresi atlandı.", "{0} invalid email addresses were skipped."),

        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Title", "Gönderim Geçmişi", "Sending History"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.RecordsTitle", "Gönderim Kayıtları", "Sending Records"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.NewEmail", "Yeni E-Posta Gönder", "Send New Email"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Description", "Kuyruk, SMTP gönderim ve yaklaşık açılma durumlarını alıcı bazında takip edin.", "Track queue, SMTP sending and approximate open status for each recipient."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Refresh", "Yenile", "Refresh"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Total", "Toplam", "Total"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Search", "Ara", "Search"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.SearchPlaceholder", "Alıcı adı, e-posta veya konu...", "Recipient name, email or subject..."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.StatusFilter", "Gönderim Durumu", "Sending Status"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.OpenFilter", "Açılma Durumu", "Open Status"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Loading", "Gönderim geçmişi yükleniyor...", "Loading sending history..."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Empty", "Bu kongre için henüz toplu e-posta kaydı bulunmuyor.", "No bulk email records exist for this congress yet."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.LoadError", "Gönderim geçmişi yüklenemedi.", "Sending history could not be loaded."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.PageSummary", "Sayfa {0} / {1} · Toplam {2} kayıt", "Page {0} / {1} · {2} records total"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Pagination", "Sayfalama", "Pagination"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Previous", "Önceki", "Previous"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Next", "Sonraki", "Next"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.NoError", "-", "-"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.OpenCount", "{0} kez", "{0} times"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.TrackingNoteTitle", "Durum bilgisi hakkında:", "About status information:"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.TrackingNote", "Gönderildi durumu SMTP sunucusunun mesajı kabul ettiğini gösterir; alıcının posta kutusuna kesin teslim garantisi değildir. Açıldı bilgisi görünmez izleme pikseline dayanır ve bazı e-posta istemcileri görselleri engellediği veya önceden yüklediği için yaklaşık sonuç verir.", "Sent means the SMTP server accepted the message; it does not guarantee final delivery to the recipient's mailbox. Opened is based on an invisible tracking pixel and is approximate because some email clients block or prefetch images."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Columns.CreatedAt", "Kuyruğa Alınma", "Queued At"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Columns.Recipient", "Alıcı", "Recipient"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Columns.Subject", "Konu", "Subject"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Columns.Audience", "Alıcı Grubu", "Audience"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Columns.SendStatus", "Gönderim", "Sending"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Columns.OpenStatus", "Açılma", "Open"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Columns.SentAt", "Gönderilme", "Sent At"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.History.Columns.Error", "Hata", "Error"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Status.Pending", "Kuyrukta", "Queued"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Status.Sent", "Gönderildi", "Sent"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Status.Failed", "Başarısız", "Failed"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Status.Cancelled", "İptal Edildi", "Cancelled"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.OpenStatus.Opened", "Açıldı", "Opened"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.OpenStatus.NotOpened", "Açılmadı", "Not Opened"),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.OpenStatus.Pending", "Henüz gönderilmedi", "Not Sent Yet"),

        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.CongressRequired", "Kongre seçimi zorunludur.", "Congress selection is required."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.CongressNotFound", "Seçilen kongre bulunamadı.", "The selected congress was not found."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.CongressAccessDenied", "Bu kongre için toplu e-posta gönderme yetkiniz bulunmuyor.", "You are not authorized to send bulk emails for this congress."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.AudienceRequired", "Geçerli bir alıcı grubu seçiniz.", "Select a valid recipient group."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.SubjectRequired", "E-posta konusu zorunludur.", "Email subject is required."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.SubjectTooLong", "E-posta konusu en fazla 200 karakter olabilir.", "Email subject can contain at most 200 characters."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.SubjectInvalid", "E-posta konusu satır sonu içeremez.", "Email subject cannot contain line breaks."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.TitleRequired", "Mail başlığı zorunludur.", "Email title is required."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.TitleTooLong", "Mail başlığı en fazla 200 karakter olabilir.", "Email title can contain at most 200 characters."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.BodyRequired", "Mail içeriği zorunludur.", "Email content is required."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.BodyTooLong", "Mail içeriği en fazla 20.000 karakter olabilir.", "Email content can contain at most 20,000 characters."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.UnsafeLinksDetected", "İçerikte güvenli olmayan bağlantılar bulundu. javascript, data, file, ftp, mailto, localhost ve özel ağ adresleri kullanılamaz.", "Unsafe links were detected. javascript, data, file, ftp, mailto, localhost and private network addresses are not allowed."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.RecipientNotFound", "Seçilen grupta gönderilebilir alıcı bulunamadı.", "No deliverable recipients were found in the selected group."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.RecipientSelectionInvalid", "Alıcı listesindeki manuel değişiklikler doğrulanamadı. Listeyi yeniden yükleyip tekrar deneyiniz.", "Manual recipient changes could not be validated. Reload the list and try again."),
        R("BackOffice.BulkEmails", "BackOffice.BulkEmails.Validation.TrackingBaseUrlInvalid", "Mail açılma takibi için uygulama adresi oluşturulamadı.", "The application URL required for email open tracking could not be generated.")
    };

    private static ResourceSeedDefinition R(string area, string key, string tr, string en)
        => new(area, key, tr, en);
}
