namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class CongressBoardMemberResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {

        R("BackOffice.CongressBoards.Create.Title", "Yeni Kurul", "New Board"),
        R("BackOffice.CongressBoards.Create.Description", "Bu kongrede kullanılacak kurul türünü ve çevirilerini oluşturun.", "Create the board type and its translations for this congress."),
        R("BackOffice.CongressBoards.Update.Title", "Kurul Düzenle", "Edit Board"),
        R("BackOffice.CongressBoards.Update.Description", "Seçili kurul türünün adını, açıklamasını ve durumunu güncelleyin.", "Update the selected board type name, description and status."),
        R("BackOffice.CongressBoards.Fields.Name", "Kurul Adı", "Board Name"),
        R("BackOffice.CongressBoards.Fields.Description", "Açıklama", "Description"),
        R("BackOffice.CongressBoards.Placeholders.Name", "Örn: Bilim Kurulu", "E.g. Scientific Committee"),
        R("BackOffice.CongressBoards.Buttons.Save", "Kurulu Kaydet", "Save Board"),
        R("BackOffice.CongressBoards.Buttons.Update", "Kurulu Güncelle", "Update Board"),
        R("BackOffice.CongressBoards.Messages.Created", "Kurul başarıyla oluşturuldu.", "Board was created successfully."),
        R("BackOffice.CongressBoards.Messages.Updated", "Kurul başarıyla güncellendi.", "Board was updated successfully."),
        R("BackOffice.CongressBoards.Messages.Deleted", "Kurul başarıyla silindi.", "Board was deleted successfully."),
        R("BackOffice.CongressBoards.Validation.CongressRequired", "Kongre bilgisi zorunludur.", "Congress is required."),
        R("BackOffice.CongressBoards.Validation.DefaultNameRequired", "Varsayılan dilde kurul adı zorunludur.", "Board name is required in the default language."),
        R("BackOffice.CongressBoards.Validation.ReorderRequired", "Sıralama için en az bir kurul seçilmelidir.", "At least one board must be selected for reordering."),
        R("BackOffice.CongressBoards.Validation.InvalidReorderList", "Kurul sıralama listesi geçersizdir.", "The board reorder list is invalid."),
        R("BackOffice.CongressBoardMembers.ListTitle", "Kurullar", "Committees"),
        R("BackOffice.CongressBoardMembers.ListDescription", "Tüm kurul üyelerini tek tabloda görüntüleyin, filtreleyin veya Excel ile toplu yükleyin.", "View, filter, or bulk import all committee members in a single table."),
        R("BackOffice.CongressBoardMembers.Buttons.New", "Yeni Kurul Üyesi", "New Committee Member"),
        R("BackOffice.CongressBoardMembers.Buttons.ExcelUpload", "Excel ile Yükle", "Upload with Excel"),
        R("BackOffice.CongressBoardMembers.Buttons.ExcelTemplate", "Excel Şablonu İndir", "Download Excel Template"),
        R("BackOffice.CongressBoardMembers.Buttons.Save", "Kurul Üyesini Kaydet", "Save Committee Member"),
        R("BackOffice.CongressBoardMembers.Buttons.Update", "Kurul Üyesini Güncelle", "Update Committee Member"),
        R("BackOffice.CongressBoardMembers.Buttons.Upload", "Yükle", "Upload"),
        R("BackOffice.CongressBoardMembers.Buttons.SelectPhoto", "Fotoğraf Seç", "Select Photo"),
        R("BackOffice.CongressBoardMembers.Buttons.SelectExcel", "Excel Dosyası Seç", "Select Excel File"),
        R("BackOffice.CongressBoardMembers.Create.Title", "Yeni Kurul Üyesi", "New Committee Member"),
        R("BackOffice.CongressBoardMembers.Create.Description", "Kurul, akademik ünvan ve üye bilgileri bağlamsal olarak seçilir; görev/açıklama alanı çeviri tablarında tutulur.", "Board, academic title and member information are selected contextually; role/description is managed in translation tabs."),
        R("BackOffice.CongressBoardMembers.Update.Title", "Kurul Üyesi Düzenle", "Edit Committee Member"),
        R("BackOffice.CongressBoardMembers.Update.Description", "Seçili kurul üyesinin kurul türü, ünvanı, kurum bilgisi ve açıklamaları güncellenir.", "Update the selected committee member's board type, title, institution and descriptions."),
        R("BackOffice.CongressBoardMembers.ExcelUpload.Title", "Excel ile Kurul Üyesi Yükle", "Upload Committee Members with Excel"),
        R("BackOffice.CongressBoardMembers.ExcelUpload.Description", "Kurul üyelerini şablona uygun Excel dosyasıyla toplu olarak yükleyin.", "Bulk upload committee members using the Excel template."),
        R("BackOffice.CongressBoardMembers.ExcelUpload.Help", "Yükleme yapmadan önce şablonu indirip aynı kolon yapısıyla doldurun. Kurul türü, akademik ünvan, ad soyad, kurum ve durum alanlarını eksiksiz girin.", "Before uploading, download the template and fill it with the same column structure. Complete board type, academic title, full name, institution and status fields."),
        R("BackOffice.CongressBoardMembers.ExcelUpload.TemplateTitle", "Şablon", "Template"),
        R("BackOffice.CongressBoardMembers.ExcelUpload.TemplateDescription", "Excel dosyasını bu şablona göre hazırlayın.", "Prepare the Excel file based on this template."),
        R("BackOffice.CongressBoardMembers.ExcelUpload.FileTitle", "Dosya Yükleme", "File Upload"),
        R("BackOffice.CongressBoardMembers.ExcelUpload.FileHelp", "Sadece .xlsx formatı önerilir.", "Only .xlsx format is recommended."),
        R("BackOffice.CongressBoardMembers.Filters.Title", "Filtreler", "Filters"),
        R("BackOffice.CongressBoardMembers.Summary.Total", "Toplam Üye", "Total Members"),
        R("BackOffice.CongressBoardMembers.Summary.Organizing", "Düzenleme Kurulu", "Organizing Committee"),
        R("BackOffice.CongressBoardMembers.Summary.Scientific", "Bilim Kurulu", "Scientific Committee"),
        R("BackOffice.CongressBoardMembers.Summary.Secretariat", "Sekreterya", "Secretariat"),
        R("BackOffice.CongressBoardMembers.Fields.BoardType", "Kurul Türü", "Board Type"),
        R("BackOffice.CongressBoardMembers.Fields.AcademicTitle", "Akademik Ünvan", "Academic Title"),
        R("BackOffice.CongressBoardMembers.Fields.NoAcademicTitle", "Ünvansız", "No Title"),
        R("BackOffice.CongressBoardMembers.Fields.FullName", "Ad Soyad", "Full Name"),
        R("BackOffice.CongressBoardMembers.Fields.Institution", "Kurum", "Institution"),
        R("BackOffice.CongressBoardMembers.Fields.Order", "Sıra No", "Order"),
        R("BackOffice.CongressBoardMembers.Fields.Status", "Durum", "Status"),
        R("BackOffice.CongressBoardMembers.Fields.SignatureAuthority", "İmza Yetkilisi", "Signature Authority"),
        R("BackOffice.CongressBoardMembers.Fields.Photo", "Fotoğraf", "Photo"),
        R("BackOffice.CongressBoardMembers.Fields.Description", "Görev / Açıklama", "Role / Description"),
        R("BackOffice.CongressBoardMembers.Placeholders.Description", "İsteğe bağlı açıklama...", "Optional description..."),
        R("BackOffice.CongressBoardMembers.Help.Photo", "İsteğe bağlı. JPG, PNG veya WEBP yükleyebilirsiniz.", "Optional. You may upload JPG, PNG or WEBP."),
        R("BackOffice.CongressBoardMembers.Messages.Created", "Kurul üyesi başarıyla oluşturuldu.", "Committee member was created successfully."),
        R("BackOffice.CongressBoardMembers.Messages.Updated", "Kurul üyesi başarıyla güncellendi.", "Committee member was updated successfully."),
        R("BackOffice.CongressBoardMembers.Messages.Deleted", "Kurul üyesi başarıyla silindi.", "Committee member was deleted successfully."),
        R("BackOffice.CongressBoardMembers.Messages.Imported", "Excel dosyası başarıyla yüklendi.", "Excel file was uploaded successfully."),
        R("BackOffice.CongressBoardMembers.Messages.ImportedWithErrors", "Excel dosyası bazı hatalarla işlendi.", "Excel file was processed with some errors."),
        R("BackOffice.CongressBoardMembers.Business.EntityNotFound", "Kurul üyesi bulunamadı.", "Committee member was not found."),
        R("BackOffice.CongressBoardMembers.Business.DefaultTranslationRequired", "Varsayılan dilde açıklama bilgisi geçersiz.", "Default language description is invalid."),
        R("BackOffice.CongressBoardMembers.Validation.CongressRequired", "Kongre bilgisi zorunludur.", "Congress is required."),
        R("BackOffice.CongressBoardMembers.Validation.BoardRequired", "Kurul türü zorunludur.", "Board type is required."),
        R("BackOffice.CongressBoardMembers.Validation.FullNameRequired", "Ad soyad zorunludur.", "Full name is required."),
        R("BackOffice.CongressBoardMembers.Validation.FullNameMaxLength", "Ad soyad en fazla 250 karakter olabilir.", "Full name can be at most 250 characters."),
        R("BackOffice.CongressBoardMembers.Validation.ReorderRequired", "Sıralama için en az bir kurul üyesi seçilmelidir.", "At least one committee member must be selected for reordering."),
        R("BackOffice.CongressBoardMembers.Validation.InvalidReorderList", "Kurul üyesi sıralama listesi geçersizdir.", "The committee member reorder list is invalid."),
        R("BackOffice.CongressBoardMembers.Validation.ReorderSingleBoardRequired", "Kurul üyesi sıralaması yalnızca aynı kurul türündeki üyeler arasında yapılabilir.", "Committee member ordering can only be changed among members of the same board type."),
        R("BackOffice.CongressBoardMembers.Validation.AcademicTitleMaxLength", "Akademik ünvan en fazla 100 karakter olabilir.", "Academic title can be at most 100 characters."),
        R("BackOffice.CongressBoardMembers.Validation.InstitutionMaxLength", "Kurum en fazla 500 karakter olabilir.", "Institution can be at most 500 characters."),
        R("BackOffice.CongressBoardMembers.Validation.OrderMustBePositive", "Sıra numarası negatif olamaz.", "Order cannot be negative."),
        R("BackOffice.CongressBoardMembers.Validation.ImageExtensionInvalid", "Sadece JPG, PNG veya WEBP görsel yükleyebilirsiniz.", "Only JPG, PNG or WEBP images are allowed."),
        R("BackOffice.CongressBoardMembers.Validation.ImageSizeInvalid", "Fotoğraf en fazla 5 MB olabilir.", "Photo can be at most 5 MB."),
        R("BackOffice.CongressBoardMembers.Validation.ExcelFileRequired", "Excel dosyası seçilmelidir.", "Excel file is required."),
        R("BackOffice.CongressBoardMembers.Validation.ExcelFileInvalid", "Sadece .xlsx dosyası yükleyebilirsiniz.", "Only .xlsx files are allowed."),
        R("BackOffice.CongressBoardMembers.Validation.ImportFileEmpty", "Excel dosyasında aktarılacak kayıt bulunamadı.", "No importable records were found in the Excel file."),

        R("BackOffice.CongressBoardMembers.Signature.Title", "Kabul Mektubu İmzası", "Acceptance Letter Signature"),
        R("BackOffice.CongressBoardMembers.Signature.Description", "Bu kurul üyesinin kabul mektuplarında imza yetkilisi olup olmayacağını yönetin.", "Manage whether this board member signs acceptance letters."),
        R("BackOffice.CongressBoardMembers.Signature.InfoTitle", "Belgeyi imzalayacak kişi", "Document signer"),
        R("BackOffice.CongressBoardMembers.Signature.InfoDescription", "Bir kongrede kabul mektubunu imzalayacak aktif kişi buradan seçilir. Yeni bir kişi imza yetkilisi yapılırsa diğer kişiler otomatik olarak pasiflenir.", "Select the active person who signs acceptance letters for this congress. When a new signer is selected, other signers are automatically disabled."),
        R("BackOffice.CongressBoardMembers.Signature.IsSigner", "Bu kişi kabul mektuplarını imzalasın", "This person signs acceptance letters"),
        R("BackOffice.CongressBoardMembers.Signature.IsSignerHelp", "Kabul kararı verildiğinde oluşturulan PDF belgelerde bu kişinin adı, unvanı ve imzası kullanılır.", "When a submission is accepted, this person’s name, title, and signature are used in generated PDF letters."),
        R("BackOffice.CongressBoardMembers.Signature.File", "İmza görseli", "Signature image"),
        R("BackOffice.CongressBoardMembers.Signature.Current", "Mevcut imza", "Current signature"),
        R("BackOffice.CongressBoardMembers.Signature.Help", "Şeffaf arka planlı PNG önerilir. JPG de yüklenebilir. En fazla 2 MB.", "Transparent PNG is recommended. JPG is also allowed. Maximum 2 MB."),
        R("BackOffice.CongressBoardMembers.Signature.Save", "İmza Ayarlarını Kaydet", "Save Signature Settings"),
        R("BackOffice.CongressBoardMembers.Signature.Authorized", "Yetkili", "Authorized"),
        R("BackOffice.CongressBoardMembers.Signature.Missing", "İmza görseli eksik", "Signature image is missing"),
        R("BackOffice.CongressBoardMembers.Messages.SignatureUpdated", "Kabul mektubu imza ayarları güncellendi.", "Acceptance letter signature settings have been updated."),
        R("BackOffice.CongressBoardMembers.Validation.SignatureExtensionInvalid", "Sadece PNG veya JPG imza görseli yükleyebilirsiniz.", "Only PNG or JPG signature images can be uploaded."),
        R("BackOffice.CongressBoardMembers.Validation.SignatureSizeInvalid", "İmza görseli en fazla 2 MB olabilir.", "The signature image can be at most 2 MB."),
        R("BackOffice.CongressBoardMembers.Validation.SignatureRequiredForSigner", "İmza yetkilisi seçebilmek için önce imza görseli yüklemelisiniz.", "You must upload a signature image before selecting the signer.")
    };

    private static ResourceSeedDefinition R(string key, string tr, string en)
        => new("BackOffice", key, tr, en);
}
