using System.Collections.Generic;

namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class CongressResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("BackOffice.Sidebar", "BackOffice.Sidebar.Congresses", "Kongreler", "Congresses"),

        new("Common", "Common.Default", "Varsayılan", "Default"),
        new("Common", "Common.Saving", "Kaydediliyor...", "Saving..."),

        new("BackOffice", "BackOffice.Congresses.PageTitle", "Kongreler", "Congresses"),
        new("BackOffice", "BackOffice.Congresses.PageDescription", "Kongre kayıtlarını listeleyin, yeni kongre oluşturun ve yönetim ekranına geçin.", "List congress records, create a new congress and continue to the management screen."),
        new("BackOffice", "BackOffice.Congresses.InfoTitle", "Kongre yönetimi", "Congress management"),
        new("BackOffice", "BackOffice.Congresses.InfoDescription", "Organizasyonlara bağlı kongreleri oluşturabilir, listeleyebilir ve yönetim ekranından slider kayıtlarını düzenleyebilirsiniz.", "Create and list congresses linked to organizations and manage slider records from the management screen."),
        new("BackOffice", "BackOffice.Congresses.ListTitle", "Kongre Listesi", "Congress List"),
        new("BackOffice", "BackOffice.Congresses.ListDescription", "Yeni oluşturulan kongreler bu tabloya düşer.", "Newly created congresses appear in this table."),
        new("BackOffice", "BackOffice.Congresses.CreateButton", "Yeni Kongre Ekle", "Add New Congress"),
        new("BackOffice", "BackOffice.Congresses.Filters.AllOrganizations", "Tüm organizasyonlar", "All organizations"),
        new("BackOffice", "BackOffice.Congresses.Filters.Title", "Filtreler", "Filters"),
        new("BackOffice", "BackOffice.Congresses.Filters.Clear", "Filtreleri Temizle", "Clear Filters"),

        new("BackOffice", "BackOffice.Congresses.Create.PageTitle", "Yeni Kongre Ekle", "Add New Congress"),
        new("BackOffice", "BackOffice.Congresses.Create.PageDescription", "Kongrenin temel kaydını oluşturun. Kayıt tamamlandıktan sonra kongre listesine dönebilirsiniz.", "Create the core congress record. You can return to the congress list after saving."),
        new("BackOffice", "BackOffice.Congresses.Create.InfoTitle", "Kongre oluşturma", "Create congress"),
        new("BackOffice", "BackOffice.Congresses.Create.InfoDescription", "Bu ekranda kongrenin ana kaydı, iletişim bilgileri ve Türkçe/İngilizce çevirileri oluşturulur.", "This screen creates the core congress record, contact information and translations."),
        new("BackOffice", "BackOffice.Congresses.Create.BasicInfo", "Temel Bilgiler", "Basic Information"),
        new("BackOffice", "BackOffice.Congresses.Create.ContactLocationTitle", "İletişim ve Lokasyon", "Contact and Location"),
        new("BackOffice", "BackOffice.Congresses.Create.ContactLocationDescription", "Public kongre sayfasındaki iletişim ve mekan bilgileri bu alandan yönetilir.", "Contact and venue information displayed on the public congress page is managed here."),
        new("BackOffice", "BackOffice.Congresses.Create.Translations", "Çeviriler", "Translations"),
        new("BackOffice", "BackOffice.Congresses.Create.TranslationsDescription", "Varsayılan dilde başlık ve karşılama yazısı zorunludur. Diğer diller opsiyoneldir.", "Title and welcome content are required in the default language. Other languages are optional."),
        new("BackOffice", "BackOffice.Congresses.Create.CodeAutoPlaceholder", "Sistem otomatik üretecek", "Generated automatically"),
        new("BackOffice", "BackOffice.Congresses.Create.CodeAutoHelp", "Kod kullanıcıdan alınmaz; organizasyon kodu, yıl ve sıra numarasına göre oluşturulur.", "Code is not entered manually; it is generated from organization code, year and sequence."),
        new("BackOffice", "BackOffice.Congresses.Create.BrandSourceTitle", "Marka Bilgisi", "Brand Source"),
        new("BackOffice", "BackOffice.Congresses.Create.BrandSourceDescription", "Kongre oluşturulduğunda açık/koyu tema logoları organizasyondan kopyalanır. Create ekranında logo alınmaz; gerekirse edit ekranında kongreye özel logo değiştirilebilir.", "When a congress is created, light/dark theme logos are copied from the organization. Logos are not uploaded on the create screen; they can be customized later from the edit screen."),
        new("BackOffice", "BackOffice.Congresses.Create.NextStepsTitle", "Sonraki Adımlar", "Next Steps"),
        new("BackOffice", "BackOffice.Congresses.Create.Step1Title", "Kongre ana kaydını oluştur", "Create the congress record"),
        new("BackOffice", "BackOffice.Congresses.Create.Step1Description", "Organizasyon, tarih, lokasyon ve iletişim alanlarını tamamlayın.", "Complete organization, date, location and contact fields."),
        new("BackOffice", "BackOffice.Congresses.Create.Step2Title", "Çevirileri doğrula", "Verify translations"),
        new("BackOffice", "BackOffice.Congresses.Create.Step2Description", "Varsayılan dilde başlık ve karşılama yazısı zorunludur.", "Title and welcome content are required in the default language."),
        new("BackOffice", "BackOffice.Congresses.Create.Step3Title", "Liste üzerinden kontrol et", "Check the list"),
        new("BackOffice", "BackOffice.Congresses.Create.Step3Description", "Kaydı tamamladıktan sonra kongre listesinde görünür.", "After saving, the record appears in the congress list."),

        new("BackOffice", "BackOffice.Congresses.Fields.Organization", "Organizasyon", "Organization"),
        new("BackOffice", "BackOffice.Congresses.Fields.Code", "Kod", "Code"),
        new("BackOffice", "BackOffice.Congresses.Fields.EditionNumber", "Kongre No", "Edition Number"),
        new("BackOffice", "BackOffice.Congresses.Fields.Title", "Kongre Başlığı", "Congress Title"),
        new("BackOffice.Congresses", "BackOffice.Congresses.Fields.Subtitle", "Alt Başlık", "Subtitle"),
        new("BackOffice", "BackOffice.Congresses.Fields.ShortDescription", "Kısa Açıklama", "Short Description"),
        new("BackOffice", "BackOffice.Congresses.Fields.WelcomeTitle", "Karşılama Başlığı", "Welcome Title"),
        new("BackOffice", "BackOffice.Congresses.Fields.WelcomeContent", "Karşılama Yazısı", "Welcome Content"),
        new("BackOffice", "BackOffice.Congresses.Fields.SeoTitle", "SEO Başlığı", "SEO Title"),
        new("BackOffice", "BackOffice.Congresses.Fields.SeoDescription", "SEO Açıklaması", "SEO Description"),
        new("BackOffice", "BackOffice.Congresses.Fields.StartDate", "Başlangıç Tarihi", "Start Date"),
        new("BackOffice", "BackOffice.Congresses.Fields.EndDate", "Bitiş Tarihi", "End Date"),
        new("BackOffice", "BackOffice.Congresses.Fields.DateRange", "Tarih", "Date"),
        new("BackOffice", "BackOffice.Congresses.Fields.Location", "Lokasyon", "Location"),
        new("BackOffice", "BackOffice.Congresses.Fields.Language", "Dil", "Language"),
        new("BackOffice", "BackOffice.Congresses.Fields.Status", "Durum", "Status"),
        new("BackOffice", "BackOffice.Congresses.Fields.ContactEmail", "E-posta", "Email"),
        new("BackOffice", "BackOffice.Congresses.Fields.ContactPhone", "Telefon", "Phone"),
        new("BackOffice", "BackOffice.Congresses.Fields.ContactName", "İletişim Kişisi", "Contact Person"),
        new("BackOffice", "BackOffice.Congresses.Fields.ContactTitle", "İletişim Kişisi Görevi", "Contact Person Title"),
        new("BackOffice", "BackOffice.Congresses.Fields.ContactAddress", "İletişim Adresi", "Contact Address"),
        new("BackOffice", "BackOffice.Congresses.Fields.VenueName", "Mekan Adı", "Venue Name"),
        new("BackOffice", "BackOffice.Congresses.Fields.LogoLight", "Açık Tema Logosu", "Light Theme Logo"),
        new("BackOffice", "BackOffice.Congresses.Fields.LogoDark", "Koyu Tema Logosu", "Dark Theme Logo"),
        new("BackOffice", "BackOffice.Congresses.Fields.Country", "Ülke", "Country"),
        new("BackOffice", "BackOffice.Congresses.Fields.State", "İl / Bölge", "State / Region"),
        new("BackOffice", "BackOffice.Congresses.Fields.City", "Şehir", "City"),

        new("BackOffice", "BackOffice.Congresses.Edit.PageTitle", "Kongre Düzenleme", "Edit Congress"),
        new("BackOffice", "BackOffice.Congresses.Edit.PageDescription", "Kongrenin temel bilgilerini, iletişim/lokasyon alanlarını ve çeviri içeriklerini güncelleyin.", "Update the congress core information, contact/location fields and translation contents."),
        new("BackOffice", "BackOffice.Congresses.Edit.InfoTitle", "Kongre güncelleme", "Update congress"),
        new("BackOffice", "BackOffice.Congresses.Edit.InfoDescription", "Bu ekranda kongrenin ana kaydı, iletişim bilgileri ve çok dilli içerikleri AJAX üzerinden güncellenir.", "This screen updates the core congress record, contact information and multilingual contents via AJAX."),
        new("BackOffice", "BackOffice.Congresses.Edit.CodeReadonlyHelp", "Teknik kod sistem tarafından üretilir ve bu ekranda değiştirilemez.", "The technical code is generated by the system and cannot be changed on this screen."),

        new("BackOffice.Congresses", "BackOffice.Congresses.Buttons.BackToList", "Listeye Dön", "Back to List"),
        new("BackOffice", "BackOffice.Congresses.Buttons.SaveAsDraft", "Taslak Olarak Bırak", "Save as Draft"),
        new("BackOffice", "BackOffice.Congresses.Buttons.Save", "Kongreyi Kaydet", "Save Congress"),
        new("BackOffice", "BackOffice.Congresses.Buttons.UpdateAsDraft", "Taslak Olarak Güncelle", "Update as Draft"),
        new("BackOffice", "BackOffice.Congresses.Buttons.Update", "Kongreyi Güncelle", "Update Congress"),
        new("BackOffice.Congresses", "BackOffice.Congresses.Buttons.Manage", "Yönet", "Manage"),
        new("BackOffice", "BackOffice.Congresses.Buttons.ManageComingSoon", "Yönetim ekranı bir sonraki adımda eklenecek", "Management screen will be added in the next step"),

        new("BackOffice", "BackOffice.Congresses.Help.WelcomeContent", "Public kongre ana sayfasında 'Değerli Araştırmacılar' alanında gösterilir.", "Shown in the welcome section of the public congress homepage."),
        new("BackOffice", "BackOffice.Congresses.Help.LogoLight", "Açık zeminlerde kullanılacak kongre logosu. Boş bırakılırsa mevcut logo korunur.", "Congress logo used on light backgrounds. Leave empty to keep the existing logo."),
        new("BackOffice", "BackOffice.Congresses.Help.LogoDark", "Koyu zeminlerde kullanılacak kongre logosu. Boş bırakılırsa mevcut logo korunur.", "Congress logo used on dark backgrounds. Leave empty to keep the existing logo."),
        new("BackOffice", "BackOffice.Congresses.Placeholders.Title", "Örn: 26. Uluslararası Bilimsel Araştırmalar Kongresi", "Example: 26th International Scientific Research Congress"),

        new("BackOffice.Congresses", "BackOffice.Congresses.Status.Draft", "Taslak", "Draft"),
        new("BackOffice.Congresses", "BackOffice.Congresses.Status.Published", "Yayında", "Published"),
        new("BackOffice.Congresses", "BackOffice.Congresses.Status.Archived", "Arşivde", "Archived"),
        new("BackOffice.Congresses", "BackOffice.Congresses.Status.Cancelled", "İptal", "Cancelled"),
        new("BackOffice.Congresses", "BackOffice.Congresses.Table.FallbackLanguage", "Fallback", "Fallback"),
        new("BackOffice.Congresses", "BackOffice.Congresses.Table.CurrentLanguage", "Geçerli", "Current"),

        new("BackOffice", "BackOffice.Congresses.Messages.Created", "Kongre başarıyla oluşturuldu.", "Congress created successfully."),
        new("BackOffice", "BackOffice.Congresses.Messages.Updated", "Kongre başarıyla güncellendi.", "Congress updated successfully."),
        new("BackOffice", "BackOffice.Congresses.Validation.OrganizationRequired", "Organizasyon seçimi zorunludur.", "Organization is required."),
        new("BackOffice", "BackOffice.Congresses.Validation.StartDateRequired", "Başlangıç tarihi zorunludur.", "Start date is required."),
        new("BackOffice", "BackOffice.Congresses.Validation.EndDateRequired", "Bitiş tarihi zorunludur.", "End date is required."),
        new("BackOffice", "BackOffice.Congresses.Validation.DateRangeInvalid", "Bitiş tarihi başlangıç tarihinden önce olamaz.", "End date cannot be earlier than start date."),
        new("BackOffice", "BackOffice.Congresses.Validation.ContactEmailRequired", "Kongre iletişim e-posta adresi zorunludur.", "Congress contact email is required."),
        new("BackOffice", "BackOffice.Congresses.Validation.TitleRequired", "Varsayılan dilde kongre başlığı zorunludur.", "Congress title is required in the default language."),
        new("BackOffice", "BackOffice.Congresses.Validation.WelcomeContentRequired", "Varsayılan dilde karşılama yazısı zorunludur.", "Welcome content is required in the default language."),
        new("BackOffice", "BackOffice.Congresses.Validation.TranslationTitleRequiredWhenAnyFieldFilled", "Bu dil için herhangi bir içerik girildiyse kongre başlığı da zorunludur.", "If any content is entered for this language, congress title is also required."),
        new("BackOffice", "BackOffice.Congresses.Validation.InvalidLogo", "Logo PNG, JPG, WEBP veya SVG olmalıdır.", "Logo must be PNG, JPG, WEBP, or SVG.")
    };
}
