namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class OrganizationResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        // Organizations - page
        new("BackOffice.Organizations", "BackOffice.Organizations.PageTitle", "Organizasyonlar", "Organizations"),
        new("BackOffice.Organizations", "BackOffice.Organizations.PageDescription", "Aktif organizasyon kayıtlarını ve API anahtar durumlarını görüntüleyin.", "View active organization records and API key status."),
        new("BackOffice.Organizations", "BackOffice.Organizations.ManagementTitle", "Organizasyon Yönetimi", "Organization Management"),
        new("BackOffice.Organizations", "BackOffice.Organizations.ManagementDescription", "Organizasyon temel kayıt, iletişim, logo, marka ve API anahtarı yönetimini yapın.", "Manage organization base records, contact information, logo, branding, and API keys."),
        new("BackOffice.Organizations", "BackOffice.Organizations.ListTitle", "Organizasyon Listesi", "Organization List"),
        new("BackOffice.Organizations", "BackOffice.Organizations.ListDescription", "Aktif ve pasif organizasyon kayıtlarını görüntüleyin ve düzenleyin.", "View and edit active and passive organization records."),
        new("BackOffice.Organizations", "BackOffice.Organizations.CreateButton", "Yeni Organizasyon Ekle", "New Organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.CreatePageTitle", "Organizasyon Oluştur", "Create Organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.CreateTitle", "Yeni Organizasyon", "New Organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.CreateDescription", "Temel kayıt, iletişim, logo ve marka bilgilerini girin.", "Enter base record, contact, logo, and brand information."),
        new("BackOffice.Organizations", "BackOffice.Organizations.EditPageTitle", "Organizasyon Düzenle", "Edit Organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.EditTitle", "Organizasyonu Düzenle", "Edit Organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.EditDescription", "Organizasyon temel kayıt, iletişim ve marka bilgilerini güncelleyin.", "Update organization base record, contact, and brand information."),

        // Organizations - sections
        new("BackOffice.Organizations", "BackOffice.Organizations.Sections.BasicInformation", "Temel Bilgiler", "Basic Information"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Sections.ContactInformation", "İletişim Bilgileri", "Contact Information"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Sections.Branding", "Logo ve Marka", "Logo and Branding"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Sections.Logo", "Logo", "Logo"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Sections.Actions", "İşlemler", "Actions"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Sections.OrganizationCreate", "Organizasyon oluşturma", "Create organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Sections.OrganizationCreateInfo", "API anahtarları kayıt sonrası ilgili organizasyon yönetim ekranından oluşturulur.", "API keys are created from the related organization management screen after the organization is saved."),

        // Organizations - fields
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.Organization", "Organizasyon", "Organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.Name", "Organizasyon Adı", "Organization Name"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.Code", "Kod", "Code"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.ShortName", "Kısa Ad", "Short Name"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.WebsiteUrl", "Web Sitesi", "Website"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.Description", "Kısa Açıklama", "Short Description"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.ContactName", "Yetkili Kişi", "Contact Person"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.ContactTitle", "Yetkili Görevi", "Contact Title"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.ContactEmail", "E-posta", "Email"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.ContactPhone", "Telefon", "Phone"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.ContactNote", "Adres / Not", "Address / Note"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.Logo", "Organizasyon Logosu", "Organization Logo"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.LogoLight", "Açık Tema Logosu", "Light Theme Logo"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.LogoDark", "Koyu Tema Logosu", "Dark Theme Logo"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.BrandColor", "Marka Rengi", "Brand Color"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.IsActive", "Durum", "Status"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.ApiKeyStatus", "API Anahtarı", "API Key"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.LastUpdatedAt", "Son Güncelleme", "Last Update"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Fields.Actions", "İşlemler", "Actions"),

        // Organizations - placeholders and helpers
        new("BackOffice.Organizations", "BackOffice.Organizations.Placeholders.Name", "Örn: UBAK", "Example: UBAK"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Placeholders.Code", "Örn: ubak", "Example: ubak"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Placeholders.ShortName", "Örn: UTSAK", "Example: UTSAK"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Placeholders.WebsiteUrl", "https://...", "https://..."),
        new("BackOffice.Organizations", "BackOffice.Organizations.Placeholders.Description", "Organizasyon hakkında kısa açıklama giriniz.", "Enter a short description about the organization."),
        new("BackOffice.Organizations", "BackOffice.Organizations.Placeholders.ContactNote", "Adres veya ek not giriniz.", "Enter address or additional note."),
        new("BackOffice.Organizations", "BackOffice.Organizations.Helper.Code", "URL, API ve sistem kayıtlarında kullanılacak kısa kod.", "Short code used in URLs, API, and system records."),
        new("BackOffice.Organizations", "BackOffice.Organizations.Helper.ShortName", "Kongre kodu ve doküman dosya adlarında kullanılacak kurumsal kısa ad. Örn: UTSAK, ISPEC, UBAK.", "Corporate short name used in congress codes and document file names. Example: UTSAK, ISPEC, UBAK."),
        new("BackOffice.Organizations", "BackOffice.Organizations.Helper.Logo", "PNG, JPG, WEBP veya SVG önerilir.", "PNG, JPG, WEBP, or SVG is recommended."),
        new("BackOffice.Organizations", "BackOffice.Organizations.Helper.LogoLight", "Açık zeminlerde kullanılacak logo. PNG, JPG, WEBP veya SVG önerilir.", "Logo used on light backgrounds. PNG, JPG, WEBP, or SVG is recommended."),
        new("BackOffice.Organizations", "BackOffice.Organizations.Helper.LogoDark", "Koyu zeminlerde kullanılacak logo. PNG, JPG, WEBP veya SVG önerilir.", "Logo used on dark backgrounds. PNG, JPG, WEBP, or SVG is recommended."),

        // Organizations - buttons/status/table
        new("BackOffice.Organizations", "BackOffice.Organizations.Buttons.SelectLogo", "Logo Seç", "Select Logo"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Buttons.SelectLogoLight", "Açık Logo Seç", "Select Light Logo"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Buttons.SelectLogoDark", "Koyu Logo Seç", "Select Dark Logo"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Buttons.Save", "Organizasyonu Kaydet", "Save Organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Buttons.Update", "Organizasyonu Güncelle", "Update Organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Buttons.BackToList", "Listeye Dön", "Back to List"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Buttons.ApiKeys", "API Keyleri Yönet", "Manage API Keys"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Status.Active", "Aktif", "Active"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Status.Passive", "Pasif", "Passive"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Status.ActiveOrganization", "Aktif Organizasyon", "Active Organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Status.PassiveOrganization", "Pasif Organizasyon", "Passive Organization"),
        new("BackOffice.Organizations", "BackOffice.Organizations.Table.ActiveApiKeysSuffix", "aktif anahtar", "active keys"),

        // Organizations - validation/messages
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.EntityNotFound", "Organizasyon bulunamadı.", "Organization was not found."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.NameRequired", "Organizasyon adı zorunludur.", "Organization name is required."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.NameMaxLength", "Organizasyon adı en fazla 200 karakter olabilir.", "Organization name can be at most 200 characters."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.CodeRequired", "Organizasyon kodu zorunludur.", "Organization code is required."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.CodeMaxLength", "Organizasyon kodu en fazla 64 karakter olabilir.", "Organization code can be at most 64 characters."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.CodeAlreadyExists", "Bu organizasyon kodu zaten kayıtlı.", "This organization code is already registered."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.InvalidCode", "Organizasyon kodu yalnızca harf, rakam ve tire içermelidir.", "Organization code must contain only letters, numbers, and hyphens."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.ShortNameRequired", "Organizasyon kısa adı zorunludur.", "Organization short name is required."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.ShortNameMaxLength", "Organizasyon kısa adı en fazla 80 karakter olabilir.", "Organization short name can be at most 80 characters."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.InvalidShortName", "Organizasyon kısa adı yalnızca harf, rakam ve tire içermelidir.", "Organization short name must contain only letters, numbers, and hyphens."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.InvalidLogo", "Logo PNG, JPG, WEBP veya SVG olmalıdır.", "Logo must be PNG, JPG, WEBP, or SVG."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.InvalidWebsiteUrl", "Geçerli bir web sitesi adresi giriniz.", "Enter a valid website URL."),
        new("BackOffice.Organizations.Validation", "BackOffice.Organizations.Validation.InvalidContactEmail", "Geçerli bir e-posta adresi giriniz.", "Enter a valid email address."),
        new("BackOffice.Organizations.Messages", "BackOffice.Organizations.Messages.Created", "Organizasyon başarıyla oluşturuldu.", "Organization was created successfully."),
        new("BackOffice.Organizations.Messages", "BackOffice.Organizations.Messages.Updated", "Organizasyon başarıyla güncellendi.", "Organization was updated successfully."),
        new("BackOffice.Organizations.Messages", "BackOffice.Organizations.Messages.Deleted", "Organizasyon başarıyla silindi.", "Organization was deleted successfully."),

        // Organization API Keys - pages
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.PageTitle", "API Key Yönetimi", "API Key Management"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.PageDescription", "{0} organizasyonu için API anahtarlarını yönetin.", "Manage API keys for {0}."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.ListTitle", "API Keyleri", "API Keys"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.ListDescription", "Organizasyona ait API anahtarlarını görüntüleyin.", "View API keys for the organization."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.CreateButton", "Yeni API Key", "New API Key"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.CreatePageTitle", "Yeni API Key", "New API Key"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.CreateDescription", "{0} organizasyonu için yeni API anahtarı oluşturun.", "Create a new API key for {0}."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.BackToOrganizations", "Organizasyonlara Dön", "Back to Organizations"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.BackToList", "Listeye Dön", "Back to List"),

        // Organization API Keys - sections
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Sections.KeyInformation", "Anahtar Bilgileri", "Key Information"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Sections.KeyInformationDescription", "API anahtarını tanımlayan temel bilgileri girin.", "Enter the basic information describing the API key."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Sections.Scopes", "Yetki Kapsamı", "Permission Scope"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Sections.ScopesDescription", "Bu anahtarın erişebileceği işlemleri seçin.", "Select the operations this key can access."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Sections.Security", "Güvenlik Ayarları", "Security Settings"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Sections.SecurityDescription", "İsteğe bağlı IP ve domain kısıtlamaları belirleyin.", "Define optional IP and domain restrictions."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Sections.Warning", "Önemli Uyarı", "Important Warning"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Sections.Actions", "İşlemler", "Actions"),

        // Organization API Keys - fields
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.Name", "Anahtar Adı", "Key Name"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.Environment", "Ortam", "Environment"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.KeyType", "Anahtar Tipi", "Key Type"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.KeyPrefix", "Prefix", "Prefix"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.Description", "Açıklama", "Description"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.ExpiresAt", "Bitiş Tarihi", "Expiration Date"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.Scopes", "Yetkiler", "Scopes"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.AllowedIpAddresses", "İzinli IP Adresleri", "Allowed IP Addresses"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.AllowedDomains", "İzinli Domainler", "Allowed Domains"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.IsActive", "Durum", "Status"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.LastUsedAt", "Son Kullanım", "Last Used"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Fields.Actions", "İşlemler", "Actions"),

        // Organization API Keys - placeholders
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Placeholders.Name", "Örn: Congress Mobile App", "Example: Congress Mobile App"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Placeholders.Description", "Bu anahtarın nerede kullanılacağını kısa yazın.", "Briefly describe where this key will be used."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Placeholders.AllowedIpAddresses", "Her satıra bir IP yazın. Boş bırakırsanız tüm IP adreslerine izin verilir.", "Write one IP per line. Leave empty to allow all IP addresses."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Placeholders.AllowedDomains", "Örn: app.example.com", "Example: app.example.com"),

        // Organization API Keys - values/buttons/warnings
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Environments.Production", "Production", "Production"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Environments.Sandbox", "Sandbox", "Sandbox"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Environments.Development", "Development", "Development"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.KeyTypes.SecretKey", "Secret Key", "Secret Key"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.KeyTypes.PublicKey", "Public Key", "Public Key"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.KeyTypes.IntegrationKey", "Integration Key", "Integration Key"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Buttons.Create", "API Key Oluştur", "Create API Key"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Buttons.Copy", "Kopyala", "Copy"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Buttons.Copied", "Kopyalandı", "Copied"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Warning.OneTimeSecretTitle", "Gizli değer sadece bir kez gösterilir.", "The secret value is shown only once."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Warning.OneTimeSecretMessage", "API key oluşturulduktan sonra gizli anahtar sadece bir kez gösterilir. Daha sonra tekrar görüntülenemez.", "After the API key is created, the secret key is shown only once. It cannot be displayed again later."),

        // Organization API Keys - scopes
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.CongressRead.Title", "Kongre Okuma", "Congress Read"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.CongressRead.Description", "Kongre bilgilerini ve genel ayarlarını okuyabilir.", "Can read congress information and general settings."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.SubmissionRead.Title", "Bildiri Okuma", "Submission Read"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.SubmissionRead.Description", "Bildiri listelerini ve detaylarını okuyabilir.", "Can read submission lists and details."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.SubmissionWrite.Title", "Bildiri Yazma", "Submission Write"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.SubmissionWrite.Description", "Bildiri kayıtlarını oluşturabilir veya güncelleyebilir.", "Can create or update submission records."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.PaymentWrite.Title", "Ödeme İşlemleri", "Payment Operations"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.PaymentWrite.Description", "Ödeme durumlarını okuyabilir veya güncelleyebilir.", "Can read or update payment statuses."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.UserRead.Title", "Kullanıcı Okuma", "User Read"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.UserRead.Description", "Kullanıcı ve profil bilgilerini okuyabilir.", "Can read user and profile information."),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.WebhookSend.Title", "Webhook Gönderimi", "Webhook Send"),
        new("BackOffice.OrganizationApiKeys", "BackOffice.OrganizationApiKeys.Scopes.WebhookSend.Description", "Dış sistemlere webhook tetikleyebilir.", "Can trigger webhooks to external systems."),

        // Organization API Keys - validation/messages
        new("BackOffice.OrganizationApiKeys.Validation", "BackOffice.OrganizationApiKeys.Validation.EntityNotFound", "API key bulunamadı.", "API key was not found."),
        new("BackOffice.OrganizationApiKeys.Validation", "BackOffice.OrganizationApiKeys.Validation.OrganizationNotFound", "Seçilen organizasyon bulunamadı. API key yönetimi için listeden geçerli bir organizasyon seçin.", "The selected organization was not found. Select a valid organization from the list for API key management."),
        new("BackOffice.OrganizationApiKeys.Validation", "BackOffice.OrganizationApiKeys.Validation.OrganizationRequired", "API key işlemi için önce bir organizasyon seçmelisiniz.", "You must select an organization before managing API keys."),
        new("BackOffice.OrganizationApiKeys.Validation", "BackOffice.OrganizationApiKeys.Validation.NameRequired", "Anahtar adı zorunludur.", "Key name is required."),
        new("BackOffice.OrganizationApiKeys.Validation", "BackOffice.OrganizationApiKeys.Validation.NameMaxLength", "Anahtar adı en fazla 200 karakter olabilir.", "Key name can be at most 200 characters."),
        new("BackOffice.OrganizationApiKeys.Validation", "BackOffice.OrganizationApiKeys.Validation.EnvironmentRequired", "Ortam bilgisi zorunludur.", "Environment is required."),
        new("BackOffice.OrganizationApiKeys.Validation", "BackOffice.OrganizationApiKeys.Validation.KeyTypeRequired", "Anahtar tipi zorunludur.", "Key type is required."),
        new("BackOffice.OrganizationApiKeys.Validation", "BackOffice.OrganizationApiKeys.Validation.AtLeastOneScopeRequired", "En az bir yetki seçilmelidir.", "At least one scope must be selected."),
        new("BackOffice.OrganizationApiKeys.Validation", "BackOffice.OrganizationApiKeys.Validation.InvalidExpirationDate", "Bitiş tarihi bugünden küçük olamaz.", "Expiration date cannot be earlier than today."),
        new("BackOffice.OrganizationApiKeys.Messages", "BackOffice.OrganizationApiKeys.Messages.Created", "API key başarıyla oluşturuldu.", "API key was created successfully."),
        new("BackOffice.OrganizationApiKeys.Messages", "BackOffice.OrganizationApiKeys.Messages.Updated", "API key başarıyla güncellendi.", "API key was updated successfully."),
        new("BackOffice.OrganizationApiKeys.Messages", "BackOffice.OrganizationApiKeys.Messages.Deleted", "API key başarıyla silindi.", "API key was deleted successfully."),
        new("BackOffice.OrganizationApiKeys.Messages", "BackOffice.OrganizationApiKeys.Messages.Revoked", "API key pasifleştirildi.", "API key was revoked."),
        new("BackOffice.OrganizationApiKeys.Messages", "BackOffice.OrganizationApiKeys.Messages.InvalidApiKey", "Geçersiz API key bilgisi.", "Invalid API key information.")
    };
}
