namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class PortalResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("Portal", "Portal.Navigation.Home", "Anasayfa", "Home"),
        new("Portal", "Portal.Navigation.Announcements", "Duyurular", "Announcements"),
        new("Portal", "Portal.Navigation.Boards", "Kurullar", "Boards"),
        new("Portal", "Portal.Navigation.GeneralInformation", "Genel Bilgiler", "General Information"),
        new("Portal", "Portal.Navigation.RegistrationConditions", "Kayıt Koşulları", "Registration Conditions"),
        new("Portal", "Portal.Navigation.Documents", "Dokümanlar", "Documents"),
        new("Portal", "Portal.Navigation.AllDocuments", "Tüm Dokümanlar", "All Documents"),
        new("Portal", "Portal.Navigation.Contact", "İletişim", "Contact"),
        new("Portal", "Portal.Language.Selected", "Seçili dil", "Selected language"),
        new("Portal", "Portal.Common.Home", "Anasayfa", "Home"),
        new("Portal", "Portal.Common.Search", "Ara", "Search"),
        new("Portal", "Portal.Common.All", "Tümü", "All"),
        new("Portal", "Portal.Common.Download", "İndir", "Download"),
        new("Portal", "Portal.Common.Details", "Detay", "Details"),
        new("Portal", "Portal.Common.NotPublished", "Henüz yayınlanmadı", "Not published yet"),
        new("Portal", "Portal.Common.Current", "Güncel", "Current"),
        new("Portal", "Portal.Common.Archive", "Arşiv", "Archive"),
        new("Portal", "Portal.Common.Year", "Yıl", "Year"),
        new("Portal", "Portal.Common.Type", "Tür", "Type"),
        new("Portal", "Portal.Common.SelectYear", "Yıl seç", "Select year"),
        new("Portal", "Portal.Common.Clear", "Temizle", "Clear"),
        new("Portal", "Portal.Common.Filter", "Filtrele", "Filter"),
        new("Portal", "Portal.Common.List", "Liste", "List"),
        new("Portal", "Portal.Common.Showing", "Gösterilen", "Showing"),
        new("Portal", "Portal.Home.CongressInfo", "Kongre Bilgisi", "Congress Information"),
        new("Portal", "Portal.Home.MemberLoginSubmitAbstract", "Üye Girişi / Özet Gönder", "Member Login / Submit Abstract"),
        new("Portal", "Portal.Home.DateInfo", "Tarih Bilgisi", "Date Information"),
        new("Portal", "Portal.Home.CongressCalendar", "Kongre Takvimi", "Congress Calendar"),
        new("Portal", "Portal.Home.NoImportantDateTitle", "Yakında", "Coming Soon"),
        new("Portal", "Portal.Home.NoImportantDateDescription", "Kongre takvimi yayınlandığında burada gösterilecektir.", "The congress calendar will be displayed here when published."),
        new("Portal", "Portal.Home.LatestAnnouncements", "Son Duyurular", "Latest Announcements"),
        new("Portal", "Portal.Home.Announcements", "Duyurular", "Announcements"),
        new("Portal", "Portal.Home.CurrentAnnouncements", "Güncel Duyurular", "Current Announcements"),
        new("Portal", "Portal.Home.NoAnnouncementTitle", "Henüz duyuru bulunmuyor", "No announcements yet"),
        new("Portal", "Portal.Home.NoAnnouncementDescription", "Güncel duyurular yayınlandığında bu alanda listelenecektir.", "Current announcements will be listed here when published."),
        new("Portal", "Portal.Home.CongressInformation", "Kongre Bilgilendirme", "Congress Information"),
        new("Portal", "Portal.Home.WelcomeFallbackTitle", "Değerli Araştırmacılar", "Dear Researchers"),
        new("Portal", "Portal.Home.WelcomeFallbackDescription", "Kongre bilgilendirme metni yayınlandığında burada gösterilecektir.", "The congress information text will be shown here when published."),
        new("Portal", "Portal.Boards.PageTitle", "Kurullar", "Boards"),
        new("Portal", "Portal.Boards.Breadcrumb", "Kurullar", "Boards"),
        new("Portal", "Portal.Boards.EmptyTitle", "Kurul bilgisi bulunmuyor", "No board information found"),
        new("Portal", "Portal.Boards.EmptyDescription", "Kurul üyeleri yayınlandığında burada listelenecektir.", "Board members will be listed here when published."),
        new("Portal", "Portal.Sections.PageTitle", "Genel Bilgiler", "General Information"),
        new("Portal", "Portal.Sections.Breadcrumb", "Genel Bilgiler", "General Information"),
        new("Portal", "Portal.Sections.Topics", "Kongre Konuları", "Congress Topics"),
        new("Portal", "Portal.Sections.OtherTopics", "Diğer Konular", "Other Topics"),
        new("Portal", "Portal.Sections.SubmissionTypes", "Bildiri Türleri", "Submission Types"),
        new("Portal", "Portal.Sections.EmptyTitle", "İçerik bulunmuyor", "No content found"),
        new("Portal", "Portal.Sections.EmptyDescription", "Genel bilgiler yayınlandığında burada listelenecektir.", "General information will be listed here when published."),
        new("Portal", "Portal.Sections.TopicsEmpty", "Kongre konusu bulunmuyor.", "No congress topics found."),
        new("Portal", "Portal.Sections.SubmissionTypesEmpty", "Bildiri türü bulunmuyor.", "No submission types found."),
        new("Portal", "Portal.PaymentPlans.PageTitle", "Kayıt Koşulları", "Registration Conditions"),
        new("Portal", "Portal.PaymentPlans.Breadcrumb", "Kayıt Koşulları", "Registration Conditions"),
        new("Portal", "Portal.PaymentPlans.HeaderBadge", "Kongre Kayıt Ücretleri", "Congress Registration Fees"),
        new("Portal", "Portal.PaymentPlans.HeaderTitle", "Katılım türünüze uygun kayıt koşullarını inceleyin", "Review registration conditions suitable for your participation type"),
        new("Portal", "Portal.PaymentPlans.HeaderDescription", "Aşağıdaki tutarlar kongre yönetimi tarafından yayınlanan güncel kayıt koşullarından alınır.", "The amounts below are taken from the current registration conditions published by the congress management."),
        new("Portal", "Portal.PaymentPlans.Featured", "Öne Çıkan", "Featured"),
        new("Portal", "Portal.PaymentPlans.ParticipationFee", "Katılım bedeli", "Participation fee"),
        new("Portal", "Portal.PaymentPlans.DetailsButton", "Plan Detayları", "Plan Details"),
        new("Portal", "Portal.PaymentPlans.ModalTitle", "Plan Detayları", "Plan Details"),
        new("Portal", "Portal.PaymentPlans.Amount", "Katılım Bedeli", "Participation Fee"),
        new("Portal", "Portal.PaymentPlans.Description", "Plan Açıklaması", "Plan Description"),
        new("Portal", "Portal.PaymentPlans.Bank", "Banka", "Bank"),
        new("Portal", "Portal.PaymentPlans.AccountName", "Hesap Adı", "Account Name"),
        new("Portal", "Portal.PaymentPlans.Iban", "IBAN", "IBAN"),
        new("Portal", "Portal.PaymentPlans.DueDate", "Son Ödeme Tarihi", "Due Date"),
        new("Portal", "Portal.PaymentPlans.Validity", "Geçerlilik", "Validity"),
        new("Portal", "Portal.PaymentPlans.ContactEmail", "İletişim E-postası", "Contact Email"),
        new("Portal", "Portal.PaymentPlans.ImportantNote", "Önemli Not", "Important Note"),
        new("Portal", "Portal.PaymentPlans.EmptyTitle", "Kayıt koşulu bulunmuyor", "No registration condition found"),
        new("Portal", "Portal.PaymentPlans.EmptyDescription", "Kayıt koşulları yayınlandığında burada listelenecektir.", "Registration conditions will be listed here when published."),
        new("Portal", "Portal.Documents.PageTitle", "Evraklar", "Documents"),
        new("Portal", "Portal.Documents.Breadcrumb", "Evraklar", "Documents"),
        new("Portal", "Portal.Documents.SearchTitle", "Evrak Ara", "Search Documents"),
        new("Portal", "Portal.Documents.SearchPlaceholder", "Evrak ara...", "Search document..."),
        new("Portal", "Portal.Documents.YearTitle", "Yıllar", "Years"),
        new("Portal", "Portal.Documents.CurrentDocumentCount", "Güncel Evrak", "Current Documents"),
        new("Portal", "Portal.Documents.ArchiveDocumentCount", "Arşiv Evrakı", "Archive Documents"),
        new("Portal", "Portal.Documents.EmptyTitle", "Doküman bulunmuyor", "No documents found"),
        new("Portal", "Portal.Documents.EmptyDescription", "Dokümanlar yayınlandığında burada listelenecektir.", "Documents will be listed here when published."),
        new("Portal", "Portal.Documents.DownloadButton", "İndir", "Download"),
        new("Portal", "Portal.Documents.FileUnavailable", "Dosya bulunamadı", "File unavailable"),
        new("Portal", "Portal.Documents.DefaultType", "Doküman", "Document"),
        new("Portal", "Portal.Documents.DefaultTitle", "Kongre Dokümanı", "Congress Document"),
        new("Portal", "Portal.Documents.FileSize", "Dosya boyutu", "File size"),
        new("Portal", "Portal.Documents.DefaultPublishedDescription", "Bu kongre için yayınlanmış doküman.", "A published document for this congress."),
        new("Portal", "Portal.Documents.DefaultDownloadDescription", "İlgili evrak dosyasını aşağıdan indirebilirsiniz.", "You can download the relevant document below."),
        new("Portal", "Portal.Documents.Information", "Bilgilendirme", "Information"),
        new("Portal", "Portal.Documents.FilterResult", "Filtre Sonucu", "Filter Result"),
        new("Portal", "Portal.Documents.NoPublishedTitle", "Yayınlanmış evrak bulunamadı", "No published documents found"),
        new("Portal", "Portal.Documents.NoPublishedDescription", "Bu kongre için henüz public doküman eklenmemiş.", "No public document has been added for this congress yet."),
        new("Portal", "Portal.Documents.NoFilterResultTitle", "Aramanıza uygun evrak bulunamadı", "No documents matching your search were found"),
        new("Portal", "Portal.Documents.NoFilterResultDescription", "Arama metnini veya yıl filtresini değiştirerek tekrar deneyebilirsiniz.", "You can change the search text or year filter and try again."),
        new("Portal", "Portal.Documents.ClearFilters", "Filtreleri Temizle", "Clear Filters"),
        new("Portal", "Portal.Documents.NoFile", "Dosya Yok", "No File"),
        new("Portal", "Portal.Contact.PageTitle", "İletişim", "Contact"),
        new("Portal", "Portal.Contact.Breadcrumb", "İletişim", "Contact"),
        new("Portal", "Portal.Contact.InfoTitle", "İletişim Bilgileri", "Contact Information"),
        new("Portal", "Portal.Contact.FormTitle", "Bize Ulaşın", "Contact Us"),
        new("Portal", "Portal.Contact.FormDescription", "Soru ve önerileriniz için formu doldurarak bize ulaşabilirsiniz.", "You can contact us by filling out the form for your questions and suggestions."),
        new("Portal", "Portal.Contact.NamePlaceholder", "Ad Soyad", "Full Name"),
        new("Portal", "Portal.Contact.EmailPlaceholder", "E-posta", "Email"),
        new("Portal", "Portal.Contact.SubjectPlaceholder", "Konu", "Subject"),
        new("Portal", "Portal.Contact.MessagePlaceholder", "Mesaj", "Message"),
        new("Portal", "Portal.Contact.Loading", "Gönderiliyor", "Sending"),
        new("Portal", "Portal.Contact.SentMessage", "Mesajınız gönderildi. Teşekkürler!", "Your message has been sent. Thank you!"),
        new("Portal", "Portal.Contact.SendButton", "Mesaj Gönder", "Send Message"),
        new("Portal", "Portal.Footer.QuickAccess", "Hızlı Erişim", "Quick Links"),
        new("Portal", "Portal.Footer.Copyright", "Tüm hakları saklıdır.", "All rights reserved."),
        new("Portal", "Portal.Error.PageTitle", "Sayfa yüklenemedi", "Page could not be loaded"),
        new("Portal", "Portal.Error.UnavailableTitle", "Geçici bir sorun oluştu", "A temporary issue occurred"),
        new("Portal", "Portal.Error.UnavailableDescription", "Public API yanıt vermediği için sayfa şu anda gösterilemiyor. Lütfen kısa süre sonra tekrar deneyin.", "The page cannot be displayed because the Public API did not respond. Please try again shortly."),
        new("Portal", "Portal.Seo.DefaultDescription", "Symplify kongre portalı", "Symplify congress portal"),
        new("Portal", "Portal.Seo.DefaultKeywords", "symplify, kongre, akademik etkinlik, bildiri, konferans", "symplify, congress, academic event, submission, conference"),
        new("Portal", "Portal.PaymentPlans.Free", "Ücretsiz", "Free"),
        new("Portal", "Portal.PaymentPlans.ShortFallback", "Kayıt koşulları, banka bilgileri ve ödeme notları için plan detaylarını inceleyiniz.", "Review plan details for registration conditions, bank information and payment notes."),
        new("Portal", "Portal.PaymentPlans.BankInfoHint", "Banka ve IBAN bilgileri detaylarda yer alır.", "Bank and IBAN information is included in the details."),
        new("Portal", "Portal.PaymentPlans.CheckDescriptionHint", "Kayıt açıklamasını göndermeden önce kontrol ediniz.", "Please check the registration description before submitting."),
        new("Portal", "Portal.PaymentPlans.DueDateShort", "Son ödeme", "Due date"),
        new("Portal", "Portal.PaymentPlans.PaymentInformation", "Ödeme Bilgileri", "Payment Information"),
        new("Portal", "Portal.Contact.DefaultContactName", "Kongre Sekretaryası", "Congress Secretariat"),
        new("Portal", "Portal.Contact.DefaultAddress", "Türkiye", "Türkiye"),
        new("Portal", "Portal.Sections.TopicsEmptyDescription", "Bu kongre için yayınlanmış konu kaydı bulunmuyor.", "There are no published topic records for this congress."),
        new("Portal", "Portal.Sections.SubmissionTypesEmptyDescription", "Bu kongre için yayınlanmış bildiri türü kaydı bulunmuyor.", "There are no published submission type records for this congress."),
        new("Portal", "Portal.Error.ServiceStatus", "Servis Durumu", "Service Status"),
        new("Portal", "Portal.Error.ApiNotResponding", "Public API yanıt vermedi", "Public API did not respond"),
        new("Portal", "Portal.Error.ApiUnavailableDescription", "Portal içeriği şu anda API üzerinden alınamadı. Lütfen API adresi, API key ve host ayarlarını kontrol edin.", "Portal content could not be retrieved from the API. Please check the API address, API key and host settings."),
        new("Portal", "Portal.Site.DefaultName", "Kongre Portalı", "Congress Portal"),
        new("Portal", "Portal.Common.Close", "Kapat", "Close"),
        new("Portal", "Portal.Common.Previous", "Önceki", "Previous"),
        new("Portal", "Portal.Common.Next", "Sonraki", "Next"),
        new("Portal", "Portal.Common.SlideNumber", "Slayt {0}", "Slide {0}"),
        new("Portal", "Portal.Common.TryAgain", "Tekrar Dene", "Try Again"),
        new("Portal", "Portal.Common.BackToHome", "Anasayfaya Dön", "Back to Home"),
        new("Portal", "Portal.Common.ServiceStatus", "Servis Durumu", "Service Status"),
        new("Portal", "Portal.Home.CongressLogoAlt", "{0} kongre logosu", "{0} congress logo"),
        new("Portal", "Portal.Home.AnnouncementImageAlt", "Slider görseli", "Slider image"),
        new("Portal", "Portal.Boards.EmptyMembers", "Bu kurul için üye kaydı bulunmuyor.", "No member record exists for this board."),
        new("Portal", "Portal.Boards.SeoDescription", "Kongre kurulları, bilim kurulu ve kurul üyeleri.", "Congress boards, scientific committee and board members."),
        new("Portal", "Portal.Sections.SeoDescription", "Kongre hakkında genel bilgiler, amaç ve kapsam, kongre konuları ve başvuru içerikleri.", "General information, aims and scope, congress topics and submission content."),
        new("Portal", "Portal.Sections.DetailEmptyDescription", "Bu bilgi alanı için içerik bulunamadı.", "No content was found for this information section."),
        new("Portal", "Portal.PaymentPlans.SeoDescription", "Kongre kayıt koşulları, katılım ücretleri, ödeme bilgileri, bildiri konuları ve bildiri türleri.", "Congress registration conditions, participation fees, payment information, topics and submission types."),
        new("Portal", "Portal.Documents.SeoDescription", "Kongre programı, özet kitabı, tam metin kitabı, belgeler ve yayın dosyaları.", "Congress programme, abstract book, full text book, documents and publication files."),
        new("Portal", "Portal.Contact.SeoDescription", "Kongre sekretaryası, iletişim bilgileri ve adres bilgileri.", "Congress secretariat, contact information and address details."),
        new("Portal", "Portal.Privacy.PageTitle", "Gizlilik Politikası", "Privacy Policy"),
        new("Portal", "Portal.Privacy.Description", "Gizlilik politikası içeriği yayınlandığında bu sayfada gösterilecektir.", "The privacy policy content will be displayed on this page when published."),
        new("Portal", "Portal.Error.RequestId", "İstek Kimliği", "Request ID"),
        new("Portal", "Portal.Error.DevelopmentModeTitle", "Geliştirme Modu", "Development Mode"),
        new("Portal", "Portal.Error.DevelopmentModeDescription", "Geliştirme ortamında hata detayları görüntülenebilir. Production ortamında kullanıcıya teknik hata detayları gösterilmemelidir.", "Error details may be displayed in the development environment. Technical error details should not be shown to users in production."),
        new("Portal", "Portal.Error.UnavailableHeading", "İçeriğe şu anda ulaşılamıyor", "We cannot load the content right now"),
        new("Portal", "Portal.Error.UnavailableSupportText", "Sorun devam ederse kongre sekretaryası ile iletişime geçebilirsiniz.", "If the issue continues, you can contact the congress secretariat."),
        new("Portal", "Portal.Error.GenericDescription", "İşlem sırasında bir sorun oluştu.", "An issue occurred while processing your request."),
    };
}
