namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class ProfileResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("BackOffice.Profile", "BackOffice.Profile.PageTitle", "Profilim", "My Profile"),
        new("BackOffice.Profile", "BackOffice.Profile.Kicker", "Hesap Bilgileri", "Account Information"),
        new("BackOffice.Profile", "BackOffice.Profile.Title", "Profilim", "My Profile"),
        new("BackOffice.Profile", "BackOffice.Profile.Description", "Kişisel bilgilerini ve şifreni güvenli şekilde buradan yönetebilirsin.", "You can securely manage your personal information and password here."),
        new("BackOffice.Profile", "BackOffice.Profile.Action.Home", "Ana Sayfa", "Home"),
        new("BackOffice.Profile", "BackOffice.Profile.Action.MySubmissions", "Bildirilerim", "My Submissions"),
        new("BackOffice.Profile", "BackOffice.Profile.ProfileInformation", "Profil Bilgileri", "Profile Information"),
        new("BackOffice.Profile", "BackOffice.Profile.ProfileInformationDescription", "Ad, soyad, telefon, kurum ve ORCID bilgilerini güncelleyebilirsin.", "You can update your name, phone, institution, and ORCID information."),
        new("BackOffice.Profile", "BackOffice.Profile.EmailReadonly", "E-posta yönetici tarafından değiştirilir", "Email is changed by the administrator"),
        new("BackOffice.Profile", "BackOffice.Profile.Field.Name", "Ad", "First Name"),
        new("BackOffice.Profile", "BackOffice.Profile.Field.Surname", "Soyad", "Last Name"),
        new("BackOffice.Profile", "BackOffice.Profile.Field.Email", "E-posta", "Email"),
        new("BackOffice.Profile", "BackOffice.Profile.Field.Phone", "Telefon", "Phone"),
        new("BackOffice.Profile", "BackOffice.Profile.Field.Institution", "Kurum", "Institution"),
        new("BackOffice.Profile", "BackOffice.Profile.Field.Orcid", "ORCID", "ORCID"),
        new("BackOffice.Profile", "BackOffice.Profile.Action.UpdateProfile", "Profili Güncelle", "Update Profile"),
        new("BackOffice.Profile", "BackOffice.Profile.ChangePassword.Title", "Şifre Değiştir", "Change Password"),
        new("BackOffice.Profile", "BackOffice.Profile.ChangePassword.Description", "Mevcut şifreni doğrulayarak yeni şifre belirleyebilirsin.", "You can set a new password by verifying your current password."),
        new("BackOffice.Profile", "BackOffice.Profile.Field.CurrentPassword", "Mevcut Şifre", "Current Password"),
        new("BackOffice.Profile", "BackOffice.Profile.Field.NewPassword", "Yeni Şifre", "New Password"),
        new("BackOffice.Profile", "BackOffice.Profile.Field.ConfirmPassword", "Yeni Şifre Tekrar", "Confirm New Password"),
        new("BackOffice.Profile", "BackOffice.Profile.Action.UpdatePassword", "Şifreyi Güncelle", "Update Password"),
        new("BackOffice.Profile", "BackOffice.Profile.SecurityNote.Title", "Güvenlik notu", "Security note"),
        new("BackOffice.Profile", "BackOffice.Profile.SecurityNote.Description", "Şifreni düzenli aralıklarla değiştir. Paylaşılan veya tahmin edilebilir şifre kullanma.", "Change your password regularly. Do not use shared or predictable passwords."),
        new("BackOffice.Profile", "BackOffice.Profile.Photo.Alt", "Profil fotoğrafı", "Profile photo"),
        new("BackOffice.Profile", "BackOffice.Profile.Photo.Update", "Fotoğrafı güncelle", "Update photo"),
        new("BackOffice.Profile", "BackOffice.Profile.Photo.Help", "Profil fotoğrafı yoksa ad ve soyad baş harflerin gösterilir.", "If there is no profile photo, your initials are displayed."),
        new("BackOffice.Profile", "BackOffice.Profile.Success.Updated", "Profil bilgileriniz güncellendi.", "Your profile information has been updated."),
        new("BackOffice.Profile", "BackOffice.Profile.Success.PasswordChanged", "Şifreniz güncellendi. Sonraki girişlerinizde yeni şifrenizi kullanabilirsiniz.", "Your password has been updated. You can use your new password on your next login."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.NameRequired", "Ad zorunludur.", "First name is required."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.NameMaxLength", "Ad en fazla 100 karakter olabilir.", "First name can be at most 100 characters."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.SurnameRequired", "Soyad zorunludur.", "Last name is required."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.SurnameMaxLength", "Soyad en fazla 100 karakter olabilir.", "Last name can be at most 100 characters."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.PhoneRequired", "Telefon numarası zorunludur.", "Phone number is required."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.PhoneInvalid", "Telefon numarasını geçerli formatta giriniz.", "Enter a valid phone number."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.InstitutionMaxLength", "Kurum bilgisi en fazla 250 karakter olabilir.", "Institution can be at most 250 characters."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.OrcidMaxLength", "ORCID en fazla 100 karakter olabilir.", "ORCID can be at most 100 characters."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.CurrentPasswordRequired", "Mevcut şifre zorunludur.", "Current password is required."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.NewPasswordRequired", "Yeni şifre zorunludur.", "New password is required."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.NewPasswordMinLength", "Yeni şifre en az 8 karakter olmalıdır.", "New password must be at least 8 characters."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.ConfirmPasswordRequired", "Yeni şifre tekrarı zorunludur.", "New password confirmation is required."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.PasswordCompare", "Yeni şifre ve tekrar alanı aynı olmalıdır.", "New password and confirmation must match."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.ImageInvalid", "Profil fotoğrafı JPG, PNG veya WEBP formatında olmalıdır.", "Profile photo must be in JPG, PNG, or WEBP format."),
        new("BackOffice.Profile", "BackOffice.Profile.Validation.ImageTooLarge", "Profil fotoğrafı en fazla 5 MB olabilir.", "Profile photo can be at most 5 MB."),
        new("BackOffice.Profile", "BackOffice.Profile.Storage.ConfigurationInvalid", "Profil fotoğrafı yükleme servisi yapılandırması eksik.", "Profile photo upload storage configuration is missing."),
        new("BackOffice.Profile", "BackOffice.Profile.Role.User", "Kullanıcı", "User"),
        new("BackOffice.Profile", "BackOffice.Profile.Role.Author", "Yazar", "Author"),
        new("BackOffice.Profile", "BackOffice.Profile.Role.Admin", "Admin", "Admin"),
        new("BackOffice.Profile", "BackOffice.Profile.Role.Editor", "Editör", "Editor"),
        new("BackOffice.Profile", "BackOffice.Profile.UserMenu.AriaLabel", "Kullanıcı menüsü", "User menu"),
        new("BackOffice.Profile", "BackOffice.Profile.UserMenu.Profile", "Profilim", "My Profile"),
        new("BackOffice.Profile", "BackOffice.Profile.UserMenu.ChangePassword", "Şifremi Değiştir", "Change Password"),
        new("BackOffice.Profile", "BackOffice.Profile.UserMenu.Settings", "Ayarlar", "Settings"),
        new("BackOffice.Profile", "BackOffice.Profile.UserMenu.Logout", "Çıkış Yap", "Log Out"),
        new("BackOffice.Profile", "BackOffice.Profile.Role.Reviewer", "Hakem", "Reviewer"),

        // Added by localization audit: statically used keys that previously had no seed definition.
        new("BackOffice.Profile", "BackOffice.Profile.CompletePhone.Description", "Devam etmek için profilinizde geçerli bir telefon numarası bulunmalıdır.", "A valid phone number is required in your profile to continue."),
        new("BackOffice.Profile", "BackOffice.Profile.CompletePhone.Field.Phone", "Telefon Numarası", "Phone Number"),
        new("BackOffice.Profile", "BackOffice.Profile.CompletePhone.HelpText", "Telefon numaranızı ülke koduyla birlikte girin.", "Enter your phone number including the country code."),
        new("BackOffice.Profile", "BackOffice.Profile.CompletePhone.PageTitle", "Telefon Bilgisini Tamamla", "Complete Phone Information"),
        new("BackOffice.Profile", "BackOffice.Profile.CompletePhone.Submit", "Telefon Bilgisini Kaydet", "Save Phone Information"),
        new("BackOffice.Profile", "BackOffice.Profile.CompletePhone.Success", "Telefon bilginiz güncellendi.", "Your phone information has been updated."),
        new("BackOffice.Profile", "BackOffice.Profile.CompletePhone.Title", "Telefon numaranızı ekleyin", "Add your phone number"),
        new("BackOffice.Profile", "BackOffice.Profile.CompletePhone.Validation.PhoneInvalid", "Geçerli bir telefon numarası girin.", "Enter a valid phone number."),
    };
}
