namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class ProgramManagementResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("BackOffice.ProgramManagement", "BackOffice.Sidebar.ProgramManagement", "Etkinlik Programı", "Event Programme"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.PageTitle", "Etkinlik Program Yönetimi", "Event Programme Management"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.PageDescription", "Kongredeki bildirileri seçtiğiniz filtrelere göre gün, salon ve oturumlara otomatik dağıtın; ardından süreleri ve sıralamayı manuel düzenleyin.", "Automatically distribute congress submissions across days, rooms and sessions using the selected filters, then adjust duration and order manually."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Draft", "Taslak Program", "Draft Programme"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Congress", "Kongre", "Congress"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.EligibleSubmissions", "Filtreye Uyan Bildiri", "Matching Submissions"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.TotalActiveSubmissions", "Toplam Aktif Bildiri", "Total Active Submissions"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Rooms", "Salon", "Rooms"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.NoCongress", "Program oluşturulabilecek kongre bulunamadı.", "No congress is available for programme generation."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.AutomaticSetup", "Otomatik Dağıtım Ayarları", "Automatic Scheduling Settings"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.AutomaticSetupDescription", "Ana çalışma saatlerini, sabit blokları ve varsayılan süreleri belirleyin.", "Define working hours, fixed blocks and default durations."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Settings", "Ayarları Aç/Kapat", "Toggle Settings"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SelectRooms", "Programa Dahil Edilecek Salonlar", "Rooms Included in Programme"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.DayStart", "Gün Başlangıç Saati", "Day Start Time"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.DayEnd", "Gün Bitiş Saati", "Day End Time"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SessionMinutes", "Oturum Süresi (dk)", "Session Duration (min)"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.PresentationMinutes", "Bildiri Süresi (dk)", "Presentation Duration (min)"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.QuestionAnswerMinutes", "Soru-Cevap Süresi (dk)", "Q&A Duration (min)"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.BreakMinutes", "Oturum Arası (dk)", "Break Between Sessions (min)"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.IncludeSessionBreak", "Her oturumun ortasına ara ekle", "Add a break to the middle of each session"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SessionBreakMinutes", "Oturum İçi Ara (dk)", "In-session Break (min)"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SessionBreakHelp", "Ara otomatik olarak oturumun ortasına yerleşir; sonradan gün, salon ve oturumlar arasında taşınabilir.", "The break is placed in the middle of the session automatically; it can later be moved between days, rooms and sessions."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.IncludeOpening", "İlk güne açılış bloğu ekle", "Add opening block to first day"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.IncludeLunch", "Her güne öğle arası ekle", "Add lunch break to each day"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.BlockTitle", "Blok Başlığı", "Block Title"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Duration", "Süre (dk)", "Duration (min)"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Room", "Salon", "Room"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.AllRooms", "Tüm Salonlar", "All Rooms"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.StartTime", "Başlangıç Saati", "Start Time"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.FillUnassigned", "Sadece Atanmamışları Doldur", "Fill Unassigned Only"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Generate", "Otomatik Program Oluştur", "Generate Programme"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Regenerate", "Programı Baştan Oluştur", "Regenerate Programme"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Assigned", "Programa Atanan", "Assigned"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Unassigned", "Atanamayan", "Unassigned"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Days", "Program Günü", "Programme Days"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Planner", "Program Planlayıcı", "Programme Planner"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.PlannerHelp", "Bildirileri oturumlar arasında sürükleyin, dakika alanını değiştirin veya manuel kararlarınızı kilitleyin.", "Drag submissions between sessions, change minutes or lock manual decisions."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Reset", "Programı Sıfırla", "Reset Programme"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Day", "Gün", "Day"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Drag", "Taşımak için sürükleyin", "Drag to move"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Lock", "Kilitle/Kilidi Aç", "Lock/Unlock"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.QuestionAnswer", "Soru-Cevap", "Questions & Answers"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.UnassignedList", "Programa Atanamayan Bildiriler", "Unassigned Submissions"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.UnassignedHelp", "Boş kapasite açtıktan sonra “Sadece Atanmamışları Doldur” işlemini çalıştırabilirsiniz.", "After creating free capacity, run “Fill Unassigned Only”."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Number", "Bildiri No", "Submission No"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Title", "Bildiri Başlığı", "Submission Title"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Topic", "Konu", "Topic"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SchedulePreview", "Zaman Planı Önizlemesi", "Schedule Preview"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SchedulePreviewHelp", "Saat ve süre değişikliklerinde oturum sayısı ile kapasite otomatik hesaplanır.", "Session count and capacity are recalculated automatically when times or durations change."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SchedulePreviewInvalid", "Zaman planı ayarları geçersiz.", "Schedule settings are invalid."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.TimelineValid", "Zaman planı tutarlı; sabit bloklar arasında plansız dakika bırakılmayacak.", "The schedule is consistent; no unplanned minutes will remain between fixed blocks."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.FirstDay", "İlk Gün", "First Day"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.OtherDays", "Diğer Günler", "Other Days"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.EstimatedSessions", "Tahmini Oturum", "Estimated Sessions"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.EstimatedCapacity", "Tahmini Bildiri Kapasitesi", "Estimated Submission Capacity"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.TimelineWarning", "Program zaman çizelgesinde kontrol edilmesi gereken noktalar var.", "The programme timeline contains items that require review."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.DraftPdf", "Taslak PDF Önizle", "Preview Draft PDF"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.DraftWord", "Word İndir", "Download Word"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Move", "Başka Oturuma Taşı", "Move to Another Session"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.MoveSubmission", "Bildiriyi Başka Oturuma Taşı", "Move Submission to Another Session"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.TargetSession", "Hedef Oturum", "Target Session"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.MoveHelp", "Farklı gün, salon veya oturum seçebilirsiniz. Süre ve yazar çakışmaları kaydetmeden önce kontrol edilir.", "You can select a different day, room or session. Capacity and author conflicts are checked before saving."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Cancel", "Vazgeç", "Cancel"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.MoveConfirm", "Taşı", "Move"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Order", "Sıra", "Order"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.RemoveBreak", "Arayı Kaldır", "Remove Break"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.RemoveBreakConfirmTitle", "Ara kaldırılsın mı?", "Remove break?"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.RemoveBreakConfirmText", "Bu ara programdan tamamen kaldırılacaktır.", "This break will be removed from the programme completely."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Remove", "Kaldır", "Remove"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SessionOfficials", "Oturum Görevlileri", "Session Officials"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.AssignSessionOfficials", "Başkanları Ata", "Assign Chairs"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SessionChair", "Oturum Başkanı", "Session Chair"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SessionViceChair", "Oturum Başkan Yardımcısı", "Session Vice Chair"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.NotAssigned", "Atanmadı", "Not Assigned"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SaveSessionOfficials", "Görevlileri Kaydet", "Save Officials"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SameOfficialError", "Oturum başkanı ile başkan yardımcısı aynı kişi olamaz.", "The session chair and vice chair cannot be the same person."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.OfficialsInSession", "Oturumdakiler", "Session Participants"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.OfficialsBoardMembers", "Kurul Üyeleri", "Board Members"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.OfficialsAllParticipants", "Tüm Katılımcılar", "All Participants"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SearchOfficials", "Ad, unvan veya kurum ara", "Search by name, title or institution"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.NoOfficialCandidates", "Bu filtreye uygun görevli adayı bulunamadı.", "No official candidate matches this filter."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SubmissionScope", "Programa Alınacak Bildiriler", "Submissions Included in Programme"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SubmissionScopeDescription", "Hazır kapsamı seçin; süreç, ödeme, tür, konu ve arama filtreleriyle sonucu daraltın.", "Select a scope, then narrow the result by workflow, payment, type, topic and search filters."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ScopePreset", "Bildiri Kapsamı", "Submission Scope"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ScopeAllActive", "Tüm Aktif Bildiriler", "All Active Submissions"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ScopeAcceptedOnly", "Sadece Kabul Edilenler", "Accepted Only"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ScopePaidOnly", "Sadece Ödemesi Tamamlananlar", "Payment Completed Only"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ScopeAcceptedAndPaid", "Kabul Edilen ve Ödemesi Tamamlananlar", "Accepted and Payment Completed"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.WorkflowStatuses", "Süreç Durumu", "Workflow Status"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.PaymentStatuses", "Ödeme Durumu", "Payment Status"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SubmissionTypes", "Bildiri Türü", "Submission Type"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.Topics", "Konu", "Topic"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SearchSubmissions", "Bildiri Ara", "Search Submissions"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.SearchSubmissionsPlaceholder", "Bildiri no, başlık, yazar veya kurum ara", "Search by submission no, title, author or institution"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.FilteredSubmissionCount", "Filtreye Uyan", "Matching"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.MultiSelectHelp", "Bir veya birden fazla seçenek belirleyebilirsiniz. Seçim yapılmazsa ilgili filtre uygulanmaz.", "Select one or more options. An empty field does not apply that filter."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.FilterSearchPlaceholder", "Seçenek ara...", "Search options..."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.FilterSelectAll", "Tümünü Seç", "Select All"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.FilterClearSelection", "Seçimi Temizle", "Clear Selection"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.FilterNoOptions", "Sonuç bulunamadı.", "No options found."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ClearAdditionalFilters", "Ek Filtreleri Temizle", "Clear Additional Filters"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.NoFilteredSubmissions", "Seçilen filtrelere uygun bildiri bulunamadı.", "No submissions match the selected filters."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ProgramBookExport", "Program Kitabı Oluştur", "Create Programme Book"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ProgramBookExportHelp", "İsteğe bağlı kapak görselini yükleyin; aynı kapak PDF ve Word çıktısının ilk sayfasında kullanılır.", "Upload an optional cover image; the same cover is used as the first page of both PDF and Word outputs."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ProgramBookCover", "Kapak Görseli", "Cover Image"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ProgramBookCoverHelp", "PNG veya JPG, en fazla 8 MB. Görsel yüklenmezse mevcut otomatik taslak kapak kullanılır.", "PNG or JPG, maximum 8 MB. The existing generated draft cover is used when no image is uploaded."),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.ProgramBookOptions", "Program Kitabı Bölümleri", "Programme Book Sections"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.IncludeTableOfContents", "İçindekileri ekle", "Include contents"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.IncludeScheduleTimes", "Program saatlerini göster", "Show programme times"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.IncludeQuestionAnswer", "Soru-cevap bölümü oluştur", "Create question and answer block"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.IncludeBoards", "Kurullar bölümünü ekle", "Include boards section"),
        new("BackOffice.ProgramManagement", "BackOffice.ProgramManagement.VideoPresentationsExportHelp", "Video sunumu bulunan bildiriler zamanlı programa alınmaz. Onaylı videolar program sonunda kısa bağlantılarıyla ayrı tabloda gösterilir.", "Submissions with a presentation video are excluded from timed sessions. Approved videos are listed with short links in a separate table after the programme.")
    };
}
