namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;
public static class ReviewerEvaluationResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Index.PageTitle", "Hakem Değerlendirmeleri", "Reviewer Evaluations"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Index.Title", "Hakem Değerlendirmelerim", "My Reviewer Evaluations"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Index.Subtitle", "Size atanan bildirileri buradan takip edebilir ve değerlendirebilirsiniz.", "Track and evaluate the submissions assigned to you."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Info.Title", "Gizli değerlendirme", "Confidential evaluation"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Info.Description", "Yazar bilgileri gösterilmez. Lütfen bildiriyi yalnızca içerik, yöntem, özgünlük ve konuya uygunluk açısından değerlendirin.", "Author information is not shown. Please evaluate only the content, method, originality, and topic fit."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Stat.Assigned", "Atanan bildiri", "Assigned submissions"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Stat.Pending", "Bekleyen", "Pending"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Stat.Completed", "Tamamlanan", "Completed"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Stat.DueSoon", "Son tarihi yaklaşan", "Due soon"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Title", "Filtreler", "Filters"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Search.Label", "Arama", "Search"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Search.Placeholder", "Bildiri no, başlık, konu, tür veya kongre ara...", "Search submission no, title, topic, type, or congress..."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Congress", "Kongre", "Congress"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Status", "Durum", "Status"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Topic", "Konu", "Topic"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.SubmissionType", "Bildiri tipi", "Submission type"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Reset", "Filtreleri Temizle", "Clear Filters"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Congress.AllPublished", "Tüm yayındaki kongreler", "All published congresses"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Status.All", "Tüm durumlar", "All statuses"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Topic.All", "Tüm konular", "All topics"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.SubmissionType.All", "Tüm bildiri tipleri", "All submission types"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Status.Pending", "Bekleyen", "Pending"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Status.InProgress", "Devam Ediyor", "In progress"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Status.Completed", "Tamamlandı", "Completed"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Status.DueSoon", "Son tarihi yaklaşan", "Due soon"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Filters.Status.Overdue", "Süresi geçen", "Overdue"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.List.Title", "Değerlendirme Listesi", "Evaluation List"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.List.Subtitle", "Bir bildiriyi açarak puanlama ve öneri formunu doldurabilirsiniz.", "Open a submission to complete scores and your recommendation."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Empty.Title", "Size atanmış değerlendirme yok", "No assigned evaluations"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Empty.Description", "Size bir bildiri atandığında burada görünecektir.", "Assigned submissions will appear here."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Column.Action", "İşlem", "Action"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Column.SubmissionNumber", "Bildiri No", "Submission No"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Column.Type", "Tür", "Type"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Column.Title", "Başlık", "Title"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Column.Topic", "Konu", "Topic"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Column.Congress", "Kongre", "Congress"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Column.AssignedAt", "Atanma", "Assigned"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Column.DueDate", "Son Tarih", "Due Date"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Column.Status", "Durum", "Status"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Column.Recommendation", "Öneri", "Recommendation"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.BlindReview.Short", "Yazar bilgisi gizlidir", "Author information is hidden"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Due.Today", "Bugün", "Today"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Due.Overdue", "Süre geçti", "Overdue"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Due.RemainingFormat", "{0} gün kaldı", "{0} day(s) left"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Evaluate.PageTitle", "Bildiri Değerlendir", "Evaluate Submission"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Evaluate.Title", "Bildiri Değerlendir", "Evaluate Submission"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Evaluate.Subtitle", "Bildiriyi inceleyin, kriterleri puanlayın ve önerinizi gönderin.", "Review the submission, score the criteria, and send your recommendation."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Action.BackToList", "Listeye Dön", "Back to List"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.BlindReview.Title", "Gizli hakem değerlendirmesi", "Confidential reviewer evaluation"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.BlindReview.Description", "Bu ekranda yazar bilgileri gösterilmez. Değerlendirmenizi yalnızca bildirinin içeriğine göre yapın.", "Author information is not shown on this page. Please evaluate based only on the submission content."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.SubmissionInfo.Title", "Bildiri Bilgileri", "Submission Details"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.SubmissionInfo.Description", "Değerlendireceğiniz bildirinin temel bilgileri.", "Basic details of the submission you will evaluate."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.SubmissionNumber", "Bildiri No", "Submission No"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.SubmissionType", "Bildiri Türü", "Submission Type"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Topic", "Konu", "Topic"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.AssignedDate", "Atanma Tarihi", "Assigned Date"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.DueDate", "Son Değerlendirme Tarihi", "Evaluation Due Date"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.EvaluationType", "Değerlendirme Tipi", "Evaluation Type"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.BlindEvaluation", "Gizli Değerlendirme", "Confidential Evaluation"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Content.Title", "Başlık, Anahtar Kelimeler ve Özet", "Title, Keywords, and Abstract"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Title", "Başlık", "Title"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Keywords", "Anahtar Kelimeler", "Keywords"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Abstract", "Özet", "Abstract"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Language.Turkish", "Türkçe", "Turkish"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Language.English", "İngilizce", "English"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Files.Title", "Bildiri Dosyaları", "Submission Files"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Files.Description", "Değerlendirme için paylaşılmış dosyaları inceleyin.", "Review the files shared for evaluation."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Files.Empty", "Bu bildiriye bağlı dosya bulunamadı.", "No file is attached to this submission."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Files.Download", "Dosyayı indir", "Download file"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Criteria.Title", "Puanlama Kriterleri", "Scoring Criteria"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Criteria.Description", "Her kriter için 0 ile 10 arasında puan verin.", "Score each criterion between 0 and 10."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Criteria.Criterion", "Kriter", "Criterion"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Criteria.DescriptionColumn", "Açıklama", "Description"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Criteria.Score", "Puan", "Score"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Criteria.SelectScore", "Seçiniz", "Select"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Summary.Title", "Değerlendirme Özeti", "Evaluation Summary"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Summary.Status", "Durum", "Status"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Summary.DueDate", "Son Tarih", "Due Date"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Summary.Score", "Puanlama", "Score"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Recommendation.Title", "Genel Öneriniz", "Your Recommendation"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Recommendation.Label", "Öneriniz", "Recommendation"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Recommendation.Placeholder", "Seçiniz", "Select"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Recommendation.Warning", "Göndermeden önce tüm kriterleri puanladığınızdan emin olun.", "Make sure you have scored all criteria before submitting."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Recommendation.Accept", "Kabul edilebilir", "Can be accepted"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Recommendation.MinorRevision", "Küçük düzeltme gerekli", "Minor revision needed"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Recommendation.MajorRevision", "Kapsamlı düzeltme gerekli", "Major revision needed"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Recommendation.Reject", "Reddedilmesi önerilir", "Recommend rejection"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Recommendation.None", "Henüz seçilmedi", "Not selected yet"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.AuthorComment.Title", "Yazara İletilecek Yorum", "Comment Shared With Author"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.AuthorComment.Description", "Bu yorum yazar tarafından görülebilir.", "The author can see this comment."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.AuthorComment.Placeholder", "Yazar için açık, yapıcı ve anlaşılır değerlendirmenizi yazın...", "Write a clear, constructive comment for the author..."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.EditorComment.Title", "Editöre Not", "Note to Editor"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.EditorComment.Description", "Bu not yazara gösterilmez.", "This note is not shown to the author."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.EditorComment.Placeholder", "Editör için özel notunuzu yazın...", "Write a private note for the editor..."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Form.Actions.Title", "İşlemler", "Actions"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Action.SaveDraft", "Taslak Kaydet", "Save Draft"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Action.SubmitEvaluation", "Değerlendirmeyi Gönder", "Submit Evaluation"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Status.Pending", "Bekliyor", "Pending"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Status.Draft", "Devam Ediyor", "In progress"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Status.Completed", "Tamamlandı", "Completed"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Action.Evaluate", "Değerlendir", "Evaluate"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Action.Continue", "Devam Et", "Continue"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Action.View", "Görüntüle", "View"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Message.SavedDraft", "Değerlendirmeniz taslak olarak kaydedildi.", "Your evaluation has been saved as a draft."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Message.Submitted", "Değerlendirmeniz gönderildi.", "Your evaluation has been submitted."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Error.ReviewerProfileNotFound", "Hakem profiliniz bulunamadı.", "Your reviewer profile could not be found."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Error.EvaluationNotFound", "Değerlendirme kaydı bulunamadı.", "The evaluation record could not be found."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Error.EvaluationNotAssigned", "Bu değerlendirme size atanmış değil.", "This evaluation is not assigned to you."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Error.EvaluationAlreadyCompleted", "Bu değerlendirme tamamlandığı için güncellenemez.", "This evaluation has already been completed and cannot be updated."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Error.AllCriteriaMustBeScored", "Göndermeden önce tüm kriterleri puanlamalısınız.", "You must score all criteria before submitting."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Error.RecommendationRequired", "Değerlendirmeyi göndermek için genel önerinizi seçmelisiniz.", "You must select your recommendation before submitting."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Error.PendingEvaluationsBlockEditor", "Atanmış hakem değerlendirmeleri tamamlanmadan editör karar veremez.", "The editor cannot make a decision before assigned reviewer evaluations are completed."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.History.EvaluationCompleted", "Hakem değerlendirmesi tamamlandı.", "Reviewer evaluation completed."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.History.AllCompleted", "Tüm hakem değerlendirmeleri tamamlandı. Bildiri editör kararına hazır hale geldi.", "All reviewer evaluations are completed. The submission is ready for editorial decision."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Confirm.Submit.Title", "Değerlendirme gönderilsin mi?", "Submit evaluation?"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Confirm.Submit.Text", "Gönderdikten sonra bu değerlendirmeyi değiştiremezsiniz.", "You cannot change this evaluation after submitting it."),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Confirm.Submit.Button", "Evet, gönder", "Yes, submit"),
        new("BackOffice.ReviewerEvaluations", "BackOffice.ReviewerEvaluations.Confirm.Submit.Fallback", "Değerlendirme gönderilsin mi? Gönderdikten sonra değişiklik yapamazsınız.", "Submit evaluation? You cannot change it after submitting."),
    };
}
