namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class SubmissionManagementUiResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.PageTitle", "Bildiri Yönetimi", "Submission Management"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.PageSubtitle", "Gönderilen bildirileri inceleyin, hakemleri yönetin ve karar işlemlerini tamamlayın.", "Review submitted papers, manage reviewers, and complete decision actions."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Breadcrumb.Dashboard", "Panel", "Dashboard"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Breadcrumb.Index", "Bildiri Yönetimi", "Submission Management"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Breadcrumb.Detail", "Detay", "Details"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Index.InfoTitle", "Editör bildiri yönetimi", "Editorial submission management"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Index.InfoDescription", "Bu ekranda kongreye gönderilen bildirileri görüntüleyebilir ve yönetim sayfasına geçebilirsiniz.", "Use this page to view submitted papers and open their management page."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.Total", "Toplam", "Total"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.Submitted", "Gönderildi", "Submitted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.ReviewerProcess", "Hakem Süreci", "Reviewer Process"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.PaymentPending", "Ödeme Bekleyen", "Payment Pending"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.Accepted", "Kabul", "Accepted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.InReview", "İncelemede", "In review"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.Revision", "Düzeltme", "Revision"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.Rejected", "Reddedilen", "Rejected"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.Payment", "Ödeme", "Payment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Title", "Filtreler", "Filters"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Search.Label", "Arama", "Search"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Search.Placeholder", "Bildiri no, başlık, konu, tür veya yazar ara...", "Search by submission number, title, topic, type, or author..."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Search.Button", "Ara", "Search"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.List.Title", "Bildiri Listesi", "Submission List"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.List.Description", "Editör tarafında yeni bildiri oluşturulmaz; yalnızca mevcut başvurular yönetilir.", "Editors do not create new submissions here; only existing submissions are managed."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.ExportExcel", "Excel'e Aktar", "Export to Excel"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Empty.Title", "Bildiri bulunamadı", "No submissions found"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Empty.Description", "Arama kriterine uygun bildiri kaydı bulunmuyor.", "No submission matches the search criteria."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.Manage", "İşlem", "Action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.Submission", "Bildiri", "Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.TypeTopic", "Tür / Konu", "Type / Topic"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.Authors", "Yazarlar", "Authors"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.Payment", "Ödeme", "Payment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.Status", "Durum", "Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.Date", "Tarih", "Date"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.Manage", "Yönet", "Manage"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Field.Orcid", "ORCID", "ORCID"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.CorrespondingShort", "Sorumlu", "Corresponding"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.CountFormat", "{0} yazar", "{0} author(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.BackToList", "Listeye Dön", "Back to List"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.Print", "Yazdır", "Print"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Meta.Congress", "Kongre", "Congress"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Meta.CorrespondingAuthor", "Sorumlu Yazar", "Corresponding Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Meta.SubmittedAt", "Gönderim", "Submitted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.Title", "Editör işlemi bekleniyor", "Editor action required"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.Description", "Hakem değerlendirmelerini kontrol edin. Yeterli bilgi oluştuysa karar sekmesinden yazar için sonucu belirleyin.", "Check reviewer evaluations. If enough information is available, set the result for the author from the decision tab."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.ReviewCompletionFormat", "{0} / {1} hakem tamamladı", "{0} / {1} reviewers completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.MakeDecision", "Karar Ver", "Make Decision"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.AssignReviewer", "Hakem Ata", "Assign Reviewer"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.ViewEvaluations", "Değerlendirmeleri Gör", "View Evaluations"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Action.MarkPaymentCompleted", "Ödeme İşlemi Yap", "Mark Payment as Completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.EditorStatus", "Editör durumu", "Editor status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.ReviewerStatus", "Hakem durumu", "Reviewer status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.ReviewCompletedFormat", "{0} / {1} tamamlandı", "{0} / {1} completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.AverageScore", "Ortalama puan", "Average score"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.LastAction", "Son işlem", "Last action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.Summary", "Özet", "Summary"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.SummaryDescription", "Bildiri, yazar ve durum", "Submission, author, and status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.ReviewerAssignment", "Hakem Ataması", "Reviewer Assignment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.ReviewerAssignmentDescription", "Hakem seç ve süre ver", "Select reviewer and due date"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.Evaluations", "Değerlendirmeler", "Evaluations"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.EvaluationsDescription", "Hakem değerlendirme sonuçları", "Reviewer evaluation results"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.Decision", "Karar", "Decision"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.DecisionDescription", "Yazara iletilecek sonucu belirle", "Set the result to share with the author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.Files", "Dosyalar", "Files"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.FilesDescription", "Yazarın yüklediği dosyalar", "Files uploaded by the author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.History", "Geçmiş", "History"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Tab.HistoryDescription", "Bildiri hareketleri", "Submission updates"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Summary.SubmissionInfoTitle", "Bildiri Bilgileri", "Submission Details"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Summary.SubmissionInfoDescription", "Karar vermeden önce temel başvuru bilgilerini kontrol edin.", "Review the main submission details before making a decision."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Field.SubmissionNumber", "Bildiri No", "Submission No"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Field.SubmissionType", "Bildiri Türü", "Submission Type"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Field.Topic", "Konu", "Topic"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Field.PaymentStatus", "Ödeme Durumu", "Payment Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Field.Abstract", "Özet", "Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Summary.AuthorsTitle", "Yazar Bilgileri", "Author Details"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Summary.AuthorsDescription", "Başvurudaki yazar ve iletişim bilgileri.", "Author and contact information for this submission."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Summary.AuthorsEmpty", "Yazar bilgisi bulunamadı.", "No author information was found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.Role.Corresponding", "Sorumlu Yazar", "Corresponding Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.Role.Default", "Yazar", "Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.Badge.Corresponding", "İletişim Yazarı", "Contact Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.Badge.CoAuthor", "Ortak Yazar", "Co-author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Summary.SuggestedFlowTitle", "Editör için önerilen akış", "Suggested editor flow"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Summary.SuggestedFlowDescription", "Önce değerlendirmeleri kontrol edin. Eksik değerlendirme varsa hakem atayın. Yeterli bilgi varsa karar sekmesinden sonucu belirleyin.", "Check evaluations first. Assign a reviewer if evaluations are missing. If enough information is available, set the result from the decision tab."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Summary.QuickActions", "Hızlı İşlemler", "Quick Actions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.ReviewEvaluations", "Değerlendirmeleri İncele", "Review Evaluations"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.FinalDecision", "Sonucu Belirle", "Set Result"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.RestartProcess", "Süreci Yeniden Başlat", "Restart Process"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.AssignedTitle", "Atanan Hakemler", "Assigned Reviewers"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.AssignedDescription", "Bu bildiriye atanmış hakemlerin değerlendirme durumu.", "Evaluation status of reviewers assigned to this submission."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.CountFormat", "{0} hakem", "{0} reviewer(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.Empty", "Bu bildiriye henüz hakem atanmamış.", "No reviewer has been assigned to this submission yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.AssignedAt", "Atama", "Assigned"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.Completed", "Tamamladı", "Completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.Waiting", "Bekliyor", "Waiting"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.InfoTitle", "Hakem seçimi hakkında", "About reviewer selection"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.InfoDescription", "Bu bildiri için uygun hakemi seçin ve gerekiyorsa son değerlendirme tarihini belirtin.", "Select a suitable reviewer for this submission and set a due date if needed."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.NewTitle", "Yeni Hakem Ata", "Assign New Reviewer"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.NewDescription", "Hakem rolündeki kullanıcılar bu listeden atanır.", "Users with the reviewer role can be assigned from this list."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.NoCandidate", "Atanabilir hakem bulunamadı. Önce kullanıcıyı hakem olarak tanımlayın.", "No assignable reviewer was found. Define a user as a reviewer first."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.UserList", "Kullanıcı Listesi", "User List"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.Label.Reviewer", "Hakem", "Reviewer"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.SelectReviewer", "Hakem seçiniz", "Select reviewer"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Common.InstitutionEmpty", "Kurum yok", "No institution"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.WillBeAddedToPool", "hakem listesine eklenecek", "will be added to reviewer list"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.DueDate", "Son Değerlendirme Tarihi", "Evaluation Due Date"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.DueDateHelp", "Hakemin değerlendirmeyi tamamlaması beklenen tarihi seçin.", "Select the date by which the reviewer is expected to complete the evaluation."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.Note", "Hakeme / editöre not", "Note for reviewer / editor"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.NotePlaceholder", "Hakem ataması için kısa bir not yazın.", "Write a short note for this reviewer assignment."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.AssignInfo", "Hakem atandığında bildiri ile ilişkilendirilir ve değerlendirme yapabilir.", "After assignment, the reviewer is linked to the submission and can evaluate it."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Reviewers.RequiredMessage", "Lütfen hakem seçiniz.", "Please select a reviewer."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.InfoTitle", "Değerlendirme özeti", "Evaluation summary"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.InfoDescription", "Hakem kararlarını, puanları ve yazara iletilecek yorumları buradan kontrol edin.", "Review recommendations, scores, and comments to be shared with the author here."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.Empty", "Henüz hakem değerlendirmesi yok.", "There are no reviewer evaluations yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.Date", "Değerlendirme tarihi", "Evaluation date"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.RecommendationEmpty", "Öneri yok", "No recommendation"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.Score", "Puan", "Score"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.Criterion", "Kriter", "Criterion"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.CommentEmpty", "Yorum bulunmuyor.", "No comment was provided."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Title", "Karar", "Decision"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Description", "Yazara iletilecek sonucu bu bölümden belirleyin.", "Set the result to be shared with the author from this section."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.NoAction", "Bu durum için uygulanabilir karar işlemi bulunmuyor.", "No decision action is available for the current status."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.ConfirmText", "Bu işlem bildirinin durumunu güncelleyecek. Devam edilsin mi?", "This action will update the submission status. Continue?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.ConfirmButton", "Evet, uygula", "Yes, apply"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.ActionBadge", "Karar işlemi", "Decision action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.PublicNote", "Yazara Gönderilecek Not", "Note to Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.PublicNotePlaceholder", "Yazara görünecek karar metnini yazın...", "Write the decision note that the author will see..."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.InternalNote", "İç Editör Notu", "Internal Editor Note"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.InternalNotePlaceholder", "Bu not yazara gösterilmez.", "This note is not shown to the author."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.DisabledDefault", "Bu işlem şu anda uygulanamaz.", "This action cannot be applied right now."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.BeforeTitle", "Karar vermeden önce", "Before making a decision"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.BeforeDescription", "Hakem değerlendirmeleri eksikse önce değerlendirme sürecini tamamlayın. Karar verdiğinizde yazara görünür notu dikkatli yazın.", "If reviewer evaluations are missing, complete the evaluation step first. When making a decision, write the author-visible note carefully."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.ReviewerSummaryTitle", "Hakem Karar Özeti", "Reviewer Recommendation Summary"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.NoEvaluationYet", "Henüz değerlendirme yok.", "No evaluation yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.SuggestionLabel", "Öneri", "Suggestion"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.SuggestionText", "Hakem notlarını ve puanları birlikte değerlendirerek karar verin.", "Make a decision by considering reviewer notes and scores together."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Transition.Accept", "Kabul Et", "Accept"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Transition.Reject", "Reddet", "Reject"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Transition.Revision", "Düzeltme İste", "Request Changes"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Transition.SendToReview", "Hakeme Gönder", "Send to Review"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Transition.Payment", "Ödeme / Belge İste", "Request Payment / Document"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Transition.Complete", "Ödemeyi Tamamla", "Complete Payment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Transition.Withdraw", "Geri Çek", "Withdraw"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Restart.ModalTitle", "Bildiri süreci yeniden başlatılsın mı?", "Restart submission process?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Restart.ModalText", "Bu işlem bildiriyi tekrar Gönderildi durumuna alır. Mevcut hakem atamaları, değerlendirmeler, kabul belgeleri ve ödeme süreci yeni süreçte kullanılmayacak şekilde sıfırlanır. Bildiri içeriği, yazarlar ve yüklenen ana dosyalar korunur.", "This action moves the submission back to Submitted. Existing reviewer assignments, evaluations, acceptance letters, and payment process will be reset for the new process. Submission content, authors, and main uploaded files are preserved."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Restart.Submit", "Süreci Yeniden Başlat", "Restart Process"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Transition.Default", "İşlemi Uygula", "Apply Action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Files.Title", "Yazar Dosyaları", "Author Files"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Files.Description", "Editörün inceleyebileceği başvuru dosyaları.", "Submission files available for editor review."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Files.CountFormat", "{0} dosya", "{0} file(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Files.Empty", "Dosya bulunamadı.", "No file was found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Files.UploadedAt", "Yüklenme", "Uploaded"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Files.Download", "İndir", "Download"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.Title", "Süreç Geçmişi", "Process History"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.Description", "Bildiri üzerinde gerçekleşen son işlemler.", "Latest updates on this submission."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.CountFormat", "{0} işlem", "{0} action(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.Empty", "Süreç geçmişi bulunamadı.", "No process history was found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.GenericTitle", "Güncelleme yapıldı", "Update recorded"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.DraftTitle", "Taslak oluşturuldu", "Draft created"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.SubmittedTitle", "Başvuru gönderildi", "Submission sent"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.ReviewAssignmentTitle", "Hakem atama sürecine alındı", "Moved to reviewer assignment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.ReviewStartedTitle", "Değerlendirme başladı", "Evaluation started"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.EditorialDecisionTitle", "Editör değerlendirmesine alındı", "Moved to editorial evaluation"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.AcceptedTitle", "Başvuru kabul edildi", "Submission accepted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.PaymentTitle", "Ödeme bekleniyor", "Payment pending"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.CompletedTitle", "Bildiri süreci tamamlandı", "Submission process completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.RejectedTitle", "Başvuru reddedildi", "Submission rejected"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.WithdrawnTitle", "Başvuru geri çekildi", "Submission withdrawn"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.PaymentCompletedTitle", "Ödeme işlemi yapıldı", "Payment completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.PaymentRevertedTitle", "Ödeme işlemi geri alındı", "Payment completion reverted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.ReviewerAssignedTitle", "Hakem atandı", "Reviewer assigned"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.ReviewCompletedTitle", "Değerlendirme tamamlandı", "Evaluation completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.NoNote", "Not girilmemiş.", "No note was entered."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.History.PerformedBy", "İşlem yapan", "Performed by"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.Title", "İçerik Bilgileri", "Content Information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.Description", "Başlık, özet ve anahtar kelime bilgileri.", "Title, abstract, and keyword information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.LanguageBadge", "Türkçe + İngilizce", "Turkish + English"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.Turkish", "Türkçe İçerik", "Turkish Content"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.English", "İngilizce İçerik", "English Content"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.DefaultLanguage", "Varsayılan başvuru dili.", "Default submission language."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.TranslationFields", "Ek çeviri alanları.", "Additional translation fields."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.TitleLabel", "Başlık", "Title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.TitleLabelEn", "Title", "Title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.AbstractLabel", "Özet", "Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.AbstractLabelEn", "Abstract", "Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.KeywordsLabel", "Anahtar Kelimeler", "Keywords"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Content.KeywordsLabelEn", "Keywords", "Keywords"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.Email", "E-posta", "Email"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.Institution", "Kurum / Üniversite", "Institution / University"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.Orcid", "ORCID", "ORCID"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.Contact", "İletişim", "Contact"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.ImageTitle", "Sergi Görseli", "Exhibition Image"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.ImageDescription", "Başvuruya yüklenen ana görsel.", "Main image uploaded for this application."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.ImageAlt", "Sergi görseli", "Exhibition image"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.Preview", "Ön İzle", "Preview"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.InfoTitle", "Sergi Bilgileri", "Exhibition Information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.InfoDescription", "Eser adı, ölçü, teknik, açıklama ve adres bilgileri.", "Artwork name, dimensions, technique, description, and address."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.WorkName", "Eserin Adı", "Artwork Name"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.Dimensions", "Eser Ölçüsü", "Dimensions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.Technique", "Uygulanan Teknik", "Technique"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.Address", "Adres", "Address"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Exhibition.Description", "Açıklama", "Description"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Files.Kind.ExhibitionImage", "Sergi Görseli", "Exhibition Image"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Files.Kind.AcceptanceLetter", "Kabul Belgesi", "Acceptance Document"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Files.Kind.ParticipationCertificate", "Katılım Belgesi", "Certificate of Participation"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Files.Kind.Other", "Ek Dosya", "Additional File"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.PageTitle", "Bildiri Yönetimi - Düzenle", "Submission Management - Edit"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.BackToList", "Listeye Dön", "Back to List"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.Breadcrumb.Dashboard", "Panel", "Dashboard"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.Breadcrumb.Index", "Bildiri Yönetimi", "Submission Management"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.Breadcrumb.Edit", "Yönetimden Bildiri Düzenle", "Edit Submission as Editor"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ReadOnlyTitle", "Bildiri düzenlenemez", "Submission cannot be edited"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ReadOnlyDescription", "Bu bildiri mevcut iş akışı durumunda güncellenemez. Sadece taslak veya revizyon beklenen durumlarda düzenleme yapılabilir.", "This submission cannot be edited in its current workflow status. Editing is only available for draft or revision-required statuses."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.InfoTitle", "Bildiri düzenleme", "Edit submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.InfoDescription", "Bildiri kongresi değiştirilemez. Bildiri türü, konu, içerik ve yazar bilgilerini güncelleyebilirsiniz.", "The congress cannot be changed. You can update the type, topic, content, and author information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.HeaderTitle", "Yönetimden Bildiri Düzenle", "Edit Submission as Editor"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.HeaderSubtitleSuffix", "numaralı bildiri bilgilerini güncelleyin.", "submission information can be updated."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.BasicInfoSubtitle", "Bildiri türü, konu ve ORCID bilgisini güncelleyin.", "Update submission type, topic, and ORCID information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.CongressReadOnlyHelp", "Bildiri kongresi değiştirilemez.", "The submission congress cannot be changed."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.FullTextFile", "Tam Metin Dosyası", "Full Text File"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.PresentationFile", "Sunum Dosyası", "Presentation File"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.FilesTitle", "Dosyalar", "Files"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.FilesDescription", "Yönetim ekranında dosya güncelleme entegrasyonu sonraki fazda bağlanacaktır.", "File update integration for the management screen will be connected in the next phase."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.StatusTitle", "Mevcut Bildiri Durumu", "Current Submission Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.SubmissionNumber", "Bildiri No", "Submission No"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.SubmissionStatus", "Gönderim Durumu", "Submission Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.LastUpdate", "Son Güncelleme", "Last Update"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.SaveTitle", "Kaydet", "Save"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.SaveButton", "Değişiklikleri Kaydet", "Save Changes"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.SubmittedStatus", "Onaya Gönderildi", "Submitted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.DraftStatus", "Taslak", "Draft"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.Validation.CorrespondingAuthorRequired", "En az bir sorumlu yazar eklenmelidir.", "At least one corresponding author must be added."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.Validation.AuthorTitleRequired", "Her yazar için unvan seçilmelidir.", "A title must be selected for each author."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.Success.Updated", "Bildiri yönetim ekranından güncellendi.", "Submission was updated from the management screen."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.Success.Deleted", "Bildiri yönetim ekranından silindi.", "Submission was deleted from the management screen."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.Evaluation.BackToDetail", "Bildiri detayına dön", "Back to submission detail"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.Evaluation.PageTitle", "Editör Değerlendirmesi", "Editor Evaluation"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.CountFormat", "{0} değerlendirme", "{0} evaluation(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.TotalScoreFormat", "Toplam Puan: {0}", "Total Score: {0}"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.ScoreEmpty", "Kriter bazlı puan bulunamadı.", "No criterion-based score was found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Evaluations.ReviewerComment", "Hakem Yorumu", "Reviewer Comment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionPageTitle", "Sergi Başvurusu Yönetimi - Düzenle", "Exhibition Application Management - Edit"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionHeaderSubtitleSuffix", "numaralı sergi başvurusu bilgilerini güncelleyin.", "exhibition application information can be updated."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionFileOptionalHelp", "Yeni dosya seçmezseniz mevcut sergi dosyası korunur.", "If you do not select a new file, the current exhibition file will be kept."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionCurrentFileTitle", "Mevcut Sergi Dosyası", "Current Exhibition File"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionCurrentFileDescription", "Yeni dosya seçmezseniz bu dosya korunur.", "If you do not select a new file, this file will be kept."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionCurrentFileName", "Dosya adı", "File name"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionCurrentFilePreviewUnavailable", "Dosya ön izlemesi desteklenmiyor", "File preview is not supported"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionSelectedFileTitle", "Seçilen Yeni Dosya", "Selected New File"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionSelectedFileDescription", "Kaydettiğinizde mevcut sergi dosyasının yerine geçer.", "It will replace the current exhibition file when you save."),
        new("BackOffice.Submissions", "BackOffice.ExhibitionApplications.Create.Validation.FileSize", "Sergi dosyası en fazla 20 MB olabilir.", "Exhibition file can be up to 20 MB."),
        new("BackOffice.Submissions", "BackOffice.ExhibitionApplications.Create.Validation.FileType", "Sergi dosyası JPG, PNG, WEBP veya PDF formatında olmalıdır.", "Exhibition file must be in JPG, PNG, WEBP or PDF format."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.CurrentApplicationStatus", "Mevcut Başvuru Durumu", "Current Application Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionInfoTitle", "Sergi başvurusu düzenleme", "Edit exhibition application"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionInfoDescription", "Sergi başvurusunda eser bilgileri ve yazar bilgilerini güncelleyebilirsiniz.", "You can update artwork and author information for this exhibition application."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionHeaderTitle", "Yönetimden Sergi Başvurusu Düzenle", "Edit Exhibition Application"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Edit.ExhibitionTypeReadonlyHelp", "Sergi başvuru türü bu ekranda değiştirilemez.", "The exhibition application type cannot be changed on this page."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Common.Draft", "Taslak", "Draft"),

        new("BackOffice.Submissions", "BackOffice.Sidebar.FullTextBook", "Tam Metinler", "Full Texts"),
        new("BackOffice.Submissions", "BackOffice.Sidebar.VideoPresentations", "Video Sunumları", "Video Presentations"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.PageTitle", "Tam Metinler", "Full Texts"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.ListTitle", "Tam Metin Dosyaları", "Full Text Files"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.ListDescription", "Yazarlar tarafından yüklenen tam metinleri buradan kontrol edebilirsiniz.", "Review full text files uploaded by authors."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.Generate", "Tam Metin Kitabı Oluştur", "Generate Full Text Book"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.GenerateWord", "Word Kitabını Oluştur", "Generate Word Book"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.CoverModalTitle", "Tam Metin Kitabı Oluştur", "Generate Full Text Book"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.CoverModalDescription", "Kitap kapağını seçin ve Word çıktısını oluşturun.", "Select the book cover and generate the Word output."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.DefaultCoverTitle", "Varsayılan kurumsal kapak", "Default corporate cover"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.DefaultCoverDescription", "Kapak seçmezseniz kongre adı, tarihi ve yeri kullanılarak örnek kitaptaki lacivert kurumsal kapak otomatik oluşturulur.", "If no cover is selected, the navy corporate cover is generated automatically using the congress name, dates and location."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.CoverLabel", "Özel kapak görseli (isteğe bağlı)", "Custom cover image (optional)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.CoverHelp", "PNG veya JPG, en fazla 8 MB. A4 kapak görseli kırpılmadan sayfanın tamamına yerleştirilir.", "PNG or JPG, up to 8 MB. The A4 cover image is placed on the full page without cropping."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.CoverPreview", "Kapak önizlemesi", "Cover preview"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.RemoveCover", "Kapağı Kaldır", "Remove Cover"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.CoverTooLarge", "Kapak görseli en fazla 8 MB olabilir.", "The cover image can be up to 8 MB."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.CoverInvalid", "Kapak görseli geçerli bir PNG veya JPG dosyası olmalıdır.", "The cover image must be a valid PNG or JPG file."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.CongressRequired", "Tam metin kitabı oluşturmak için bir kongre seçin.", "Select a congress to generate the full text book."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.Generating", "Tam metin kitabı hazırlanıyor...", "Generating full text book..."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextBook.GenerationFailed", "Tam metin kitabı oluşturulamadı.", "The full text book could not be generated."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.VideoPresentations.PageTitle", "Video Sunumları", "Video Presentations"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.VideoPresentations.ListTitle", "Video Sunum Dosyaları", "Presentation Video Files"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.VideoPresentations.ListDescription", "Yazarlar tarafından yüklenen video sunumlarını kontrol edin ve program kitabı görünürlüğünü yönetin.", "Review presentation videos uploaded by authors and manage program book visibility."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.BulkApprove", "Seçilenleri Onayla", "Approve Selected"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.BulkRevert", "Onayı Geri Al", "Revert Approval"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.BulkDownload", "Seçilenleri İndir", "Download Selected"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.PublicLinks", "Kısa Linkleri Al", "Get Short Links"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.PublicLink", "Kısa Link", "Short Link"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.Preview", "Önizle", "Preview"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.Watch", "İzle", "Watch"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.Download", "İndir", "Download"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.Approve", "Onayla", "Approve"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.Revert", "Onayı Geri Al", "Revert Approval"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.IncludeProgramBook", "Program Kitabına Ekle", "Include in Program Book"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.ExcludeProgramBook", "Program Kitabından Çıkar", "Remove from Program Book"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Help.BulkActions", "Onay işlemi için satırları seçip üstteki toplu işlem butonlarını kullanabilirsiniz.", "Select rows and use the bulk action buttons above for approval operations."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Table.SubmissionNumber", "Bildiri No", "Submission No"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Table.Title", "Bildiri Başlık", "Submission Title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Table.Author", "Yazar", "Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Table.File", "Dosya", "File"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Table.ApprovalStatus", "Onay Durumu", "Approval Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Table.ProgramBook", "Program Kitabı", "Program Book"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Table.UploadedAt", "Yükleme Tarihi", "Upload Date"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Table.Actions", "İşlemler", "Actions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Status.PendingReview", "Onay Bekliyor", "Pending Review"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Status.Approved", "Onaylandı", "Approved"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Status.Rejected", "Reddedildi", "Rejected"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Status.RevisionRequested", "Revizyon İstendi", "Revision Requested"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.SelectAtLeastOne", "Lütfen en az bir dosya seçin.", "Please select at least one file."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.FileNotFound", "Dosya bulunamadı.", "File not found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.UnsupportedFileType", "Bu dosya tipi final dosya incelemesi için uygun değildir.", "This file type is not supported for final file review."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.InvalidReviewStatus", "Geçersiz inceleme durumu.", "Invalid review status."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.NoteRequired", "Reddetme veya revizyon isteği için açıklama girilmelidir.", "A note is required for rejection or revision request."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.Approved", "Dosya onaylandı.", "File approved."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.Rejected", "Dosya reddedildi.", "File rejected."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.RevisionRequested", "Dosya için revizyon istendi.", "Revision requested for the file."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.Reverted", "Dosya inceleme bekliyor durumuna alındı.", "File moved back to pending review."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.OnlyVideoProgramBook", "Program kitabına yalnızca video sunum dosyaları eklenebilir.", "Only presentation video files can be included in the program book."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.ApprovalRequiredForProgramBook", "Program kitabına eklemek için video önce onaylanmalıdır.", "The video must be approved before it can be included in the program book."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.ProgramBookIncluded", "Video program kitabına eklendi.", "Video included in the program book."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.ProgramBookExcluded", "Video program kitabından çıkarıldı.", "Video removed from the program book."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Confirm.Title", "İşlem onayı", "Confirm Action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Confirm.Approve", "Seçilen dosyalar onaylanacak. Devam edilsin mi?", "Selected files will be approved. Continue?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Confirm.Revert", "Seçilen dosyaların onayı geri alınacak. Devam edilsin mi?", "Approval for selected files will be reverted. Continue?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.PublicLinks.Title", "Kısa Linkler", "Short Links"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.PublicLinks.Label", "Seçilen dosyaların kısa linkleri", "Short links for selected files"),

        // Added by localization audit: statically used keys that previously had no seed definition.
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Action.RevertPayment", "Ödeme İşlemini Geri Al", "Revert Payment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Column.RowNumber", "Sıra No", "No."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.DeleteButton", "Sil", "Delete"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.DeleteConfirmButton", "Evet, sil", "Yes, delete"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.DeleteConfirmText", "Bu bildiri silinecek. Bu işlem geri alınamaz.", "This submission will be deleted. This action cannot be undone."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.DeleteConfirmTitle", "Bildiri silinsin mi?", "Delete submission?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.EditButton", "Düzenle", "Edit"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.Approve", "Kabul Et", "Approve"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.Detail", "Detay", "Details"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.EditorEvaluation", "Editör Değerlendirmesi", "Editor Evaluation"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.Evaluations", "Değerlendirmeler", "Evaluations"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.Files", "Dosyalar", "Files"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.History", "Geçmiş", "History"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.Payment", "Ödeme", "Payment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.Reject", "Reddet", "Reject"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Action.ReviewerAssignment", "Hakem Ataması", "Reviewer Assignment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Author.AdditionalCountFormat", "+{0} yazar daha", "+{0} more author(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Approve.ModalTitle", "Bildiriyi Kabul Et", "Approve Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Approve.Submit", "Kabul Et", "Approve"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.EvaluationRequired", "Karar vermeden önce editör değerlendirmesini tamamlayın.", "Complete the editor evaluation before making a decision."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Reject.ModalTitle", "Bildiriyi Reddet", "Reject Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Reject.Submit", "Reddet", "Reject"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Apply", "Filtrele", "Apply Filters"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Congress.AllActive", "Tüm aktif kongreler", "All active congresses"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Congress.AllArchived", "Tüm arşiv kongreleri", "All archived congresses"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.ViewArchive", "Arşivi Görüntüle", "View Archive"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.ViewActive", "Aktif Kongreleri Görüntüle", "View Active Congresses"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Congress.Label", "Kongre", "Congress"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Payment.All", "Tüm ödeme durumları", "All payment statuses"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Payment.Label", "Ödeme Durumu", "Payment Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Reset", "Filtreleri Temizle", "Clear Filters"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Status.All", "Tüm süreç durumları", "All workflow statuses"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Status.Label", "Süreç Durumu", "Workflow Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.SubmissionType.All", "Tüm bildiri türleri", "All submission types"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.SubmissionType.Label", "Bildiri Türü", "Submission Type"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Topic.All", "Tüm konular", "All topics"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Topic.Label", "Konu", "Topic"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.AcceptedBadge", "Kabul Edildi", "Accepted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.AcceptedDescription", "Bildiri kabul edildi. Ödeme ve nihai dosya süreçlerini takip edin.", "The submission has been accepted. Track payment and final file processes."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.AcceptedTitle", "Bildiri kabul edildi", "Submission accepted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.CompletedBadge", "Tamamlandı", "Completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.CompletedDescription", "Bildiri sürecindeki gerekli işlemler tamamlandı.", "The required submission processes have been completed."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.CompletedTitle", "Süreç tamamlandı", "Process completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.PaymentBadge", "Ödeme Bekleniyor", "Payment Pending"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.PaymentDescription", "Ödeme durumunu kontrol edin ve ödeme alındığında işlemi tamamlayın.", "Check the payment status and complete the process when payment is received."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.PaymentTitle", "Ödeme işlemi bekleniyor", "Payment action required"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.RejectedBadge", "Reddedildi", "Rejected"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.RejectedDescription", "Bildiri reddedildi. Gerekirse süreç geçmişini inceleyin.", "The submission has been rejected. Review the process history if necessary."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.RejectedTitle", "Bildiri reddedildi", "Submission rejected"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Stat.PaymentCompleted", "Ödeme Yapıldı", "Payment Completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.Congress", "Kongre", "Congress"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.SubmissionNumber", "Bildiri No", "Submission No."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.SubmissionTitle", "Bildiri Başlığı", "Submission Title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.Revert.Error", "Ödeme işlemi geri alınamadı.", "The payment action could not be reverted."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.Revert.Success", "Ödeme işlemi geri alındı.", "The payment action has been reverted."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.RevertConfirm.Description", "Ödeme durumu yeniden ödeme bekleniyor olarak güncellenecek.", "The payment status will be changed back to payment pending."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.RevertConfirm.Title", "Ödeme işlemi geri alınsın mı?", "Revert payment action?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.ReviewerAssignment.DisabledAfterEvaluation", "Değerlendirme başladıktan sonra hakem ataması değiştirilemez.", "Reviewer assignment cannot be changed after evaluation has started."),

        // Added by localization audit: complete static Submission Management resource-key contracts.
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Approve.ModalText", "Bu bildiriyi kabul etmek istediğinize emin misiniz?", "Are you sure you want to approve this submission?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Decision.Reject.ModalText", "Bu bildiriyi reddetmek istediğinize emin misiniz?", "Are you sure you want to reject this submission?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.Description", "Listeyi kongre, durum, ödeme, konu ve bildiri türüne göre filtreleyin.", "Filter the list by congress, status, payment, topic, and submission type."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.PendingBadge", "Bekliyor", "Pending"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.PendingDescription", "Bildiriyi inceleyin, gerekirse hakem atayın ve değerlendirme sürecini başlatın.", "Review the submission, assign a reviewer if needed, and start the evaluation process."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Focus.PendingTitle", "Değerlendirme Bekleniyor", "Evaluation Pending"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Index.BadgeTitle", "Editör İşlemleri", "Editor Actions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.Description", "Bildiriye ait ödeme durumunu ve ödeme belgelerini yönetin.", "Manage the submission payment status and payment documents."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.Document.Approved", "Onaylandı", "Approved"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.Document.Pending", "Onay Bekliyor", "Pending Approval"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.Documents.Empty", "Henüz ödeme belgesi yüklenmemiş.", "No payment document has been uploaded yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.Documents.Title", "Ödeme Belgeleri", "Payment Documents"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.ManualConfirm.Description", "Ödemenin alındığını doğrulayarak durumu ödeme yapıldı olarak güncelleyin.", "Confirm receipt of payment and update the status to payment completed."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.ManualConfirm.Title", "Ödemeyi Onayla", "Confirm Payment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Payment.Title", "Ödeme İşlemleri", "Payment Operations"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Tab.Payment", "Ödeme", "Payment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Tab.Payment.Description", "Ödeme durumu ve belgeler", "Payment status and documents"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.OwnerMultiplicity.Label", "Başvuru Sayısı", "Submission Count"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.OwnerMultiplicity.All", "Tüm başvuru sahipleri", "All submission owners"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.OwnerMultiplicity.Single", "Tek bildirisi olanlar", "Owners with one submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Filters.OwnerMultiplicity.Multiple", "Birden fazla bildirisi olanlar", "Owners with multiple submissions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Table.SubmissionOwner", "Başvuru Sahibi", "Submission Owner"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Owner.SubmissionCountFormat", "{0} Bildiri", "{0} Submissions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Owner.MultipleBadgeTitle", "Bu kullanıcı aynı kongrede birden fazla bildiri oluşturmuştur.", "This user created multiple submissions in the same congress."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.Editor.Owner.Missing", "Başvuru sahibi bulunamadı", "Submission owner not found"),
    };
}
