namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class SubmissionResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("BackOffice.Sidebar", "BackOffice.Sidebar.Submissions", "Bildiriler", "Submissions"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.SubmissionEvaluations", "Değerlendirmeler", "Evaluations"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.PaymentDocuments", "Ödeme Belgeleri", "Payment Documents"),

        new("BackOffice.Submissions", "BackOffice.Submissions.PageTitle", "Bildiriler", "Submissions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.PageDescription", "Kongrelere gönderilen bildirileri yönetin.", "Manage submissions sent to congresses."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create", "Yeni Bildiri", "New Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Manage", "Yönet", "Manage"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Title", "Başlık", "Title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.SubmissionNumber", "Bildiri No", "Submission No"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Status", "Durum", "Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.SubmittedAt", "Gönderim Tarihi", "Submitted At"),
        new("BackOffice.Submissions", "BackOffice.Submissions.NoRecords", "Kayıt bulunamadı", "No records found"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.EntityNotFound", "Bildiri kaydı bulunamadı.", "Submission was not found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.CongressNotFound", "Kongre kaydı bulunamadı.", "Congress was not found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.CongressWorkflowNotConfigured", "Kongre için iş akışı tanımlanmamış.", "Workflow is not configured for this congress."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.SubmissionSubmitTransitionNotConfigured", "Bildiri gönderimi için geçiş tanımlanmamış.", "Submission transition is not configured."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.SubmissionTypeRequired", "Bildiri türü zorunludur.", "Submission type is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.TopicRequired", "Konu seçimi zorunludur.", "Topic selection is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.SubmissionTypeNotAvailableForCongress", "Seçilen bildiri türü bu kongre için kullanılamaz.", "The selected submission type is not available for this congress."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.AcademicSubmissionTypeCannotBeExhibition", "Akademik bildiri türü sergi başvurusu olarak kullanılamaz.", "Academic submission type cannot be used as an exhibition application."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.ExhibitionSubmissionTypeRequired", "Sergi başvurusu için sergi bildiri türü gereklidir.", "An exhibition submission type is required for exhibition applications."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.TopicNotAvailableForCongress", "Seçilen konu bu kongre için kullanılamaz.", "The selected topic is not available for this congress."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.CorrespondingAuthorRequired", "En az bir sorumlu yazar eklenmelidir.", "At least one corresponding author must be added."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.SubmissionCannotBeUpdated", "Bu bildiri mevcut durumunda güncellenemez.", "This submission cannot be updated in its current status."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.SubmissionDraftCreatedHistoryNote", "Bildiri taslak olarak oluşturuldu.", "Submission was created as a draft."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.SubmissionCreatedAndSubmittedHistoryNote", "Bildiri oluşturuldu ve değerlendirmeye gönderildi.", "Submission was created and sent for evaluation."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.SubmissionUpdatedHistoryNote", "Bildiri bilgileri güncellendi.", "Submission details were updated."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.SubmissionUpdatedAndSubmittedHistoryNote", "Bildiri güncellendi ve değerlendirmeye gönderildi.", "Submission was updated and sent for evaluation."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.UserInfoNotFound", "Kullanıcı bilgisi bulunamadı.", "User information was not found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Business.EvaluationStatusTransitionFailed", "Değerlendirme durumu geçişi tamamlanamadı.", "Evaluation status transition could not be completed."),

        new("BackOffice.Workflow", "BackOffice.Workflow.ChangeStatus", "Durum Değiştir", "Change Status"),
        new("BackOffice.Workflow", "BackOffice.Workflow.AllowedTransitions", "Uygun Geçişler", "Allowed Transitions"),
        new("BackOffice.Workflow", "BackOffice.Workflow.NoAllowedTransitions", "Uygun geçiş bulunamadı", "No allowed transitions found"),
        new("BackOffice.Workflow", "BackOffice.Workflow.Comment", "Açıklama", "Comment"),
        new("BackOffice.Workflow", "BackOffice.Workflow.History", "İşlem Geçmişi", "History"),

        // Added by localization audit: statically used keys that previously had no seed definition.
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.CurrentWorkflowStatusNotFound", "Bildirinin mevcut iş akışı durumu bulunamadı.", "The current workflow status of the submission was not found."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.EvaluationCompletedNoNewReviewer", "Değerlendirmesi tamamlanan bildiriye yeni hakem atanamaz.", "A new reviewer cannot be assigned after the evaluation is completed."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.FinalStatusNoReviewer", "Nihai durumdaki bildiriye hakem atanamaz.", "A reviewer cannot be assigned to a submission in a final status."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.ReviewerAlreadyAssigned", "Seçilen hakem bu bildiriye zaten atanmış.", "The selected reviewer is already assigned to this submission."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.ReviewerAssignmentStatusNotFound", "Hakem atama durumu bulunamadı.", "The reviewer assignment status was not found."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.ReviewerAssignmentTransitionNotFound", "Hakem atama geçişi bulunamadı.", "The reviewer assignment transition was not found."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.ReviewerAssignmentWorkflowFailed", "Hakem ataması sırasında iş akışı güncellenemedi.", "The workflow could not be updated during reviewer assignment."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.ReviewerNotActive", "Seçilen hakem aktif değil.", "The selected reviewer is not active."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.ReviewerNotFound", "Hakem bulunamadı.", "The reviewer was not found."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.ReviewerPassiveInCongress", "Seçilen hakem bu kongrede pasif durumda.", "The selected reviewer is inactive for this congress."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.SubmissionNotFound", "Bildiri bulunamadı.", "The submission was not found."),
        new("BackOffice.Submissions", "BackOffice.SubmissionReviewers.Business.WorkflowStatusNotFound", "İş akışı durumu bulunamadı.", "The workflow status was not found."),
        new("BackOffice.Submissions", "BackOffice.SubmissionWorkflow.Validation.UnsupportedTargetStatus", "Hedef iş akışı durumu desteklenmiyor.", "The target workflow status is not supported."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AbstractEnMaxLength", "İngilizce özet en fazla 10.000 karakter olabilir.", "English abstract can be at most 10,000 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AbstractMaxLength", "Özet metni en fazla 10.000 karakter olabilir.", "Abstract can be at most 10,000 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AbstractRequired", "Özet metni zorunludur.", "Abstract is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AddressMaxLength", "Adres bilgisi en fazla 1.000 karakter olabilir.", "Address can be at most 1,000 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AddressRequired", "Adres bilgisi zorunludur.", "Address is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AuthorEmailInvalid", "Geçerli bir yazar e-posta adresi girin.", "Enter a valid author email address."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AuthorEmailMaxLength", "Yazar e-posta adresi en fazla 150 karakter olabilir.", "Author email can be at most 150 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AuthorEmailRequired", "Yazar e-posta adresi zorunludur.", "Author email is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AuthorFullNameMaxLength", "Yazar adı soyadı en fazla 250 karakter olabilir.", "Author full name can be at most 250 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AuthorFullNameRequired", "Yazar adı soyadı zorunludur.", "Author full name is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AuthorInstitutionMaxLength", "Yazar kurumu en fazla 250 karakter olabilir.", "Author institution can be at most 250 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AuthorInstitutionRequired", "Yazar kurumu zorunludur.", "Author institution is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AuthorOrcidMaxLength", "Yazar ORCID bilgisi en fazla 50 karakter olabilir.", "Author ORCID can be at most 50 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AuthorTitleRequired", "Yazar unvanı zorunludur.", "Author title is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.AuthorsRequired", "En az bir yazar eklenmelidir.", "At least one author is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.CongressRequired", "Kongre bilgisi zorunludur.", "Congress is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.CorrespondingAuthorRequired", "En az bir sorumlu yazar seçilmelidir.", "At least one corresponding author is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.DescriptionMaxLength", "Açıklama en fazla 4.000 karakter olabilir.", "Description can be at most 4,000 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.DimensionsMaxLength", "Ölçü bilgisi en fazla 200 karakter olabilir.", "Dimensions can be at most 200 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.DuplicateAuthorEmail", "Aynı e-posta adresine sahip birden fazla yazar eklenemez.", "Multiple authors cannot use the same email address."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.IdRequired", "Bildiri kimliği zorunludur.", "Submission id is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.KeywordsEnMaxLength", "İngilizce anahtar kelimeler en fazla 500 karakter olabilir.", "English keywords can be at most 500 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.KeywordsMaxLength", "Anahtar kelimeler en fazla 500 karakter olabilir.", "Keywords can be at most 500 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.KeywordsRequired", "Anahtar kelimeler zorunludur.", "Keywords are required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.OrcidMaxLength", "ORCID en fazla 50 karakter olabilir.", "ORCID can be at most 50 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.SubmissionTypeRequired", "Bildiri türü zorunludur.", "Submission type is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.TechniqueMaxLength", "Teknik bilgisi en fazla 250 karakter olabilir.", "Technique can be at most 250 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.TechniqueRequired", "Teknik bilgisi zorunludur.", "Technique is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.TitleEnMaxLength", "İngilizce başlık en fazla 300 karakter olabilir.", "English title can be at most 300 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.TitleMaxLength", "Bildiri başlığı en fazla 300 karakter olabilir.", "Submission title can be at most 300 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.TitleRequired", "Bildiri başlığı zorunludur.", "Submission title is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.TopicRequired", "Konu seçimi zorunludur.", "Topic is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.WorkNameMaxLength", "Eser adı en fazla 300 karakter olabilir.", "Work name can be at most 300 characters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Validation.WorkNameRequired", "Eser adı zorunludur.", "Work name is required."),
    };
}
