namespace Symplify.BackOffice.Persistence.Seeding.Definitions.Localization;

public static class SubmissionUiResourceSeedDefinitions
{
    public static IReadOnlyCollection<ResourceSeedDefinition> All { get; } = new List<ResourceSeedDefinition>
    {
        new("BackOffice.Sidebar", "BackOffice.Sidebar.SubmissionManagement", "Bildiri Yönetimi", "Submission Management"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.MySubmissions", "Bildirilerim", "My Submissions"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.AllSubmissions", "Tüm Bildiriler", "All Submissions"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.ReviewerUsers", "Kullanıcı Listesi", "User List"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.Reviewers", "Hakem Havuzu", "Reviewer Pool"),
        new("BackOffice.Sidebar", "BackOffice.Sidebar.ReviewerEvaluations", "Hakem Değerlendirmeleri", "Reviewer Evaluations"),
        new("BackOffice.Submissions", "BackOffice.Submissions.My.PageTitle", "Bildirilerim", "My Submissions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.PageTitle", "Yeni Bildiri Oluştur", "Create Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.BackToList", "Listeye Dön", "Back to List"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Breadcrumb.Dashboard", "Panel", "Dashboard"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Breadcrumb.MySubmissions", "Bildirilerim", "My Submissions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Breadcrumb.Create", "Yeni Bildiri", "New Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Info.Title", "Bildiri oluşturma", "Create submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Info.Description", "Bildiri, kullanıcı hesabınızın bağlı olduğu kongreye otomatik atanır. Bu ekranda kongre seçimi yapılmaz; en az bir sorumlu yazar eklenmelidir.", "Your submission is assigned automatically to the congress connected to your account. Congress selection is not available on this page; at least one corresponding author must be added."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Header.Title", "Yeni Bildiri Oluştur", "Create New Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Header.Subtitle", "Bildiri bilgilerini doldurun, yazarları ekleyin ve başvurunuzu doğrudan gönderin.", "Fill in the submission information, add authors, and submit your application directly."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.BasicInfo.Title", "Bildiri Bilgileri", "Submission Information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.BasicInfo.Subtitle", "Üyelik kongreniz, bildiri türü, konu ve ORCID bilgisini kontrol edin.", "Review your membership congress, submission type, topic, and ORCID information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.CongressLabel", "Kongre", "Congress"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.CongressMissing", "Kongre üyeliği bulunamadı", "No congress membership found"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.CongressAutoAssigned", "Bildiri, hesabınızın bağlı olduğu kongreye otomatik atanır.", "The submission is automatically assigned to the congress connected to your account."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.SubmissionTypeLabel", "Bildiri Türü", "Submission Type"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TopicLabel", "Konu", "Topic"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.OrcidLabel", "ORCID", "ORCID"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.LanguageLabel", "Bildiri Dili", "Submission Language"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TitleKeywords.Title", "Başlık ve Anahtar Kelimeler", "Title and Keywords"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TitleKeywords.Subtitle", "Türkçe alanları zorunludur. İngilizce alanları varsa doldurun.", "Turkish fields are required. Fill in English fields if available."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.ContentSection.Title", "Başlık, Anahtar Kelimeler ve Özet", "Title, Keywords and Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.ContentSection.Subtitle", "Türkçe alanları zorunludur. İngilizce alanları varsa doldurun.", "Turkish fields are required. Fill in English fields if available."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Tab.Turkish", "Türkçe", "Turkish"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Tab.English", "İngilizce", "English"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TitleLabel", "Başlık", "Title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TitlePlaceholder", "Bildiri başlığını yazın", "Enter the submission title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.KeywordsLabel", "Anahtar Kelimeler", "Keywords"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.KeywordsPlaceholder", "Örn: yapay zeka, sağlık, veri analizi", "E.g. artificial intelligence, health, data analysis"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.KeywordsHelp", "Kelimeleri virgül ile ayırın.", "Separate keywords with commas."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TitleEnLabel", "İngilizce Başlık", "English Title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TitleEnPlaceholder", "İngilizce başlık", "English title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.KeywordsEnLabel", "İngilizce Anahtar Kelimeler", "English Keywords"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.KeywordsEnPlaceholder", "artificial intelligence, health, data analysis", "artificial intelligence, health, data analysis"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.AbstractSection.Title", "Özet", "Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.AbstractSection.Subtitle", "Bildiri özetinizi sade ve anlaşılır şekilde yazın.", "Write your abstract clearly and concisely."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.AbstractLabel", "Özet", "Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.AbstractPlaceholder", "Türkçe özet metnini yazın...", "Enter the Turkish abstract..."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.AbstractHelp", "Amaç, yöntem, bulgu ve sonuç bilgilerini ekleyin.", "Include purpose, method, findings, and conclusion information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.AbstractEnLabel", "İngilizce Özet", "English Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.AbstractEnPlaceholder", "İngilizce özet...", "English abstract..."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.AbstractEnHelp", "İngilizce özet isteğe bağlıdır.", "English abstract is optional."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Submit.Title", "Gönder", "Submit"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.SubmitButton", "Bildiriyi Gönder", "Submit Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.ConfirmSubmit.Title", "Bildiri onaya gönderilsin mi?", "Send submission for approval?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.ConfirmSubmit.Text", "Onaya gönderildikten sonra bildiriyi güncelleyemeyebilirsiniz. Devam etmek istediğinize emin misiniz?", "After sending it for approval, you may not be able to update the submission. Are you sure you want to continue?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.ConfirmSubmit.ConfirmButton", "Evet, onaya gönder", "Yes, send for approval"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Processing.SubmitTitle", "Bildiri onaya gönderiliyor", "Sending submission for approval"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Processing.DraftTitle", "Bildiri kaydediliyor", "Saving submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Processing.Text", "Özet metni ve dosyalar işleniyor. Lütfen sayfayı kapatmayın.", "The abstract text and files are being processed. Please do not close the page."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Edit.PageTitle", "Bildiri Düzenle", "Edit Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Management.PageTitle", "Tüm Bildiriler", "All Submissions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Manage.PageTitle", "Bildiri Yönetimi", "Submission Management"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Reviewer.PageTitle", "Hakem Değerlendirmeleri", "Reviewer Evaluations"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Reviewer.Form.PageTitle", "Bildiri Değerlendir", "Evaluate Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.PageTitle", "Bildiri Detayı", "Submission Detail"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.PageSubtitle", "Bildiri durumunuzu, değerlendirme sonuçlarınızı ve dosyalarınızı bu ekrandan takip edebilirsiniz.", "Track your submission status, evaluation results, and documents from this page."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.PageTitle", "Sergi Başvurusu Detayı", "Exhibition Application Detail"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.PageSubtitle", "Sergi başvurusu durumunuzu, dosyalarınızı ve süreç geçmişinizi bu ekrandan takip edebilirsiniz.", "Track your exhibition application status, files, and history from this page."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.SectionTitle", "Sergi Bilgileri", "Exhibition Information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.SectionSubtitle", "Eser adı, ölçü, teknik, açıklama ve adres bilgileri.", "Artwork name, dimensions, technique, description, and address information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.WorkName", "Eserin Adı", "Artwork Name"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.Dimensions", "Eserin Ölçüleri", "Artwork Dimensions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.Technique", "Uygulanan Teknik", "Technique"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.Address", "Adres", "Address"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.Description", "Açıklama", "Description"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.Empty", "Sergi başvurusu detay bilgisi bulunamadı.", "Exhibition application detail information was not found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.ContactDescription", "Başvurudaki eser sahibi ve iletişim bilgileri.", "Owner and contact information for the application."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Kind.ExhibitionImage", "Sergi Görseli", "Exhibition Image"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Breadcrumb.Dashboard", "Panel", "Dashboard"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Breadcrumb.MySubmissions", "Bildirilerim", "My Submissions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Breadcrumb.Detail", "Detay", "Detail"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.CorrespondingAuthor", "Sorumlu Yazar", "Corresponding Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.BackToList", "Listeye Dön", "Back to List"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Edit", "Düzenle", "Edit"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Print", "Yazdır", "Print"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.RejectedAccessLimited.Title", "Bu bildiri reddedildi.", "This submission was rejected."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.RejectedAccessLimited.Description", "Başvuru özeti ve işlem geçmişi görüntülenebilir. Hakem değerlendirmeleri, kabul belgeleri, ödeme belgeleri ve dosya indirme işlemleri yazar erişimine kapatılmıştır.", "The submission summary and process history can be viewed. Reviewer evaluations, acceptance documents, payment documents, and file downloads are closed to author access."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AuthorGuidance.ActionTitle", "Düzenleme yapmanız gerekiyor", "You need to make changes"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AuthorGuidance.ActionDescription", "Bildiriniz için düzeltme istenmiş. Düzenle butonunu kullanarak bilgileri güncelleyip bildiriyi tekrar gönderebilirsiniz.", "Changes were requested for your submission. Use the edit button to update the details and resubmit it."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AuthorGuidance.PassiveTitle", "Şu anda sizden işlem beklenmiyor", "No action is required from you right now"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AuthorGuidance.PassiveDescription", "Bildiriniz inceleme sürecindedir. Sizden ek bilgi veya düzeltme istenirse bu alanda göreceksiniz.", "Your submission is being reviewed. If additional information or changes are requested from you, you will see it here."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Tasks.TrackReviews", "Değerlendirme sonucu oluştuğunda bu ekranda görebilirsiniz.", "When an evaluation result is available, you can see it on this page."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Tasks.CheckFiles", "Yüklediğiniz dosyaları Dosya & Belgeler sekmesinden inceleyebilirsiniz.", "You can review uploaded files from the Files & Documents tab."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.EditSubmission", "Bildiri Bilgilerini Düzenle", "Edit Submission Details"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Flow.Title", "Başvuru Durumu", "Submission Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Flow.Description", "Bildirinizin hangi aşamada olduğunu buradan takip edebilirsiniz.", "You can follow the current status of your submission here."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Flow.CurrentStatus", "Mevcut durum", "Current status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Flow.Progress", "İlerleme", "Progress"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Flow.WhatShouldIDo", "Ne yapmalıyım?", "What should I do?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Step.Submission", "Başvuru", "Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Step.Review", "Değerlendirme", "Review"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Step.Author", "Sizden Beklenen", "Your Action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Step.Decision", "Karar", "Decision"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Status.Submitted", "Gönderildi", "Submitted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Status.Draft", "Taslak", "Draft"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Status.Waiting", "Beklemede", "Pending"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Status.Completed", "Tamamlandı", "Completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Status.NotRequired", "Şu an yok", "Not needed now"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Status.None", "Şu an yok", "None right now"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Status.ActionWaiting", "Düzenleme gerekli", "Changes required"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Status.ReviewCompletedFormat", "{0} tamamlandı", "{0} completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Stat.CurrentStatus", "Şu anki durum", "Current status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Stat.Review", "Hakem değerlendirmesi", "Reviewer evaluation"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Stat.SubmittedAt", "Gönderim tarihi", "Submitted at"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Stat.LatestFile", "Son dosya", "Latest file"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.ReviewCountFormat", "{0} / {1} tamamlandı", "{0} / {1} completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.NotSubmittedYet", "Henüz gönderilmedi", "Not submitted yet"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.NoFile", "Dosya yok", "No file"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Tab.Summary", "Özet", "Summary"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Tab.SummaryDescription", "Bildiri bilgisi ve yapılacak işlem", "Submission details and next action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Tab.Reviews", "Hakem Değerlendirmeleri", "Reviewer Evaluations"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Tab.ReviewsDescription", "Değerlendirme sonuçları ve size iletilen notlar", "Evaluation results and notes shared with you"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Tab.Files", "Dosya & Belgeler", "Files & Documents"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Tab.FilesDescription", "Tam metin, ödeme belgesi ve kabul yazıları", "Full text, payment documents, and acceptance letters"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Tab.History", "Süreç Geçmişi", "Application Updates"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Tab.HistoryDescription", "Bildiri hareketleri", "Submission updates"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.SubmissionInfo", "Bildiri Bilgileri", "Submission Information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.SubmissionNumber", "Bildiri No", "Submission No"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.SubmissionType", "Bildiri Türü", "Submission Type"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Topic", "Konu", "Topic"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.PresentationLanguage", "Sunum Dili", "Presentation Language"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Abstract", "Özet", "Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AbstractEmpty", "Özet bilgisi girilmemiş.", "No abstract has been entered."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.KeywordsEmpty", "Anahtar kelime yok", "No keywords"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Authors", "Yazarlar", "Authors"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AuthorsEmpty", "Yazar bilgisi bulunamadı.", "No author information found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AuthorRole.Corresponding", "Sorumlu Yazar", "Corresponding Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AuthorRole.Default", "Yazar", "Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AuthorInstitutionEmpty", "Kurum bilgisi yok", "No institution information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AuthorBadge.Corresponding", "İletişim Yazarı", "Contact Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.AuthorBadge.CoAuthor", "Ortak Yazar", "Co-author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.NextStep", "Sonraki adım", "Next step"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.ShortInfo", "Kısa Bilgi", "Quick Info"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment", "Ödeme", "Payment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.LastProcessNote", "Son süreç notu", "Latest process note"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.NoProcessNote", "Henüz süreç notu bulunmuyor.", "There is no process note yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.GoToFilesTab", "Dosya Sekmesine Git", "Go to Files Tab"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.PrivateTitle", "Değerlendirme bilgileri", "Evaluation information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.PrivateDescription", "Bu bölümde hakem kimlikleri gösterilmez; yalnızca size iletilen değerlendirme notları ve istenen düzeltmeler yer alır.", "Reviewer identities are not shown here; only evaluation notes and requested changes shared with you are displayed."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.Empty", "Henüz tamamlanmış değerlendirme bulunmuyor.", "There is no completed evaluation yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.NotificationFormat", "Değerlendirme {0}", "Evaluation {0}"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.Date", "Değerlendirme tarihi", "Evaluation date"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.CommentEmpty", "Değerlendirme notu bulunmuyor.", "No evaluation note found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.ScoreSummary", "Puan Özeti", "Score Summary"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.TotalScoreFormat", "Toplam puan: {0}", "Total score: {0}"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.ScoreCountFormat", "Değerlendirilen kriter sayısı: {0}", "Evaluated criteria count: {0}"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.UploadedFiles", "Yüklü Dosyalar", "Uploaded Files"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.FileCountFormat", "{0} Dosya", "{0} File(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Empty", "Bu bildiriye ait yüklü dosya bulunamadı.", "No uploaded file was found for this submission."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.UploadedAt", "Yüklenme", "Uploaded"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Download", "İndir", "Download"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Active", "Aktif", "Active"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.RejectedAccessLimited", "Reddedilen bildirilerde dosya ön izleme ve indirme işlemleri yazar erişimine kapalıdır.", "File preview and download actions are closed to author access for rejected submissions."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Documents.ActionsTitle", "Belge yükleme ve takip", "Document upload and tracking"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Documents.ActionsDescription", "Bu bölüm tam metin, ödeme belgesi, ek belge ve kabul yazıları için kullanılır.", "Use this section for full text, payment documents, additional documents, and acceptance letters."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Documents.InfoTitle", "Belge istendiğinde yükleme alanı açılır", "Upload area opens when a document is required"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Documents.InfoDescription", "Ödeme belgesi, tam metin veya ek belge istendiğinde yükleme işlemini bu sekmeden yapabilirsiniz. Düzeltme istenirse bildiri bilgilerini güncellemek için Düzenle butonunu kullanın.", "When a payment document, full text, or additional document is requested, upload it from this tab. If changes are requested, use the Edit button to update your submission details."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Documents.ActionFullText", "Tam metin veya ek belge istendiğinde dosyanızı bu sekmeden yükleyin.", "When full text or an additional document is requested, upload it from this tab."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Documents.ActionPayment", "Ödeme adımına geçildiğinde ödeme belgenizi bu sekmeden yükleyin.", "When the payment step is opened, upload your payment document from this tab."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Documents.ActionAcceptanceLetter", "Kabul yazısı oluştuğunda bu sekmeden indirilebilir.", "When the acceptance letter is generated, it can be downloaded from this tab."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Documents.AcceptanceTitle", "Kabul Belgeleri", "Acceptance Documents"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Documents.AcceptanceDescription", "Kabul yazısı veya kabul belgesi oluştuğunda burada listelenir.", "Acceptance letters or acceptance documents are listed here when they are generated."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Documents.AcceptanceEmpty", "Bu bildiri için henüz kabul belgesi oluşturulmadı.", "No acceptance document has been generated for this submission yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Revision.Title", "Revizyon İşlemi", "Revision Action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Revision.Description", "Revizyon sadece dosya yüklemek değildir; bildiri bilgileri de güncellenir.", "Revision is not only file upload; submission details are also updated."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Revision.WaitingTitle", "Revizyon bekleniyor", "Revision required"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Revision.WaitingDescription", "Hakem/editör taleplerine göre başlık, özet, anahtar kelimeler, konu, bildiri türü ve yazar bilgilerini düzenleyip bildiriyi tekrar gönderebilirsiniz.", "You can update the title, abstract, keywords, topic, submission type, and author information according to reviewer/editor requests, then resubmit the submission."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Revision.FileTitle", "Ek dosya revizyonu", "Additional file revision"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Revision.FileDescription", "Dosya yükleme akışı ayrı fazda MinIO/dosya versiyonlama ile bağlanacaktır. Bu fazda revizyon için ana işlem bildiri formunu düzenleyip tekrar göndermektir.", "The file upload flow will be connected with MinIO/file versioning in a separate phase. In this phase, the main revision action is editing the submission form and resubmitting it."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Revision.ClosedTitle", "Revizyon işlemi açık değil", "Revision is not open"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Revision.ClosedDescription", "Düzeltme istenmediği sürece bildiri bilgileri değiştirilemez. Düzeltme istenirse Düzenle butonu açılır.", "Submission details cannot be changed unless changes are requested. When changes are requested, the Edit button becomes available."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.Title", "Süreç Geçmişi", "Application Updates"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.CountFormat", "Son {0} işlem", "Last {0} update(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.Empty", "Henüz süreç bilgisi bulunmuyor.", "There are no updates yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.GenericTitle", "Güncelleme yapıldı", "Update recorded"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.GenericDescription", "Bildirinizle ilgili yeni bir işlem yapıldı.", "A new update was recorded for your submission."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Kind.FullText", "Tam metin", "Full text"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Kind.Presentation", "Sunum dosyası", "Presentation file"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Kind.Revision", "Düzeltme dosyası", "Updated file"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Kind.AcceptanceLetter", "Kabul belgesi", "Acceptance document"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Kind.ParticipationCertificate", "Katılım belgesi", "Certificate of participation"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Kind.Other", "Ek belge", "Additional document"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.RecommendationDefault", "Değerlendirme notu", "Evaluation note"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.NoteTitle", "Bilgilendirme", "Information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.DraftTitle", "Taslak oluşturuldu", "Draft created"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.DraftDescription", "Bildiriniz taslak olarak kaydedildi.", "Your submission was saved as a draft."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.SubmittedTitle", "Başvuru gönderildi", "Submission sent"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.SubmittedDescription", "Bildiriniz değerlendirilmek üzere gönderildi.", "Your submission was sent for evaluation."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.ReviewAssignmentTitle", "Değerlendirme hazırlığı", "Evaluation preparation"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.ReviewAssignmentDescription", "Bildiriniz değerlendirme için hazırlanıyor.", "Your submission is being prepared for evaluation."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.ReviewStartedTitle", "Değerlendirme başladı", "Evaluation started"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.ReviewStartedDescription", "Bildiriniz değerlendiriliyor. Sonuç oluştuğunda bu ekranda görebilirsiniz.", "Your submission is being evaluated. You can see the result here when it is available."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.ReviewsCompletedDescription", "Hakem değerlendirmeleri tamamlandı. Bildiriniz karar aşamasına alındı.", "Reviewer evaluations are complete. Your submission has moved to the decision stage."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.EditorialDecisionTitle", "Karar aşaması", "Decision stage"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.EditorialDecisionDescription", "Değerlendirmeler tamamlandı. Son karar hazırlandığında bu ekranda görebilirsiniz.", "Evaluations are complete. You can see the final decision here when it is ready."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.AcceptedTitle", "Başvuru kabul edildi", "Submission accepted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.AcceptedDescription", "Bildiriniz kabul edildi. Kabul belgesi hazır olduğunda Dosya & Belgeler sekmesinde görünecektir.", "Your submission has been accepted. The acceptance document will appear in Files & Documents when it is ready."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.PaymentTitle", "Belge veya ödeme bekleniyor", "Document or payment required"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.PaymentDescription", "Kabul sonrası istenen belge veya ödeme bilgisi için Dosya & Belgeler sekmesini kontrol edin.", "Please check Files & Documents for any document or payment requested after acceptance."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.PaymentCompletedTitle", "Ödeme işlemi yapıldı", "Payment completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.PaymentRevertedTitle", "Ödeme işlemi geri alındı", "Payment completion reverted"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.ReviewerAssignedTitle", "Hakem atandı", "Reviewer assigned"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.ReviewCompletedTitle", "Hakem değerlendirmesi tamamlandı", "Reviewer evaluation completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.CompletedTitle", "İşlem tamamlandı", "Completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.CompletedDescription", "Bildiri süreciniz tamamlandı.", "Your submission process is complete."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.RejectedTitle", "Başvuru sonuçlandı", "Submission completed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.RejectedDescription", "Bildiri değerlendirmeniz sonuçlandı. Size iletilen notları Hakem Değerlendirmeleri sekmesinde görebilirsiniz.", "Your submission evaluation is complete. You can view the notes shared with you in Reviewer Evaluations."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.WithdrawnTitle", "Başvuru geri çekildi", "Submission withdrawn"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.WithdrawnDescription", "Bu bildiri başvurusu geri çekildi.", "This submission has been withdrawn."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.Title", "Yazar Ekle", "Add Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.Subtitle", "Yazar bilgilerini eksiksiz doldurun ve listeye ekleyin.", "Complete the author information and add it to the list."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.RequiredWarning", "En az <strong>1 sorumlu yazar</strong> eklenmelidir. Unvan, ad soyad, e-posta, kurum ve yazar rolü zorunludur.", "At least <strong>1 corresponding author</strong> must be added. Title, full name, email, institution and author role are required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.TitleLabel", "Unvan", "Title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.TitlePlaceholder", "Unvan seçiniz", "Select title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.FullNameLabel", "Ad Soyad", "Full Name"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.FullNamePlaceholder", "Yazar ad soyad", "Author full name"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.InstitutionLabel", "Kurum", "Institution"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.InstitutionPlaceholder", "Üniversite / kurum adı", "University / institution name"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.EmailLabel", "E-posta", "Email"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.EmailPlaceholder", "mail@ornek.com", "mail@example.com"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.RoleLabel", "Yazar Rolü", "Author Role"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.RoleCorresponding", "Sorumlu Yazar", "Corresponding Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.RoleAuthor", "Yazar", "Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.AddButton", "Yazarı Listeye Ekle", "Add Author to List"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.UpdateButton", "Yazarı Güncelle", "Update Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.CancelEditButton", "Düzenlemeyi İptal Et", "Cancel Editing"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.Validation.TitleRequired", "Yazar unvanı zorunludur.", "Author title is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.Validation.FullNameRequired", "Yazar adı soyadı zorunludur.", "Author full name is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.Validation.EmailRequired", "Yazar e-posta adresi zorunludur.", "Author email address is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.Validation.EmailInvalid", "Geçerli bir yazar e-posta adresi giriniz.", "Enter a valid author email address."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.Empty", "Yazar eklediğinde bilgiler bu alanda listelenecek.", "When you add an author, the information will be listed here."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.EditAriaLabel", "Yazarı düzenle", "Edit author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.DeleteAriaLabel", "Yazarı sil", "Delete author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.Title", "Eklenen Yazarlar", "Added Authors"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.Subtitle", "Kaydetmeden önce listeyi kontrol edin.", "Review the list before saving."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.CountSuffix", "Yazar", "Author(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.PageTitle", "Bildirilerim", "My Submissions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.PageSubtitle", "Başvurularınızı buradan takip edebilir, taslaklarınızı düzenleyebilirsiniz.", "You can follow your submissions here and edit your drafts."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Breadcrumb.Dashboard", "Panel", "Dashboard"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Breadcrumb.Current", "Bildirilerim", "My Submissions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Info.Title", "Bildiri başvurusu", "Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Info.Description", "Yeni bildiri ekleyebilir, taslaklarınızı düzenleyebilir ve hazır olan bildirilerinizi değerlendirme için gönderebilirsiniz.", "You can create a new submission, edit your drafts, and send completed submissions for evaluation."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.List.Title", "Bildiri Listem", "My Submission List"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.List.Description", "Başvurularınızın durumunu ve son işlemleri buradan takip edin.", "Follow the status and latest updates of your submissions here."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Action.NewSubmission", "Yeni Bildiri", "New Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Search.Label", "Arama", "Search"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Search.Placeholder", "Bildiri no, başlık, konu veya yazar ara...", "Search by submission number, title, topic, or author..."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Search.Filter", "Ara", "Search"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Search.Clear", "Temizle", "Clear"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Table.Submission", "Bildiri", "Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Table.Topic", "Konu", "Topic"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Table.Authors", "Yazarlar", "Authors"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Table.Payment", "Ödeme", "Payment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Table.Status", "Durum", "Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Table.Date", "Tarih", "Date"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Table.Action", "İşlem", "Action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Table.AuthorCountFormat", "{0} yazar", "{0} author(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Action.View", "Detayı Gör", "View Details"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Action.Edit", "Düzenle", "Edit"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Action.Delete", "Sil", "Delete"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Delete.ConfirmTitle", "Bu taslak silinsin mi?", "Delete this draft?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Delete.ConfirmText", "Taslak bildiriniz silinecek. Bu işlem geri alınamaz.", "Your draft submission will be deleted. This action cannot be undone."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Delete.ConfirmButton", "Evet, sil", "Yes, delete"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Empty.Title", "Henüz bildiri başvurunuz bulunmuyor.", "You do not have any submissions yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Empty.CreateButton", "Yeni Bildiri Oluştur", "Create New Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Pagination.InfoFormat", "Toplam {0} kayıt, sayfa {1} / {2}", "Total {0} records, page {1} / {2}"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Pagination.Previous", "Önceki", "Previous"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Pagination.Next", "Sonraki", "Next"),

        new("BackOffice.Submissions", "BackOffice.Submissions.Create.SubmissionTypeLockedHelp", "Başvuru türü seçtiğiniz gönderim bağlantısına göre atanır.", "The submission type is assigned based on the selected submission link."),

        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.Sidebar.Title", "Yeni Başvuru", "New Application"),

        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.AuthorHome.Title", "Bildiri türünü seçin", "Select submission type"),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.AuthorHome.Description", "İşleminize uygun bildiri türünü seçin.", "Select the submission type suitable for your process."),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.AuthorHome.OralTitle", "Sözlü Bildiri", "Oral Submission"),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.AuthorHome.PosterTitle", "Poster Bildiri", "Poster Submission"),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.AuthorHome.ExhibitionTitle", "Sergi Bildirisi", "Exhibition Submission"),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.AuthorHome.OralDescription", "Kongre programında sözlü sunum olarak değerlendirilmesini istediğiniz çalışmayı gönderin.", "Submit the work you would like to be evaluated as an oral presentation in the congress program."),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.AuthorHome.PosterDescription", "Poster formatında değerlendirilmesini istediğiniz bildiriyi sisteme ekleyin.", "Add the submission you would like to be evaluated in poster format."),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.AuthorHome.ExhibitionDescription", "Eser bilgilerini ve görsel/PDF dosyanızı yükleyerek sergi bildirisi oluşturun.", "Create an exhibition submission by entering artwork details and uploading your image/PDF file."),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.AuthorHome.CreateButton", "Bildiri Oluştur", "Create Submission"),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.AuthorHome.Empty", "Aktif kongre için başvuru türü bulunamadı.", "No submission type was found for the active congress."),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.Home.Title", "Yeni Başvuru Gönder", "Submit New Application"),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.Home.Description", "Aktif kongrenin desteklediği başvuru türlerinden birini seçerek gönderim yap.", "Select one of the application types supported by the active congress."),

        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.Home.StartButton", "Başvuruya Başla", "Start Application"),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.Home.Empty", "Aktif kongre için başvuru türü bulunamadı.", "No application type was found for the active congress."),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.Home.MySubmissionsTitle", "Mevcut Bildirilerim", "My Current Submissions"),
        new("BackOffice.SubmissionEntry", "BackOffice.SubmissionEntry.Home.MySubmissionsButton", "Tüm Bildirilerimi Gör", "View All My Submissions"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.PageTitle", "Sergi Başvurusu", "Exhibition Application"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.InfoTitle", "Sergi başvurusu", "Exhibition application"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.InfoDescription", "Eser bilgilerini doldurun ve başvuru görselinizi yükleyin. Başvurunuz hesabınıza bağlı aktif kongreye gönderilir.", "Enter the artwork information and upload your application file. Your application is sent to the active congress connected to your account."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.HeaderTitle", "Sergi Başvurusu Oluştur", "Create Exhibition Application"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.HeaderSubtitle", "Eser adı, ölçü, teknik, açıklama, adres ve dosya bilgilerini girin.", "Enter the artwork name, dimensions, technique, description, address, and file information."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.WorkInfoTitle", "Eser Bilgileri", "Artwork Information"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.WorkInfoSubtitle", "Başvuru yapılacak kongre ve sergi türü otomatik belirlenir.", "The congress and exhibition type are determined automatically."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.TypeMissing", "Sergi başvuru türü bulunamadı", "Exhibition application type was not found"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.WorkName", "Eserin Adı", "Artwork Name"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Dimensions", "Eserin Ölçüleri", "Artwork Dimensions"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Technique", "Uygulanan Teknik", "Applied Technique"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Description", "Açıklama", "Description"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.DescriptionPlaceholder", "Varsa vermek istediğiniz ek bilgi", "Additional information, if any"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Address", "Adresiniz", "Your Address"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.FileTitle", "Dosya Yükle", "File Upload"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.FileSubtitle", "Aynı eser için birden fazla görsel varsa kolaj olarak tek dosya yükleyin.", "If you have more than one image for the same work, upload them as a single collage file."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.FileDropTitle", "Lütfen Dosyanızı Buradan Yükleyiniz", "Please Upload Your File"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.FileHelp", "JPG, PNG, WEBP veya PDF. Maksimum 20 MB.", "JPG, PNG, WEBP, or PDF. Maximum 20 MB."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.SubmitButton", "Başvuruyu Gönder", "Submit Application"),

        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.WorkNamePlaceholder", "Eser adını yazın", "Enter artwork name"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.DimensionsPlaceholder", "Örn: 50x70 cm", "E.g. 50x70 cm"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.TechniquePlaceholder", "Örn: Yağlı boya, akrilik, dijital çalışma", "E.g. oil painting, acrylic, digital work"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.AddressPlaceholder", "İletişim ve teslimat için adresinizi yazın", "Enter your address for contact and delivery"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Success", "Sergi başvurusu oluşturuldu ve onaya gönderildi.", "The exhibition application has been created and submitted for review."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.NoActiveCongress", "Sergi başvurusu gönderebileceğiniz aktif bir kongre üyeliği bulunamadı.", "No active congress membership was found for exhibition application."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.CongressRequired", "Kongre bilgisi zorunludur.", "Congress information is required."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.TypeRequired", "Sergi başvurusu için geçerli bir başvuru türü seçilmelidir.", "A valid exhibition application type must be selected."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.WorkNameRequired", "Eser adı zorunludur.", "Artwork name is required."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.WorkNameMaxLength", "Eser adı en fazla 300 karakter olabilir.", "Artwork name can be at most 300 characters."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.DimensionsMaxLength", "Eser ölçüleri en fazla 200 karakter olabilir.", "Artwork dimensions can be at most 200 characters."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.TechniqueRequired", "Uygulanan teknik zorunludur.", "Applied technique is required."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.TechniqueMaxLength", "Uygulanan teknik en fazla 250 karakter olabilir.", "Applied technique can be at most 250 characters."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.DescriptionMaxLength", "Açıklama en fazla 4000 karakter olabilir.", "Description can be at most 4000 characters."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.AddressRequired", "Adres zorunludur.", "Address is required."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.AddressMaxLength", "Adres en fazla 1000 karakter olabilir.", "Address can be at most 1000 characters."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.FileRequired", "Sergi görseli yüklenmelidir.", "The exhibition file is required."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.FileTooLarge", "Sergi dosyası en fazla 20 MB olabilir.", "The exhibition file can be at most 20 MB."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.FileInvalidType", "Sergi dosyası JPG, PNG, WEBP veya PDF formatında olmalıdır.", "The exhibition file must be in JPG, PNG, WEBP, or PDF format."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.StorageBucketMissing", "Başvuru dosya depolama ayarı yapılandırılmamış.", "Submission file storage bucket is not configured."),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Validation.AuthorsRequired", "Başvuru sahibi bilgisi oluşturulamadı.", "Application owner information could not be created."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.TitleSearchPlaceholder", "Unvan ara...", "Search title..."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.TitleNoResults", "Eşleşen unvan bulunamadı.", "No matching title was found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.OrcidHelp", "Varsa ORCID numarasını giriniz.", "Enter the ORCID number if available."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.RolePlaceholder", "Rol seçiniz", "Select role"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.Validation.InstitutionRequired", "Yazar kurum bilgisi zorunludur.", "Author institution is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.Validation.RoleRequired", "Yazar rolü zorunludur.", "Author role is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.Validation.DuplicateEmail", "Bu e-posta adresi ile bir yazar zaten eklendi. Aynı e-posta adresiyle ikinci bir yazar eklenemez.", "An author with this email address has already been added. You cannot add another author with the same email address."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorForm.Validation.PendingAuthorNotAdded", "Yazar bilgilerini listeye eklemek için önce “Yazarı Listeye Ekle” butonuna basınız.", "Click “Add Author to List” before submitting the author information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorEditModal.Title", "Yazar Güncelle", "Update Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorEditModal.Subtitle", "Yazar bilgilerini kontrol edip güncelleyin.", "Review and update the author information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorEditModal.SaveButton", "Yazarı Güncelle", "Update Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorCard.EmailLabel", "E-posta", "Email"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorCard.InstitutionLabel", "Kurum / Üniversite", "Institution / University"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorCard.OrcidLabel", "ORCID", "ORCID"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.Validation.AtLeastOneCorrespondingAuthor", "En az bir sorumlu yazar eklenmelidir.", "At least one corresponding author must be added."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.Validation.TitleRequired", "Listedeki her yazar için unvan seçilmelidir.", "A title must be selected for every listed author."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.Validation.EmailRequired", "Listedeki her yazar için geçerli e-posta girilmelidir.", "A valid email address must be entered for every listed author."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.Validation.InstitutionRequired", "Listedeki her yazar için kurum bilgisi girilmelidir.", "Institution information must be entered for every listed author."),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.Validation.DuplicateEmail", "Aynı e-posta adresiyle birden fazla yazar eklenemez.", "Multiple authors cannot be added with the same email address."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Validation.SubmissionTypeRequired", "Bildiri türü zorunludur.", "Submission type is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Validation.TopicRequired", "Konu seçimi zorunludur.", "Topic is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Validation.TitleRequired", "Bildiri başlığı zorunludur.", "Submission title is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Validation.KeywordsRequired", "Anahtar kelimeler zorunludur.", "Keywords are required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Validation.AbstractRequired", "Özet zorunludur.", "Abstract is required."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Validation.NoActiveCongress", "Bildiri gönderebileceğiniz aktif bir kongre üyeliği bulunamadı.", "No active congress membership was found for submission."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Validation.ExhibitionFormOnly", "Sergi başvuruları sergi başvuru formundan gönderilmelidir.", "Exhibition applications must be submitted through the exhibition application form."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Validation.AuthorTitleRequired", "Her yazar için unvan seçilmelidir.", "A title must be selected for every author."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Success.CreatedAndSubmitted", "Bildiri oluşturuldu ve onaya gönderildi.", "Submission was created and sent for approval."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Success.DraftCreated", "Bildiri taslak olarak kaydedildi.", "Submission was saved as draft."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Edit.Success.UpdatedAndSubmitted", "Bildiri güncellendi ve onaya gönderildi.", "Submission was updated and sent for approval."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Edit.Success.Updated", "Bildiri güncellendi.", "Submission was updated."),

        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Title", "Tam Metin ve Sunum Dosyaları", "Full Text and Presentation Files"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.ActiveDescription", "Ödeme işleminiz tamamlandı. Tam metin dosyanızı ve gerekli ise video sunumunuzu buradan yükleyebilirsiniz.", "Your payment has been completed. You can upload your full text document and, if needed, your presentation video here."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.LockedDescription", "Bu alan ödeme işlemi tamamlandıktan sonra aktif olacaktır.", "This section will become available after the payment is completed."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.EditorDescription", "Ödeme sonrası tam metin ve varsa video sunum dosyasını buradan yönetebilirsiniz.", "You can manage the full text document and, if available, the presentation video here after payment."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.StatusActive", "Yükleme Aktif", "Upload Active"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.StatusLocked", "Ödeme Bekleniyor", "Payment Pending"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextTitle", "Tam Metin Dosyası", "Full Text Document"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextHelp", "Yalnızca DOCX formatında yükleyiniz. Maksimum 50 MB.", "Upload in DOCX format only. Maximum 50 MB."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Required", "Zorunlu", "Required"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextEmpty", "Henüz tam metin dosyası yüklenmedi.", "No full text document has been uploaded yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.UploadFullText", "Tam Metin Yükle", "Upload Full Text"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.UploadFullTextSuccess", "Tam metin dosyanız yüklendi.", "Your full text document has been uploaded."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.VideoTitle", "Video Sunum", "Presentation Video"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.VideoHelp", "Sadece kongreye katılamayacak yazarlar içindir. MP4, MOV veya WEBM. Maksimum 500 MB.", "Only for authors who cannot attend the congress. MP4, MOV, or WEBM. Maximum 500 MB."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Optional", "Gerekirse", "If needed"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.AttendanceQuestion", "Kongreye katılım durumunuzu seçin", "Select your congress attendance status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Attending", "Kongreye katılacağım", "I will attend the congress"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.AttendingHelp", "Video yüklemeniz gerekmez.", "You do not need to upload a video."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.NotAttending", "Katılamayacağım, video sunum yükleyeceğim", "I cannot attend; I will upload a presentation video"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.NotAttendingHelp", "Bu seçenekte video yükleme alanı açılır.", "This option opens the video upload field."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Selected", "Seçili", "Selected"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Select", "Seç", "Select"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.UploadVideo", "Video Sunum Yükle", "Upload Presentation Video"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.UploadVideoSuccess", "Video sunum dosyanız yüklendi.", "Your presentation video has been uploaded."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.ReplaceHelp", "Yeni dosya seçmezseniz mevcut dosya korunur.", "If you do not select a new file, the existing file will be kept."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.VideoEditorHelp", "Yazar kongreye katılamayacaksa video sunum dosyası buradan yönetilir.", "If the author cannot attend the congress, the presentation video is managed here."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.UploadLocked", "Tam metin ve video yükleme alanı ödeme işlemi tamamlandıktan sonra aktif olur.", "The full text and video upload section becomes active after the payment is completed."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Validation.FullTextRequired", "Lütfen tam metin dosyası seçin.", "Please select a full text document."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Validation.FullTextType", "Tam metin dosyası yalnızca DOCX formatında olmalıdır.", "The full text document must be in DOCX format only."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Validation.FullTextSize", "Tam metin dosyası en fazla 50 MB olabilir.", "The full text document can be at most 50 MB."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Validation.VideoRequired", "Lütfen video sunum dosyası seçin.", "Please select a presentation video file."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Validation.VideoType", "Video sunum dosyası MP4, MOV veya WEBM formatında olmalıdır.", "The presentation video must be in MP4, MOV, or WEBM format."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Validation.VideoSize", "Video sunum dosyası en fazla 500 MB olabilir.", "The presentation video can be at most 500 MB."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.Delete", "Sil", "Delete"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Action.BulkDelete", "Seçilenleri Sil", "Delete Selected"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Confirm.Delete", "Tam metin dosyası kalıcı olarak silinecek. Devam edilsin mi?", "The full-text file will be permanently deleted. Continue?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Confirm.BulkDelete", "Seçilen {0} tam metin dosyası kalıcı olarak silinecek. Devam edilsin mi?", "The selected {0} full-text files will be permanently deleted. Continue?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Confirm.DeleteButton", "Evet, Sil", "Yes, Delete"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.Deleted", "Tam metin dosyası silindi.", "The full-text file was deleted."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.BulkDeleted", "{0} tam metin dosyası silindi.", "{0} full-text files were deleted."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.BulkDeletePartial", "{0} dosya silindi, {1} dosya silinemedi, {2} kayıt atlandı.", "{0} files were deleted, {1} files could not be deleted, and {2} records were skipped."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.DeleteFailed", "Tam metin dosyası silinemedi. Kayıt korunmuştur.", "The full-text file could not be deleted. The record was preserved."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.OnlyFullTextDelete", "Bu işlem yalnızca tam metin dosyaları için kullanılabilir.", "This action can only be used for full-text files."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.Message.StorageNotConfigured", "Dosya depolama ayarı bulunamadığı için silme işlemi tamamlanamadı.", "The deletion could not be completed because file storage is not configured."),

        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Kicker", "Bildiri Takibi", "Submission Tracking"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Action.BackHome", "Ana Sayfa", "Home"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.List.CountFormat", "{0} bildiri", "{0} submissions"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Empty.Description", "Aktif kongre için henüz bildiri veya sergi başvurunuz bulunmuyor.", "You do not have any submission or exhibition application for the active congress yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Card.SubmissionNo", "Bildiri No", "Submission No"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Card.CorrespondingAuthor", "Sorumlu Yazar", "Corresponding Author"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Author.Card.Authors", "Yazarlar", "Authors"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Kicker", "Yeni Başvuru", "New Application"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Step.Basic.Title", "Temel Bilgi", "Basic Information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Step.Basic.Text", "Kongre, tür, konu ve dil.", "Congress, type, topic, and language."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Step.Content.Title", "Başlık & Özet", "Title & Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Step.Content.Text", "Başlık, özet ve anahtar kelimeler.", "Title, abstract, and keywords."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Step.Authors.Title", "Yazarlar", "Authors"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Step.Authors.Text", "Unvan, kurum, e-posta.", "Title, institution, email."),

        new("BackOffice.Submissions", "BackOffice.Submissions.Create.DefaultSubmissionTypeName", "Sözlü Bildiri", "Oral Submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Type.Oral", "Sözlü Bildiri", "Oral Presentation"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Type.Poster", "Poster Bildiri", "Poster Presentation"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Type.Exhibition", "Sergi Bildirisi", "Exhibition Application"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TypeKickerFormat", "Yeni {0}", "New {0}"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TypeTitleFormat", "{0} Oluştur", "Create {0}"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TypeSubtitle", "Sözlü sunum olarak değerlendirilecek bildirinizin bilgilerini ve yazarlarını ekleyin.", "Add the information and authors for the submission to be evaluated as an oral presentation."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TypeSubtitle.Oral", "Sözlü sunum olarak değerlendirilecek bildirinizin bilgilerini ve yazarlarını ekleyin.", "Add the information and authors for the submission to be evaluated as an oral presentation."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TypeSubtitle.Poster", "Poster olarak değerlendirilecek bildirinizin bilgilerini ve yazarlarını ekleyin.", "Add the information and authors for the submission to be evaluated as a poster presentation."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TypeSubtitle.Exhibition", "Sergi bildirinizin bilgilerini ve yazarlarını ekleyin.", "Add the information and authors for your exhibition application."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.BackHome", "Geri Dön", "Go Back"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.BasicInfo.NumberedTitle", "1. Temel Bilgiler", "1. Basic Information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.BasicInfo.TemplateDescription", "Kongre, konu ve dil bilgilerini seçin.", "Select congress, topic, and language information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TopicPlaceholder", "Konu seçiniz", "Select topic"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.TopicHelp", "Çalışmana en yakın bilimsel konuyu seç.", "Select the scientific topic closest to your study."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.OrcidPlaceholder", "ORCID numarasını yazınız", "Enter the ORCID number"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.ContentSection.NumberedTitle", "2. Başlık ve Özet", "2. Title and Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.ContentSection.TemplateDescription", "Başlık, anahtar kelime ve özet bilgilerini girin.", "Enter title, keyword, and abstract information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Tab.TurkishContent", "Türkçe İçerik", "Turkish Content"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Tab.EnglishContent", "English Content", "English Content"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.AuthorsSection.NumberedTitle", "3. İlave Yazar Bilgileri", "3. Additional Author Information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.AuthorsSection.TemplateDescription", "Sorumlu yazar ve varsa ilave yazar bilgilerini ekleyin.", "Add the corresponding author and any additional author information."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Submit.Question", "Sözlü bildiri gönderilmeye hazır mı?", "Is the oral submission ready to be submitted?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Submit.Question.Oral", "Sözlü bildiri gönderilmeye hazır mı?", "Is the oral presentation ready to be submitted?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Submit.Question.Poster", "Poster bildiri gönderilmeye hazır mı?", "Is the poster presentation ready to be submitted?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Submit.Question.Exhibition", "Sergi bildirisi gönderilmeye hazır mı?", "Is the exhibition application ready to be submitted?"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Submit.Hint", "Bildiriniz gönderildikten sonra değerlendirme süreci başlar.", "The review process starts after your submission is sent."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Create.Submit.TypeButtonFormat", "{0} Gönder", "Submit {0}"),
        new("BackOffice.Submissions", "BackOffice.Submissions.AuthorList.EmptyTitle", "Henüz yazar eklenmedi", "No authors added yet"),
        new("BackOffice.ExhibitionApplications", "BackOffice.ExhibitionApplications.Create.Kicker", "Yeni Sergi Bildirisi", "New Exhibition Application"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.ModalHelp", "Dosyanızı seçtikten sonra kaydet butonuna basınız.", "Select your file and then click save."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.SelectFile", "Dosya Seç", "Select File"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.NoFileSelected", "Henüz dosya seçilmedi.", "No file selected yet."),

        new("BackOffice.Submissions", "BackOffice.SubmissionEntry.AuthorHome.GenericDescription", "Başvuru bilgilerinizi doldurarak gönderim yapın.", "Fill in your application information and submit it."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextModalTitle", "Tam Metin Dosyası Yükle", "Upload Full Text Document"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.FullTextModalDescription", "Kabul edilen bildiriniz için tam metin dosyanızı yükleyin.", "Upload your full text document for your accepted submission."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.VideoModalTitle", "Bildiri Sunum Videosu Yükle", "Upload Submission Presentation Video"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.VideoModalDescription", "Sunum videonuzu bildirinizle ilişkilendirin.", "Attach your presentation video to your submission."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.SaveFullText", "Tam Metni Kaydet", "Save Full Text"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.SelectVideo", "Video Seç", "Select Video"),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.NoVideoSelected", "Henüz video seçilmedi.", "No video selected yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.FinalFiles.SaveVideo", "Videoyu Kaydet", "Save Video"),
        new("BackOffice.Navigation", "BackOffice.Navbar.ToggleSidebar", "Sidebar aç/kapat", "Toggle sidebar"),
        new("BackOffice.Navigation", "BackOffice.Navbar.OpenMobileMenu", "Mobil menüyü aç", "Open mobile menu"),
        new("BackOffice.Navigation", "BackOffice.Navbar.Messages", "Mesajlar", "Messages"),
        new("BackOffice.Navigation", "BackOffice.Navbar.MessagesDescription", "Kişisel mesajlarınız burada gösterilecek.", "Your personal messages will be shown here."),
        new("BackOffice.Navigation", "BackOffice.Navbar.NoUnreadMessages", "Henüz okunmamış mesaj yok.", "There are no unread messages."),
        new("BackOffice.Navigation", "BackOffice.Navbar.NotificationsDescription", "Sistem bildirimleri burada gösterilecek.", "System notifications will be shown here."),

        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Abstracts.Title", "Özet Bilgileri", "Abstract Information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Abstracts.Turkish", "Türkçe Özet", "Turkish Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Abstracts.English", "İngilizce Özet", "English Abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Abstracts.TurkishEmpty", "Türkçe özet bilgisi bulunamadı.", "Turkish abstract information was not found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Abstracts.EnglishEmpty", "İngilizce özet bilgisi bulunamadı.", "English abstract information was not found."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.UploadLocked", "Bu bildiri için şu anda ödeme belgesi yüklenemez.", "A payment document cannot be uploaded for this submission right now."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Edit.Validation.RejectedNotEditable", "Bu bildiri reddedildiği için düzenlenemez.", "This submission cannot be edited because it has been rejected."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Delete.Validation.RejectedNotDeletable", "Bu bildiri reddedildiği için silinemez.", "This submission cannot be deleted because it has been rejected."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Delete.Success", "Bildiri silindi.", "Submission was deleted."),
        new("BackOffice.Navigation", "BackOffice.Navbar.NoNotifications", "Şu anda yeni bildiriminiz yok.", "You do not have any new notifications right now."),

        // Added by localization audit: statically used keys that previously had no seed definition.
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Author.Contact", "İletişim", "Contact"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Author.Email", "E-posta", "Email"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Author.Institution", "Kurum", "Institution"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Author.Orcid", "ORCID", "ORCID"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Authors.ContactDescription", "Yazarların iletişim ve kurum bilgileri", "Author contact and institution information"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Authors.CountFormat", "{0} yazar", "{0} author(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Close", "Kapat", "Close"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Content.EnglishSubtitle", "İngilizce başlık, anahtar kelimeler ve özet", "English title, keywords, and abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Content.EnglishTitle", "İngilizce İçerik", "English Content"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Content.KeywordsLabel", "Anahtar Kelimeler", "Keywords"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Content.LanguageBadge", "{0} içeriği", "{0} content"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Content.Subtitle", "Bildiri başlığı, anahtar kelimeleri ve özet metni", "Submission title, keywords, and abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Content.Title", "Bildiri İçeriği", "Submission Content"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Content.TitleLabel", "Başlık", "Title"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Content.TurkishSubtitle", "Türkçe başlık, anahtar kelimeler ve özet", "Turkish title, keywords, and abstract"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Content.TurkishTitle", "Türkçe İçerik", "Turkish Content"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.ImageAlt", "Sergi çalışması görseli", "Exhibition work image"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.ImageEmpty", "Sergi çalışması için görsel yüklenmemiş.", "No image has been uploaded for the exhibition work."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.ImageSubtitle", "Yüklenen sergi görseli veya PDF önizlemesi", "Uploaded exhibition image or PDF preview"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Exhibition.ImageTitle", "Sergi Görseli", "Exhibition Image"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Description", "Bildiriye ait yüklenen dosyalar ve belgeler", "Uploaded files and documents for the submission"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.ImageAlt", "Yüklenen dosya önizlemesi", "Uploaded file preview"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Kind.PaymentDocument", "Ödeme Belgesi", "Payment Document"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.Title", "Dosyalar", "Files"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.LatestAction", "Son İşlem", "Latest Action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.Status", "Durum", "Status"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.DocumentApproved", "Ödeme belgesi onaylandı", "Payment document approved"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.DocumentPending", "Ödeme belgesi onay bekliyor", "Payment document pending approval"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Preview", "Önizle", "Preview"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.Comment", "Yorum", "Comment"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.CountFormat", "{0} değerlendirme", "{0} evaluation(s)"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.ScoreEmpty", "Puan girilmedi", "No score entered"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.TotalScore", "Toplam Puan", "Total Score"),

        // Added by localization audit: complete static Submission Management resource-key contracts.
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Files.CreatedAt", "Yüklenme Tarihi", "Uploaded At"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.Action", "İşlem", "Action"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.Date", "Tarih", "Date"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.History.DescriptionColumn", "Açıklama", "Description"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.DocumentsDescription", "Yüklediğiniz ödeme belgelerini ve inceleme durumlarını görüntüleyin.", "View your uploaded payment documents and their review status."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.DocumentsEmpty", "Henüz ödeme belgesi yüklenmemiş.", "No payment document has been uploaded yet."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.DocumentsTitle", "Ödeme Belgeleri", "Payment Documents"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.UploadButton", "Belgeyi Yükle", "Upload Document"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.UploadDescription", "Ödeme işleminize ait belgeyi PDF veya görsel olarak yükleyin.", "Upload the document for your payment as a PDF or image."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.UploadHelp", "İzin verilen dosya türleri ve boyut sınırı yükleme alanında gösterilir.", "Allowed file types and the size limit are shown in the upload field."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.UploadInputLabel", "Ödeme Belgesi", "Payment Document"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.UploadInvalidSize", "Ödeme belgesi izin verilen dosya boyutunu aşıyor.", "The payment document exceeds the allowed file size."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.UploadInvalidType", "Bu dosya türü ödeme belgesi olarak yüklenemez.", "This file type cannot be uploaded as a payment document."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.UploadRequired", "Ödeme belgesi seçiniz.", "Select a payment document."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.UploadSuccess", "Ödeme belgesi başarıyla yüklendi.", "The payment document was uploaded successfully."),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Payment.UploadTitle", "Ödeme Belgesi Yükle", "Upload Payment Document"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.Criterion", "Değerlendirme Kriteri", "Evaluation Criterion"),
        new("BackOffice.Submissions", "BackOffice.Submissions.Detail.Reviews.Score", "Puan", "Score"),
    };
}
