<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Symplify.Api.Application\Symplify.Api.Application.csproj" />
    <ProjectReference Include="..\Symplify.Api.Persistence\Symplify.Api.Persistence.csproj" />
  </ItemGroup>

</Project>
